{
  "hash": "42b038d61e21b1e0d94d451ff72ef36e",
  "result": {
    "engine": "knitr",
    "markdown": "# Bivariate Regression and Ordinary Least Squares {#sec-ols}\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n```{=html}\n\n<style>\n.problem {\n    background-color: #f8f9fa;\n    border: 1px solid #dee2e6;\n    border-radius: 8px;\n    padding: 20px;\n    margin: 20px 0;\n}\n.context {\n    background-color: #e8f4f8;\n    padding: 12px;\n    border-radius: 5px;\n    margin-bottom: 15px;\n    border-left: 4px solid #2874a6;\n}\n.question {\n    margin: 15px 0;\n    padding: 10px;\n    background-color: #fff3cd;\n    border-radius: 5px;\n}\n.answer-row {\n    display: flex;\n    align-items: center;\n    margin: 10px 0;\n    flex-wrap: wrap;\n    gap: 10px;\n}\n.answer-row label {\n    min-width: 320px;\n    font-weight: 500;\n}\nselect {\n    padding: 8px 12px;\n    font-size: 14px;\n    border: 2px solid #ccc;\n    border-radius: 5px;\n    min-width: 300px;\n    cursor: pointer;\n}\nselect:focus {\n    border-color: #2874a6;\n    outline: none;\n}\n.correct {\n    border-color: #28a745 !important;\n    background-color: #d4edda !important;\n}\n.incorrect {\n    border-color: #dc3545 !important;\n    background-color: #f8d7da !important;\n}\n.explanation {\n    margin-top: 10px;\n    padding: 15px;\n    background-color: #e7f3ff;\n    border-radius: 5px;\n    border-left: 4px solid #2874a6;\n}\n.note {\n    font-size: 0.85em;\n    color: #666;\n    font-style: italic;\n}\n</style>\n\n<script>\nfunction checkAnswer(selectElement, correctValue) {\n    if (selectElement.value === '') {\n        selectElement.classList.remove('correct', 'incorrect');\n    } else if (selectElement.value === correctValue) {\n        selectElement.classList.remove('incorrect');\n        selectElement.classList.add('correct');\n    } else {\n        selectElement.classList.remove('correct');\n        selectElement.classList.add('incorrect');\n    }\n}\n</script>\n\n```\n\n\n\n\n\n\n\n::: {.callout-tip collapse=\"true\"}\n## **Key Questions**\n- How do we mathematically model the relationship between two variables?\n- What is the population regression model and how do we interpret its parameters?\n- How do we derive the OLS estimator?\n- What assumptions are required for OLS to be unbiased?\n- What is omitted variable bias and when does it arise?\n- When can we interpret OLS estimates as causal effects?\n- How do we measure the precision of our estimates?\n:::\n\n::: {.callout-note collapse=\"true\"}\n## **Suggested Readings**\n- @wooldridge_introductory_2019, Ch. 2\n:::\n\n\nIn @sec-rcts,\nwe learned that randomized control trials provide the gold standard for causal inference by eliminating selection bias through random assignment.\nBut most economic questions cannot be answered with experiments.\nWe typically work with observational data where \"treatment\" is not randomly assigned.\nThis chapter introduces **Ordinary Least Squares (OLS)** regression,\nthe workhorse tool of econometrics.\nWe focus here on the **bivariate** case---a single independent variable---to build intuition before extending to multiple variables.\n\n\n## Modeling Relationships Between Variables\n\nSuppose we have two variables, $y$ and $x$.\nIn econometrics,\nwe are often interested in one of several related goals:\nestimating the **causal effect** of $x$ on $y$,\nexplaining variation in $y$ using $x$,\nor simply describing how $y$ varies with $x$.\nOLS is a tool that can help with all of these---though as we'll see,\nwhether we can interpret results causally depends on assumptions that may or may not hold.\n\nBut what do we even *mean* when we say we want to study \"how $x$ is related to $y$\"?\nWe need a precise,\nmathematical way to operationalize this question.\nThe most straightforward approach is to ask:\nwhat is the *average* value of $y$ for each different value that $x$ can take?\n\nConsider some examples.\nHow can we quantify the gender pay gap?\nWe compare the *average* wage for men versus women.\nHow do we measure the returns to education?\nWe compare the *average* wage of people with different levels of education.\nIn both cases,\nwe are asking about how the average of one variable changes across values of another.\n\n\n### Conditional Expectations\n\nThis idea of finding \"the average value of $y$ for a given value of $x$\" is exactly what we call the **conditional expectation**.\nFormally,\nthe conditional expectation of $y$ given $x$ is written as:\n\n$$\nE[Y | X = x]\n$$\n\nThis notation asks:\nif we knew that $X$ took on some specific value $x$,\nwhat would we expect $Y$ to be,\non average?\nThe conditional expectation is often the central quantity we want to model and estimate in econometrics.\n\n### Example: Education and Wages\n\nSuppose $X$ represents education level,\nwhich can take values $X = \\{\\text{hsdeg}, \\text{colldeg}, \\text{profdeg}\\}$ (high school degree,\ncollege degree,\nprofessional degree),\nand $Y$ represents hourly wage.\n\nFor each education level,\nwe can compute the average wage among people in that group.\nThis will gives us a good idea of how wages are related to education.\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Wages by education level. Each point represents an individual. Red points show the conditional expectation (average wage) for each education group.](unit3_files/figure-html/fig-cond-exp-example-1.png){#fig-cond-exp-example width=80%}\n:::\n:::\n\n\n\n\n\n\n@fig-cond-exp-example is a scatterplot with an indiviudal's wage on the y-axis and their education level on the x-axis, with each point plotted in blue.\nThe red points in @fig-cond-exp-example show the conditional expectations---the average wage for individuals *within each education category,*\ni.e., $E[Y|X=HS], E[Y|X=College], \\text{and} E[Y|X=Prof]$.\n\nThese averages tell us how we can expect wages to change when we increase education,\nwhich is precisely what we set out to measure.\n\n\n## The Population Regression Model\n\nNow that we understand what we want to estimate (the conditional expectation),\nwe need a framework for *how* to estimate it.\nBefore we can estimate anything,\nwe must first describe the underlying relationship we believe exists in the population.\n\n### The Bivariate Model\n\nThe simplest specification is called the **bivariate** (or simple) regression model:\n\n$$\ny = \\beta_0 + \\beta_1 x + \\mu\n$$ {#eq-pop-reg}\n\nwhere:\n\n- $y$ is the **dependent variable** (also called the explained, response, or outcome variable)\n- $x$ is the **independent variable** (also called the explanatory, control, or predictor variable)\n- $\\mu$ is the **error term**, which represents all unobserved factors that affect $y$\n- $\\beta_0$ and $\\beta_1$ are **population parameters**---the \"true\" values describing the relationship between $x$ and $y$ in the population\n\n::: {.callout-note}\n## The Error Term\nThe error term $\\mu$ is crucial.\nIt captures everything that affects $y$ other than $x$.\nIn a wage equation,\n$\\mu$ might include ability,\nmotivation,\nfamily connections,\nluck,\nand countless other factors we cannot observe or measure.\n:::\n\n### Connecting to Conditional Expectations\n\nHow does this regression model relate to our goal of estimating $E[Y|X]$?\nIf we assume that the error term has mean zero conditional on $x$---that is,\n$E[\\mu | x] = 0$---then:\n\n$$\nE[y | x] = E[\\beta_0 + \\beta_1 x + \\mu | x] = \\beta_0 + \\beta_1 x + E[\\mu | x] = \\beta_0 + \\beta_1 x\n$$\n\nThis is exactly the conditional expectation we set out to estimate!\nThe regression line $\\beta_0 + \\beta_1 x$ traces out the average value of $y$ for each value of $x$.\n\n\n### Interpreting the Coefficients\n\nThe coefficients in @eq-pop-reg have specific interpretations:\n\n- **$\\beta_0$ (the intercept):** The predicted value of $y$ when $x = 0$. Depending on the context, this may or may not have a meaningful interpretation.\n\n- **$\\beta_1$ (the slope):** The **marginal effect** of $x$ on $y$. Mathematically, it is the derivative:\n\n$$\n\\frac{dy}{dx} = \\beta_1\n$$\n\nThis tells us:\nwhen $x$ increases by one unit,\n$y$ changes by $\\beta_1$ units,\non average.\n\n### Example: Education and Wages\n\nA regression model relating years of education to hourly wages might be:\n\n$$\nwage = \\beta_0 + \\beta_1 \\cdot educ + \\mu\n$$\n\nwhere $wage$ is dollars per hour,\n$educ$ is years of education,\nand $\\mu$ captures all other determinants of wages (experience,\nability,\netc.).\n\nIf $\\beta_1 = 2.50$,\nthis would mean that each additional year of education is associated with \\$2.50 higher hourly wages,\non average.\n\n\n## The Regression Line: Predicted Values and Residuals\n\nThe entire goal of linear regression is to use our *sample* of the data from the wider *population*\nto estimate the values of $\\beta_0$ and $\\beta_1$ that are the best possible estimates we can generate.\nWe call these estimates $\\hat{\\beta_0}$ and $\\hat{\\beta_1}$,\nand the method we use to calculate these estimates the **estimator**.\n\nBefore we derive estimators for $\\beta_0$ and $\\beta_1$,\nlet's introduce some key concepts that will guide our approach.\n\n### Fitted Values and the Regression Line\n\nOnce we have estimates $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$,\nwe can construct the **OLS regression line** (or fitted line):\n\n$$\n\\hat{y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 x\n$$\n\nFor any value of $x$,\nthis line gives us $\\hat{y}$,\nthe **predicted value** (or **fitted value**) of $y$.\nThe regression line represents our best guess for the average value of $y$ at each level of $x$.\n\n### Residuals: The Prediction Errors\n\nOf course,\nour predictions won't be perfect.\nThe **residual** for observation $i$ is the difference between the actual value and the predicted value:\n\n$$\n\\hat{\\mu}_i = y_i - \\hat{y}_i = y_i - (\\hat{\\beta}_0 + \\hat{\\beta}_1 x_i)\n$$\n\nThe residual measures how much our prediction \"misses\" for each observation.\nPositive residuals mean we underpredicted;\nnegative residuals mean we overpredicted.\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Components of the regression line. Black points show actual values, the blue line shows predicted values, and the salmon segment illustrates a residual.](unit3_files/figure-html/fig-regression-components-1.png){#fig-regression-components width=672}\n:::\n:::\n\n\n\n\n\n\n### A Numerical Example\n\nLet's see these concepts with actual numbers.\nThe table below shows the first six observations from a regression of MPG on horsepower,\nalong with the predicted values and residuals:\n\n\n\n\n\n\n::: {#tbl-regression-example .cell tbl-cap='Example regression data showing actual values, predicted values, and residuals.'}\n::: {.cell-output-display}\n\n\n|                  | x (Horsepower) | y (MPG) | ŷ (Predicted) | û (Residual) |\n|:-----------------|:--------------:|:-------:|:-------------:|:------------:|\n|Mazda RX4         |      110       |  21.0   |     22.59     |    -1.59     |\n|Mazda RX4 Wag     |      110       |  21.0   |     22.59     |    -1.59     |\n|Datsun 710        |       93       |  22.8   |     23.75     |    -0.95     |\n|Hornet 4 Drive    |      110       |  21.4   |     22.59     |    -1.19     |\n|Hornet Sportabout |      175       |  18.7   |     18.16     |     0.54     |\n|Valiant           |      105       |  18.1   |     22.93     |    -4.83     |\n\n\n:::\n:::\n\n\n\n\n\n\nNotice how the residual column equals the actual value minus the predicted value.\nFor the first observation,\nthe car has 110 horsepower and gets 21 MPG.\nOur regression predicts it should get about 22.59 MPG,\nso the residual is $21 - 22.59 = -1.59$.\nThe negative residual means we *overpredicted*---the car actually gets slightly worse fuel economy than our model predicted.\n\n### The Key Insight: Minimize the Residuals\n\nHere's the crucial idea:\nwe want to choose $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$ so that our predictions are as good as possible.\nIn other words,\nwe want to make the residuals as small as possible.\n\nBut we can't simply minimize the sum of residuals $\\sum \\hat{\\mu}_i$,\nbecause positive and negative residuals would cancel out.\nInstead,\nwe minimize the **Sum of Squared Residuals (SSR)**:\n\n$$\nSSR = \\sum_{i=1}^{n} \\hat{\\mu}_i^2 = \\sum_{i=1}^{n} (y_i - \\hat{\\beta}_0 - \\hat{\\beta}_1 x_i)^2\n$$\n\nThis is exactly where the name \"Ordinary Least Squares\" comes from:\nwe find the estimates that make the sum of squared residuals as small as possible.\n\n\n## Deriving the OLS Estimator\n\nNow we turn to the mechanics of estimation.\nThe **population** regression model describes the true relationship,\nbut we never observe the entire population or the true values of $\\beta_0$ and $\\beta_1$.\nInstead,\nwe have a **sample** of data and must *estimate* the population parameters.\n\n### The Minimization Problem\n\nSuppose we have a sample of $n$ observations,\n$\\{(x_i, y_i): i = 1, 2, ..., n\\}$.\nAs discussed above,\nwe want to find the values of $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$ that minimize the sum of squared residuals:\n\n$$\n\\min_{\\hat{\\beta}_0, \\hat{\\beta}_1} \\sum_{i=1}^{n} (y_i - \\hat{\\beta}_0 - \\hat{\\beta}_1 x_i)^2\n$$\n\nThis is a calculus optimization problem!\nThe SSR is a function of two unknowns ($\\hat{\\beta}_0$ and $\\hat{\\beta}_1$),\nand we want to find the values that minimize it.\n\n### First-Order Conditions\n\nTo find the minimum,\nwe take partial derivatives with respect to each parameter,\nset them equal to zero,\nand solve.\nThese are called the **first-order conditions**.\n\n**Partial derivative with respect to $\\hat{\\beta}_0$:**\n\n$$\n\\frac{\\partial SSR}{\\partial \\hat{\\beta}_0} = -2 \\sum_{i=1}^{n} (y_i - \\hat{\\beta}_0 - \\hat{\\beta}_1 x_i) = 0\n$$\n\nDividing by $-2$ and rearranging:\n\n$$\n\\sum_{i=1}^{n} (y_i - \\hat{\\beta}_0 - \\hat{\\beta}_1 x_i) = 0\n$$\n\n**Partial derivative with respect to $\\hat{\\beta}_1$:**\n\n$$\n\\frac{\\partial SSR}{\\partial \\hat{\\beta}_1} = -2 \\sum_{i=1}^{n} x_i(y_i - \\hat{\\beta}_0 - \\hat{\\beta}_1 x_i) = 0\n$$\n\nDividing by $-2$:\n\n$$\n\\sum_{i=1}^{n} x_i(y_i - \\hat{\\beta}_0 - \\hat{\\beta}_1 x_i) = 0\n$$\n\n### Solving for the Intercept\n\nFrom the first condition,\ndistributing the summation:\n\n$$\n\\sum_{i=1}^{n} y_i - n\\hat{\\beta}_0 - \\hat{\\beta}_1 \\sum_{i=1}^{n} x_i = 0\n$$\n\nDividing by $n$ and recognizing sample means:\n\n$$\n\\bar{y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 \\bar{x}\n$$\n\nSolving for the intercept:\n\n$$\n\\hat{\\beta}_0 = \\bar{y} - \\hat{\\beta}_1 \\bar{x}\n$$ {#eq-b0-formula}\n\nThis tells us that the regression line always passes through the point $(\\bar{x}, \\bar{y})$---the \"center\" of the data.\n\n### Solving for the Slope\n\nSubstituting @eq-b0-formula into the second first-order condition and working through the algebra (using summation properties from @sec-stats-review):\n\n$$\n\\sum_{i=1}^{n} x_i[y_i - (\\bar{y} - \\hat{\\beta}_1\\bar{x}) - \\hat{\\beta}_1 x_i] = 0\n$$\n\nAfter distributing and rearranging:\n\n$$\n\\sum_{i=1}^{n} x_i(y_i - \\bar{y}) = \\hat{\\beta}_1 \\sum_{i=1}^{n} x_i(x_i - \\bar{x})\n$$\n\nUsing the summation properties $\\sum x_i(y_i - \\bar{y}) = \\sum(x_i - \\bar{x})(y_i - \\bar{y})$ and $\\sum x_i(x_i - \\bar{x}) = \\sum(x_i - \\bar{x})^2$:\n\n$$\n\\sum_{i=1}^{n} (x_i - \\bar{x})(y_i - \\bar{y}) = \\hat{\\beta}_1 \\sum_{i=1}^{n} (x_i - \\bar{x})^2\n$$\n\nSolving for $\\hat{\\beta}_1$:\n\n$$\n\\hat{\\beta}_1 = \\frac{\\sum_{i=1}^{n}(x_i - \\bar{x})(y_i - \\bar{y})}{\\sum_{i=1}^{n}(x_i - \\bar{x})^2}\n$$ {#eq-b1-formula}\n\n### Confirming It's a Minimum\n\nHow do we know this critical point is a minimum rather than a maximum?\nWe check the second-order conditions.\nThe second partial derivative of SSR with respect to $\\hat{\\beta}_1$ is:\n\n$$\n\\frac{\\partial^2 SSR}{\\partial \\hat{\\beta}_1^2} = 2\\sum_{i=1}^{n} x_i^2 > 0\n$$\n\nSince this is positive (as long as there's variation in $x$),\nthe SSR function is convex,\nand our solution is indeed a minimum.\n\n::: {.callout-important}\n## The OLS Slope Formula\nThe OLS slope estimate equals the sample covariance of $x$ and $y$ divided by the sample variance of $x$:\n\n$$\n\\hat{\\beta}_1 = \\frac{Cov(x, y)}{Var(x)} = \\frac{\\sum(x_i - \\bar{x})(y_i - \\bar{y})}{\\sum(x_i - \\bar{x})^2}\n$$\n\nThis can also be written in terms of the correlation coefficient:\n$$\n\\hat{\\beta}_1 = \\rho_{xy} \\frac{\\sigma_y}{\\sigma_x}\n$$\n:::\n\nThis last expression reveals something important:\nbivariate OLS is essentially a scaled version of the correlation between $x$ and $y$.\nAnd as we discussed in @sec-introduction,\ncorrelation does not imply causation!\nWe must be very careful about interpreting bivariate OLS results causally.\n\n\n## Computing OLS in R\n\nWhile we derived the formulas by hand,\nin practice we use software to compute OLS estimates.\nIn R,\nthe `lm()` function (for \"linear model\") performs OLS regression.\n\n### Basic Syntax\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# General syntax\nlm(y ~ x, data = your_data)\n```\n:::\n\n\n\n\n\n\nThe formula `y ~ x` specifies that $y$ is the dependent variable and $x$ is the independent variable.\nAn intercept is included by default.\n\n### Example: MPG and Horsepower\n\nLet's estimate the relationship between fuel efficiency (MPG) and engine horsepower using the built-in `mtcars` dataset:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the data\ndata(mtcars)\n\n# Estimate the regression\nlm_mpg <- lm(mpg ~ hp, data = mtcars)\n\n# View the results\nsummary(lm_mpg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mpg ~ hp, data = mtcars)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.7121 -2.1122 -0.8854  1.5819  8.2360 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 30.09886    1.63392  18.421  < 2e-16 ***\nhp          -0.06823    0.01012  -6.742 1.79e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.863 on 30 degrees of freedom\nMultiple R-squared:  0.6024,\tAdjusted R-squared:  0.5892 \nF-statistic: 45.46 on 1 and 30 DF,  p-value: 1.788e-07\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe output shows our estimates:\n$\\hat{\\beta}_0 = 30.10$ and $\\hat{\\beta}_1 = -0.07$.\nThe slope suggests that each additional unit of horsepower is associated with about 0.07 fewer miles per gallon.\n\n\n## Goodness-of-Fit: R-Squared\n\nHow well does our regression line fit the data?\nThe **R-squared** ($R^2$) provides one measure of goodness-of-fit.\n\nDefine:\n\n- **Total Sum of Squares (SST):** $SST = \\sum_{i=1}^{n}(y_i - \\bar{y})^2$ — total variation in $y$\n- **Explained Sum of Squares (SSE):** $SSE = \\sum_{i=1}^{n}(\\hat{y}_i - \\bar{y})^2$ — variation explained by the regression\n- **Residual Sum of Squares (SSR):** $SSR = \\sum_{i=1}^{n}\\hat{\\mu}_i^2$ — unexplained variation\n\nThe R-squared is:\n\n$$\nR^2 = \\frac{SSE}{SST} = 1 - \\frac{SSR}{SST}\n$$\n\nThis measures the fraction of the total variation in $y$ that is explained by the regression.\n$R^2$ ranges from 0 (no explanatory power) to 1 (perfect fit).\n\n::: {.callout-warning}\n## Interpreting R-Squared\nBe careful interpreting $R^2$,\nespecially in the context of causal inference.\nA high $R^2$ does not mean we have a causal estimate---it just means $x$ is correlated with $y$.\nConversely,\na low $R^2$ does not mean our estimate is wrong or unimportant.\nIn cross-sectional data,\n$R^2$ values of 0.1 to 0.3 are common and can still represent economically meaningful relationships.\n:::\n\n\n## The Gauss-Markov Assumptions\n\nWe've derived the OLS formulas,\nbut how do we know if the estimates are any good?\nThe formulas will always give us *some* numbers,\nbut whether those numbers have useful statistical properties depends on certain conditions being met.\n\nThe **Gauss-Markov assumptions** are a set of conditions under which OLS has desirable properties.\nUnderstanding these assumptions is crucial:\nthey tell us when we can trust our estimates and when we should be skeptical.\n\n### Assumption 1: Linear in Parameters\n\n::: {.callout-note}\n## Gauss-Markov Assumption 1: Linear in Parameters\nThe population model is: $y = \\beta_0 + \\beta_1 x + \\mu$\n:::\n\nThis assumption states that the dependent variable $y$ can be written as a linear function of the parameters $\\beta_0$ and $\\beta_1$,\nplus an error term.\n\n**What this does NOT mean:**\nThis assumption is less restrictive than it might first appear.\nIt does *not* require that $y$ and $x$ have a linear relationship.\nWe can model many non-linear relationships by transforming the variables.\nFor example:\n\n- $y = \\beta_0 + \\beta_1 x^2 + \\mu$ is linear in parameters (we can define $z = x^2$ and estimate $y = \\beta_0 + \\beta_1 z + \\mu$)\n- $\\log(y) = \\beta_0 + \\beta_1 x + \\mu$ is linear in parameters\n- $y = \\beta_0 + \\beta_1 \\log(x) + \\mu$ is linear in parameters\n\n**What would violate this assumption:**\nModels where parameters enter non-linearly,\nsuch as $y = \\beta_0 + x^{\\beta_1} + \\mu$ or $y = \\frac{1}{1 + e^{-\\beta_0 - \\beta_1 x}} + \\mu$ (a logistic function).\nThese require different estimation techniques.\n\n### Assumption 2: Random Sampling\n\n::: {.callout-note}\n## Gauss-Markov Assumption 2: Random Sampling\nWe have a random sample of size $n$ from the population: $\\{(x_i, y_i): i = 1, ..., n\\}$\n:::\n\nThis assumption states that each observation in our dataset is drawn randomly and independently from the population of interest.\nEach unit in the population has an equal chance of being selected,\nand the selection of one unit doesn't affect the probability of selecting another.\n\n**Why it matters:**\nRandom sampling ensures that our sample is representative of the population.\nIf certain types of observations are more likely to be included,\nour estimates may not generalize to the full population.\n\n**When this might be violated:**\n\n- **Self-selection:** If people choose whether to participate in a survey, those who respond may differ systematically from those who don't. For example, a wage survey might oversample high earners if low-wage workers are less likely to respond.\n\n- **Convenience sampling:** Surveying only people who are easy to reach (e.g., college students for a study about the general population).\n\n- **Time series data:** Observations collected over time are often correlated with each other. Today's stock price depends on yesterday's stock price, violating independence.\n\n- **Clustered data:** Students within the same classroom, or workers within the same firm, may be more similar to each other than to randomly selected individuals.\n\n### Assumption 3: Variation in the Independent Variable\n\n::: {.callout-note}\n## Gauss-Markov Assumption 3: Sample Variation in $x$\nThe independent variable has some variation in the sample: $\\sum(x_i - \\bar{x})^2 > 0$\n:::\n\nThis assumption simply requires that $x$ is not constant in our sample.\nIf everyone in our sample has the same value of $x$,\nwe cannot estimate how changes in $x$ relate to changes in $y$.\n\n**Why it matters:**\nLook back at our formula for $\\hat{\\beta}_1$:\n\n$$\n\\hat{\\beta}_1 = \\frac{\\sum(x_i - \\bar{x})(y_i - \\bar{y})}{\\sum(x_i - \\bar{x})^2}\n$$\n\nIf all $x_i$ equal $\\bar{x}$,\nthe denominator is zero,\nand the formula is undefined.\nIntuitively,\nif everyone has 12 years of education,\nwe have no way to estimate what would happen with 13 years of education.\n\n**In practice:**\nThis assumption is almost always satisfied.\nIt would only fail in unusual circumstances,\nlike if you accidentally collected a sample where everyone happened to have the exact same value of $x$.\nHowever,\nhaving *little* variation in $x$ (even if not zero) can lead to imprecise estimates,\nas we'll see when discussing variance.\n\n### Assumption 4: Zero Conditional Mean\n\n::: {.callout-note}\n## Gauss-Markov Assumption 4: Zero Conditional Mean\nThe expected value of the error term is zero for any value of $x$: $E[\\mu | x] = 0$\n:::\n\nThis is the most important and most frequently violated assumption.\nIt states that the average value of all the unobserved factors affecting $y$ is the same regardless of the value of $x$.\n\n**Understanding the assumption:**\nLet's break this down carefully.\nThe error term $\\mu$ contains everything that affects $y$ other than $x$.\nThe zero conditional mean assumption says that if we could collect all people with $x = 10$ and compute the average of their $\\mu$ values,\nit would be zero.\nAnd if we collected all people with $x = 20$ and averaged their $\\mu$ values,\nthat would also be zero.\nThe average of unobservables is the same at every level of $x$.\n\n**Example: Education and Wages**\n\nConsider the regression:\n$$wage = \\beta_0 + \\beta_1 \\cdot educ + \\mu$$\n\nThe error term $\\mu$ includes ability,\nmotivation,\nfamily connections,\nand other unobserved factors.\nThe zero conditional mean assumption requires:\n\n$$E[\\mu | educ = 8] = E[\\mu | educ = 12] = E[\\mu | educ = 16] = 0$$\n\nIs this plausible?\nProbably not.\nPeople with higher ability tend to get more education (because school is easier for them,\nor because they enjoy learning).\nSo among people with 16 years of education,\naverage ability is probably higher than among people with 8 years.\nThis means $E[\\mu | educ = 16] > E[\\mu | educ = 8]$,\nviolating the assumption.\n\n**Why it matters:**\nWhen this assumption fails,\nOLS is **biased**.\nThe estimate $\\hat{\\beta}_1$ will systematically overshoot or undershoot the true $\\beta_1$.\nIn the education example,\nif high-ability people get more education,\nour estimate of the \"return to education\" will partly capture the \"return to ability,\"\nmaking education look more valuable than it really is.\n\nThis is the essence of **omitted variable bias**,\nwhich we'll explore in detail shortly.\n\n### Assumption 5: Homoskedasticity\n\n::: {.callout-note}\n## Gauss-Markov Assumption 5: Homoskedasticity\nThe variance of the error term is constant across all values of $x$: $Var(\\mu | x) = \\sigma^2$\n:::\n\nThis assumption states that the spread of the error term is the same regardless of the value of $x$.\nThe \"noise\" in our data is equally noisy everywhere.\n\n**Understanding the assumption:**\nWhile Assumption 4 concerns the *mean* of $\\mu$ at different values of $x$,\nAssumption 5 concerns the *variance*.\nHomoskedasticity (from Greek: \"same scatter\") means the scatter of points around the regression line is constant.\n**Heteroskedasticity** (different scatter) occurs when the variance of $\\mu$ depends on $x$.\n\n**Example: Income and Spending**\n\nConsider a regression of consumption spending on income.\nFor low-income households,\nspending is relatively constrained---there's not much room for variation because most income goes to necessities.\nFor high-income households,\nthere's much more discretion in spending patterns,\nleading to greater variation.\nThis would create heteroskedasticity:\n$Var(\\mu | income)$ increases with income.\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Left: Homoskedasticity—the spread of points around the line is constant. Right: Heteroskedasticity—the spread increases with x.](unit3_files/figure-html/fig-homohetero-1.png){#fig-homohetero width=90%}\n:::\n:::\n\n\n\n\n\n\n**Why it matters:**\nUnlike Assumption 4,\nviolating homoskedasticity does **not** make OLS biased.\nYour estimate of $\\beta_1$ is still centered on the true value.\nHowever,\nheteroskedasticity affects the *variance* and *standard errors* of the estimator.\nThe usual standard error formulas become incorrect,\nwhich can lead to invalid hypothesis tests and confidence intervals.\n\nWe'll discuss how to handle heteroskedasticity later in the course using **robust standard errors**.\n\n### Summary: Which Assumptions Matter for What?\n\n| Assumption | Needed for Unbiasedness? | Needed for Valid Standard Errors? |\n|------------|-------------------------|----------------------------------|\n| 1. Linear in parameters | Yes | Yes |\n| 2. Random sampling | Yes | Yes |\n| 3. Variation in $x$ | Yes (otherwise undefined) | Yes |\n| 4. Zero conditional mean | **Yes** | Yes |\n| 5. Homoskedasticity | No | **Yes** |\n\nThe key insight:\nAssumptions 1-4 are required for OLS to be **unbiased** (on average, we hit the target).\nAssumption 5 is additionally required for the usual standard error formulas to be valid and for OLS to be **BLUE** (Best Linear Unbiased Estimator).\n\n\n## Unbiasedness of OLS\n\nBefore discussing unbiasedness,\nlet's revisit an important distinction we introduced in @sec-stats-review:\nthe difference between the **population** and the **sample**.\n\n### Population Parameters vs. Sample Estimates\n\nThe **population** represents the entire group we're interested in studying.\nIn our wage-education example,\nthe population might be all workers in the U.S. economy.\nThe population regression model describes the *true* relationship in this population:\n\n$$\ny = \\beta_0 + \\beta_1 x + \\mu\n$$\n\nThe parameters $\\beta_0$ and $\\beta_1$ are **population parameters**---fixed,\nunknown constants that describe how $x$ and $y$ are related for everyone in the population.\nWe never observe these true values directly.\n\nInstead,\nwe collect a **sample**---a subset of observations from the population.\nUsing this sample,\nwe compute **estimates** $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$.\nThese estimates are our best guesses for the unknown population parameters.\n\nHere's the key insight:\n*if we drew a different sample, we would get different estimates*.\nYour classmate analyzing a different random sample of workers would compute different values of $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$ than you would.\nThis randomness in the estimates is called **sampling variability**.\n\n### What Does Unbiasedness Mean?\n\nGiven that estimates vary from sample to sample,\nhow do we know if our estimation procedure is any good?\nOne desirable property is **unbiasedness**.\n\nAn estimator $\\hat{\\theta}$ is **unbiased** if its expected value equals the true population parameter:\n\n$$\nE[\\hat{\\theta}] = \\theta\n$$\n\nUnbiasedness does *not* mean that any particular estimate exactly equals the truth.\nRather,\nit means that if we could:\n\n1. Draw a random sample from the population\n2. Compute $\\hat{\\beta}_1$ from that sample\n3. Repeat steps 1-2 many, many times\n4. Average all the $\\hat{\\beta}_1$ values we computed\n\n...then that average would equal the true $\\beta_1$.\n\nIn other words,\nour estimation procedure doesn't systematically overshoot or undershoot the target.\nIndividual estimates might be too high or too low,\nbut on average,\nwe get it right.\n\n### Proof Sketch\n\nStarting from our formula for $\\hat{\\beta}_1$ and substituting the true model $y_i = \\beta_0 + \\beta_1 x_i + \\mu_i$:\n\n$$\n\\hat{\\beta}_1 = \\beta_1 + \\frac{\\sum_{i=1}^{n}(x_i - \\bar{x})\\mu_i}{\\sum_{i=1}^{n}(x_i - \\bar{x})^2}\n$$\n\nTaking expectations and using the zero conditional mean assumption ($E[\\mu_i | x_i] = 0$):\n\n$$\nE[\\hat{\\beta}_1] = \\beta_1 + \\frac{\\sum_{i=1}^{n}(x_i - \\bar{x}) \\cdot 0}{\\sum_{i=1}^{n}(x_i - \\bar{x})^2} = \\beta_1\n$$\n\nThus,\nOLS is unbiased when the Gauss-Markov assumptions hold.\n\n### Simulation: Unbiasedness in Action\n\n::: {.callout-note collapse=\"true\"}\n## Show Code: Unbiasedness Simulation\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a \"population\" with known parameters\nset.seed(1248)\nn_pop <- 1000\nx_pop <- sample(1:100, size = n_pop, replace = TRUE)\nerr_pop <- rnorm(n_pop)\n\n# True model: y = 3.5 + 2.21*x + error\npop_data <- tibble(\n  x = x_pop,\n  y = 3.5 + 2.21 * x + err_pop\n)\n\n# Draw many samples and estimate beta_1 each time\nset.seed(812476)\nn_simulations <- 500\nsample_size <- 25\n\nsim_results <- map_dfr(1:n_simulations, function(i) {\n  # Draw a random sample\n  sample_data <- slice_sample(pop_data, n = sample_size, replace = TRUE)\n  \n  # Estimate OLS\n  reg <- lm(y ~ x, data = sample_data)\n  \n  tibble(\n    iteration = i,\n    b1_hat = coef(reg)[2]\n  )\n})\n\n# Calculate the average of all estimates\nmean_b1 <- mean(sim_results$b1_hat)\n```\n:::\n\n\n\n\n\n\n:::\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribution of OLS slope estimates across 500 samples. The green line shows the average of all estimates, which equals the true value (2.21), demonstrating unbiasedness.](unit3_files/figure-html/fig-unbiasedness-1.png){#fig-unbiasedness width=80%}\n:::\n:::\n\n\n\n\n\n\nThe simulation in @fig-unbiasedness confirms the theory:\nwhile individual estimates vary around the true value,\nthe average across many samples equals the true parameter.\n\n\n## Omitted Variable Bias\n\nWhat happens when the zero conditional mean assumption fails?\nThe most common culprit is **omitted variable bias**:\nwe've left out a variable that affects both $x$ and $y$.\n\nConsider the true model:\n\n$$\ny = \\beta_0 + \\beta_1 x + \\beta_2 z + \\mu\n$$\n\nIf we omit $z$ and estimate only $y = \\beta_0 + \\beta_1 x + \\nu$ (where $\\nu = \\beta_2 z + \\mu$),\nthen whenever $z$ is correlated with $x$,\nwe have $E[\\nu | x] \\neq 0$,\nand our estimate of $\\beta_1$ is biased.\n\n**Example:** In the education-wage regression,\nif ability ($z$) affects both education choices ($x$) and wages ($y$),\nthen omitting ability creates bias.\nThe estimated \"return to education\" will partly reflect the return to ability.\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![With omitted variable bias, the average of OLS estimates (green) systematically differs from the true value (red). The bias persists even with many samples.](unit3_files/figure-html/fig-ovb-1.png){#fig-ovb width=80%}\n:::\n:::\n\n\n\n\n\n\n\n## Unbiasedness and Causality: Why This All Matters\n\nLet's step back and connect what we've learned to the bigger picture.\nIn @sec-rcts,\nwe discussed how the fundamental challenge of causal inference is selection bias:\npeople who receive \"treatment\" (more education,\na new drug,\na policy intervention) may differ systematically from those who don't.\nThis makes it hard to know whether differences in outcomes are caused by the treatment or by those pre-existing differences.\n\nNow we can see the same problem through the lens of regression.\n**The zero conditional mean assumption is essentially a \"no selection bias\" assumption.**\n\n### When Can We Interpret $\\hat{\\beta}_1$ Causally?\n\nConsider our wage regression:\n$$wage = \\beta_0 + \\beta_1 \\cdot educ + \\mu$$\n\nWhen $E[\\mu | educ] = 0$,\nour OLS estimate $\\hat{\\beta}_1$ is unbiased for $\\beta_1$.\nBut what does $\\beta_1$ actually represent?\n\nIf the zero conditional mean assumption holds,\nthen $\\beta_1$ represents the **causal effect** of education on wages:\nhow much wages would change if we could take a person and give them one more year of education,\nholding everything else constant.\nIn this case,\n$\\hat{\\beta}_1$ is an unbiased estimate of this causal effect.\n\nBut if $E[\\mu | educ] \\neq 0$---say,\nbecause high-ability people get more education---then $\\beta_1$ no longer represents a pure causal effect.\nIt conflates the effect of education with the effect of ability.\nOur estimate $\\hat{\\beta}_1$ is biased,\nand we cannot interpret it as the causal effect of education.\n\n### Correlation vs. Causation, Revisited\n\nRecall that the OLS slope can be written as:\n$$\\hat{\\beta}_1 = \\rho_{xy} \\frac{\\sigma_y}{\\sigma_x}$$\n\nBivariate OLS is fundamentally measuring the *correlation* between $x$ and $y$,\nscaled by their relative standard deviations.\nCorrelation becomes causation **only when the Gauss-Markov assumptions hold**---especially the zero conditional mean assumption.\n\nThis is why we emphasize these assumptions so heavily.\nWithout them:\n\n- OLS still gives you numbers\n- Those numbers still describe the correlation in your data\n- But you **cannot** interpret those numbers as causal effects\n\n::: {.callout-warning}\n## The Key Insight\nOLS always estimates *something*.\nWhether that something is a causal effect or merely a correlation depends entirely on whether the assumptions are satisfied.\nMost of econometrics is about finding clever ways to make the zero conditional mean assumption more plausible.\n:::\n\n\n## Variance of the OLS Estimator\n\nEven when OLS is unbiased,\nour estimates vary from sample to sample.\nThe **variance** of $\\hat{\\beta}_1$ tells us how much variation to expect.\n\nUnder the Gauss-Markov assumptions:\n\n$$\nVar(\\hat{\\beta}_1) = \\frac{\\sigma^2}{SST_x}\n$$\n\nwhere $\\sigma^2 = Var(\\mu)$ is the error variance and $SST_x = \\sum(x_i - \\bar{x})^2$ is the total variation in $x$.\n\nThis formula reveals two key insights:\n\n1. **More noise ($\\sigma^2$) means more variance:** If there's a lot of unexplained variation in $y$, our estimates are less precise.\n\n2. **More variation in $x$ means less variance:** Spreading out our observations of $x$ gives us more information and more precise estimates. This also implies that larger samples (which have more total variation) yield more precise estimates.\n\n\n## Standard Errors\n\nThe **standard error** of $\\hat{\\beta}_1$ is the square root of the variance:\n\n$$\nse(\\hat{\\beta}_1) = \\frac{\\hat{\\sigma}}{\\sqrt{SST_x}}\n$$\n\nwhere $\\hat{\\sigma} = \\sqrt{\\frac{SSR}{n-2}}$ is the estimated standard deviation of the errors.\n\nStandard errors quantify the precision of our estimates and are essential for hypothesis testing and confidence intervals (which we'll cover in the next chapter).\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# R reports standard errors automatically\nsummary(lm_mpg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mpg ~ hp, data = mtcars)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.7121 -2.1122 -0.8854  1.5819  8.2360 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 30.09886    1.63392  18.421  < 2e-16 ***\nhp          -0.06823    0.01012  -6.742 1.79e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.863 on 30 degrees of freedom\nMultiple R-squared:  0.6024,\tAdjusted R-squared:  0.5892 \nF-statistic: 45.46 on 1 and 30 DF,  p-value: 1.788e-07\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe standard error of $\\hat{\\beta}_1$ is 0.01, shown in the `Std. Error` column.\n\n\n## OLS is BLUE\n\nUnder all five Gauss-Markov assumptions,\nOLS is **BLUE**:\n\n- **B**est: Lowest variance among all linear unbiased estimators\n- **L**inear: The estimator is a linear function of the $y_i$'s\n- **U**nbiased: $E[\\hat{\\beta}] = \\beta$\n- **E**stimator: It's a rule for using sample data to estimate population parameters\n\nThis is a powerful result:\namong all estimators that are linear and unbiased,\nOLS has the smallest variance.\nYou cannot do better without either using non-linear methods or accepting some bias.\n\n\n## Summary and Conclusion\n\nThis chapter introduced Ordinary Least Squares regression,\nthe foundational tool of econometrics.\nWe started with the goal of modeling how the conditional expectation $E[Y|X]$ varies with $x$,\nand showed how the linear regression model $y = \\beta_0 + \\beta_1 x + \\mu$ provides a framework for this.\n\nWe derived the OLS estimator by minimizing the sum of squared residuals,\nlearned to compute regressions in R,\nand explored the properties of the OLS regression line.\nWe then turned to the statistical properties of OLS,\nintroducing the Gauss-Markov assumptions and proving that OLS is unbiased when these assumptions hold.\nWhen the zero conditional mean assumption fails---typically due to omitted variables---our estimates become biased.\n\nCrucially,\nwe connected unbiasedness to causality:\nthe zero conditional mean assumption is what allows us to interpret OLS coefficients as causal effects rather than mere correlations.\nWithout this assumption,\nOLS still produces numbers,\nbut those numbers cannot be given a causal interpretation.\n\nFinally,\nwe discussed the variance of OLS estimates and the conditions under which OLS is the best linear unbiased estimator.\n\n### Key Takeaways\n\n- **The goal** is to estimate the conditional expectation $E[Y|X] = \\beta_0 + \\beta_1 x$\n\n- **The OLS slope** equals the covariance of $x$ and $y$ divided by the variance of $x$:\n$$\\hat{\\beta}_1 = \\frac{Cov(x,y)}{Var(x)}$$\n\n- **Bivariate OLS is essentially correlation**—be very careful about causal interpretation\n\n- **The Gauss-Markov assumptions** (especially zero conditional mean) are required for unbiasedness\n\n- **Omitted variable bias** arises when we exclude a variable correlated with both $x$ and $y$\n\n- **Causality requires unbiasedness**—only when $E[\\mu|x] = 0$ can we interpret $\\hat{\\beta}_1$ as a causal effect\n\n- **OLS is BLUE** under the Gauss-Markov assumptions—best among linear unbiased estimators\n\n\n## Check Your Understanding\n\n:::: {.content-visible when-format=\"html\"}\n\n\n\n\n\n\n```{=html}\n<div class=\"question\">\n<div class=\"answer-row\">\n    <label>i. In the model \\(y = \\beta_0 + \\beta_1 x + \\mu\\), what does \\(\\beta_1\\) represent? </label>\n    <select onchange=\"checkAnswer(this, 'b')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">The predicted value of y when x = 0</option>\n        <option value=\"b\">The change in y for a one-unit increase in x</option>\n        <option value=\"c\">The correlation between x and y</option>\n        <option value=\"d\">The variance of the error term</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>ii. The zero conditional mean assumption states that: </label>\n    <select onchange=\"checkAnswer(this, 'c')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">The mean of y is zero</option>\n        <option value=\"b\">The mean of x is zero</option>\n        <option value=\"c\">\\(E[\\mu|x] = 0\\)</option>\n        <option value=\"d\">\\(Var(\\mu|x) = \\sigma^2\\)</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>iii. The OLS slope coefficient can be written as: </label>\n    <select onchange=\"checkAnswer(this, 'a')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">\\(Cov(x,y) / Var(x)\\)</option>\n        <option value=\"b\">\\(Cov(x,y) / Var(y)\\)</option>\n        <option value=\"c\">\\(Var(x) / Cov(x,y)\\)</option>\n        <option value=\"d\">\\(Corr(x,y) \\times Var(x)\\)</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>iv. An unbiased estimator is one where: </label>\n    <select onchange=\"checkAnswer(this, 'b')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Every estimate exactly equals the true parameter</option>\n        <option value=\"b\">The expected value of the estimator equals the true parameter</option>\n        <option value=\"c\">The variance of the estimator is zero</option>\n        <option value=\"d\">The estimator has the smallest possible variance</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>v. Omitted variable bias occurs when: </label>\n    <select onchange=\"checkAnswer(this, 'c')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">We include too many variables in the regression</option>\n        <option value=\"b\">The sample size is too small</option>\n        <option value=\"c\">We exclude a variable correlated with both x and y</option>\n        <option value=\"d\">The error term is heteroskedastic</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>vi. Which Gauss-Markov assumption is required for unbiasedness but NOT for calculating the OLS formulas? </label>\n    <select onchange=\"checkAnswer(this, 'b')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Linear in parameters</option>\n        <option value=\"b\">Zero conditional mean</option>\n        <option value=\"c\">Variation in x</option>\n        <option value=\"d\">Homoskedasticity</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>vii. <strong>(Challenge)</strong> If \\(Var(\\hat{\\beta}_1) = \\sigma^2 / SST_x\\), what happens to the variance of our estimate as sample size increases? </label>\n    <select onchange=\"checkAnswer(this, 'a')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">It decreases, because \\(SST_x\\) increases with sample size</option>\n        <option value=\"b\">It increases, because we have more observations</option>\n        <option value=\"c\">It stays the same</option>\n        <option value=\"d\">It depends on the value of \\(\\sigma^2\\)</option>\n    </select>\n</div>\n</div>\n```\n\n\n\n\n\n\n::: {.callout-tip collapse=\"true\"}\n## Show Explanation\n\ni. The slope coefficient $\\beta_1$ is the marginal effect—it tells us how much $y$ changes when $x$ increases by one unit. The intercept $\\beta_0$ gives the predicted value when $x = 0$.\n\nii. The zero conditional mean assumption $E[\\mu|x] = 0$ states that the expected value of the error term is zero for any given value of $x$. This is crucial for unbiasedness.\n\niii. The OLS slope equals the sample covariance of $x$ and $y$ divided by the sample variance of $x$. This follows directly from the derivation.\n\niv. Unbiasedness means that if we could repeat the sampling process many times, the *average* of our estimates would equal the true parameter. Individual estimates can still miss the target.\n\nv. Omitted variable bias occurs when we leave out a variable that belongs in the model and is correlated with our included independent variable. This causes $E[\\mu|x] \\neq 0$.\n\nvi. The zero conditional mean assumption ($E[\\mu|x] = 0$) is needed to prove OLS is unbiased, but it is not needed to derive the OLS formulas themselves. The calculus minimization approach works regardless of this assumption—it just tells us which values minimize squared residuals.\n\nvii. As sample size increases, we get more variation in $x$, so $SST = \\sum(x_i - \\bar{x})^2$ increases. Since this appears in the denominator, the variance of our estimate decreases. Larger samples give more precise estimates.\n\n:::\n\n::::\n\n### Practice: Interpreting Regression Output\n\nThe following questions present regression results for you to interpret.\n\n\n\n\n\n\n```{=html}\n<div class=\"context\" style=\"margin-bottom: 20px;\">\n<strong>Regression 1:</strong> A researcher estimates the relationship between test scores and class size using data from California elementary schools:\n<pre style=\"background-color: #f5f5f5; padding: 10px; margin-top: 10px; font-family: monospace;\">\nDependent variable: testscr (average test score, points)\n\n             Estimate  Std. Error\n(Intercept)   698.93      10.36\nstr            -2.28       0.52\n\nn = 420, R-squared = 0.051\n</pre>\n<em>Note: str = student-teacher ratio (students per teacher)</em>\n</div>\n\n<div class=\"question\">\n<div class=\"answer-row\">\n    <label>viii. According to this regression, a class with 5 more students per teacher is predicted to score: </label>\n    <select onchange=\"checkAnswer(this, 'b')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">2.28 points higher</option>\n        <option value=\"b\">11.4 points lower</option>\n        <option value=\"c\">2.28 points lower</option>\n        <option value=\"d\">11.4 points higher</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>ix. A school with a student-teacher ratio of 20 would have a predicted test score of: </label>\n    <select onchange=\"checkAnswer(this, 'c')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">698.93</option>\n        <option value=\"b\">744.53</option>\n        <option value=\"c\">653.33</option>\n        <option value=\"d\">656.13</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>x. The R-squared of 0.051 means: </label>\n    <select onchange=\"checkAnswer(this, 'b')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">The regression is invalid</option>\n        <option value=\"b\">About 5% of the variation in test scores is explained by class size</option>\n        <option value=\"c\">Class size has no effect on test scores</option>\n        <option value=\"d\">The coefficient is statistically insignificant</option>\n    </select>\n</div>\n</div>\n\n<div class=\"context\" style=\"margin-top: 30px; margin-bottom: 20px;\">\n<strong>Regression 2:</strong> An economist studies the relationship between cigarette consumption and prices across U.S. states:\n<pre style=\"background-color: #f5f5f5; padding: 10px; margin-top: 10px; font-family: monospace;\">\nDependent variable: packs (cigarette packs sold per capita)\n\n             Estimate  Std. Error\n(Intercept)   219.58      29.19\nrprice        -1.04       0.29\n\nn = 48, R-squared = 0.21\n</pre>\n<em>Note: rprice = real price per pack (cents)</em>\n</div>\n\n<div class=\"question\">\n<div class=\"answer-row\">\n    <label>xi. According to this regression, if the price increases by 10 cents per pack: </label>\n    <select onchange=\"checkAnswer(this, 'c')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Consumption increases by 1.04 packs per capita</option>\n        <option value=\"b\">Consumption decreases by 1.04 packs per capita</option>\n        <option value=\"c\">Consumption decreases by 10.4 packs per capita</option>\n        <option value=\"d\">Consumption increases by 10.4 packs per capita</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>xii. The negative coefficient on price is consistent with: </label>\n    <select onchange=\"checkAnswer(this, 'a')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">The law of demand: higher prices lead to lower quantity demanded</option>\n        <option value=\"b\">A violation of the zero conditional mean assumption</option>\n        <option value=\"c\">Heteroskedasticity in the error term</option>\n        <option value=\"d\">An R-squared that is too low</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>xiii. <strong>(Challenge)</strong> Why might we be cautious about interpreting this coefficient as the causal effect of price on consumption? </label>\n    <select onchange=\"checkAnswer(this, 'd')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">The R-squared is too low</option>\n        <option value=\"b\">The sample size is too small</option>\n        <option value=\"c\">The coefficient is negative</option>\n        <option value=\"d\">Omitted variables (like anti-smoking policies or income) may affect both price and consumption</option>\n    </select>\n</div>\n</div>\n```\n\n\n\n\n\n\n::: {.callout-tip collapse=\"true\"}\n## Show Explanation\n\ni. The slope coefficient $\\beta_1$ is the marginal effect—it tells us how much $y$ changes when $x$ increases by one unit. The intercept $\\beta_0$ gives the predicted value when $x = 0$.\n\nii. The zero conditional mean assumption $E[\\mu|x] = 0$ states that the expected value of the error term is zero for any given value of $x$. This is crucial for unbiasedness.\n\niii. The OLS slope equals the sample covariance of $x$ and $y$ divided by the sample variance of $x$. This follows directly from the derivation.\n\niv. Unbiasedness means that if we could repeat the sampling process many times, the *average* of our estimates would equal the true parameter. Individual estimates can still miss the target.\n\nv. Omitted variable bias occurs when we leave out a variable that belongs in the model and is correlated with our included independent variable. This causes $E[\\mu|x] \\neq 0$.\n\nvi. The zero conditional mean assumption ($E[\\mu|x] = 0$) is needed to prove OLS is unbiased, but it is not needed to derive the OLS formulas themselves. The calculus minimization approach works regardless of this assumption—it just tells us which values minimize squared residuals.\n\nvii. As sample size increases, we get more variation in $x$, so $SST = \\sum(x_i - \\bar{x})^2$ increases. Since this appears in the denominator, the variance of our estimate decreases. Larger samples give more precise estimates.\n\n**Regression Interpretation Questions:**\n\nviii. The coefficient on `str` is $-2.28$, meaning each additional student per teacher is associated with 2.28 fewer points. For 5 additional students: $5 \\times (-2.28) = -11.4$ points.\n\nix. Using the regression equation: $\\hat{y} = 698.93 + (-2.28)(20) = 698.93 - 45.6 = 653.33$\n\nx. R-squared measures the fraction of variance in $y$ explained by the regression. Here, 5.1% of test score variation is explained by class size. A low R-squared doesn't make the coefficient meaningless—it just means other factors also matter.\n\nxi. The coefficient is $-1.04$, so a 10-cent increase predicts: $10 \\times (-1.04) = -10.4$ packs per capita.\n\nxii. The negative relationship between price and quantity is exactly what economic theory predicts—the law of demand.\n\nxiii. States with strong anti-smoking policies might have both higher cigarette taxes (raising prices) AND other policies that reduce smoking. This would create omitted variable bias, making price appear more effective than it actually is at reducing consumption.\n\n:::\n\n::::\n\n:::: {.content-hidden when-format=\"html\"}\n\n*Note: This section contains interactive content only available in the HTML version.*\n\n::::\n",
    "supporting": [
      "unit3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}