<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>13&nbsp; Advanced Difference-in-Differences – EC325 Lecture Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/instrumental_variables.html" rel="next">
<link href="../chapters/did.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/advanced_did.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Advanced Difference-in-Differences</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">EC325 Lecture Notes</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../EC325-Lecture-Notes.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../EC325-Lecture-Notes.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/data_practices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Good Data Practices</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/rcts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Causality and Randomized Control Trials</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bivariate_ols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bivariate Regression and Ordinary Least Squares</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/multivariate_ols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Multivariate Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/statistical_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/dummies_nonlins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dummy Variables and Non-Linear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/interaction_effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Interaction Effects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/heteroskedasticity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Heteroskedasticity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/binary_outcomes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Binary Outcomes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/panel_fe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Panel Data and Fixed Effects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/did.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Difference-in-Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/advanced_did.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Advanced Difference-in-Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/instrumental_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Instrumental Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/installingR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Intro to R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/statsreview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Statistics and Probability Review</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/working_with_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Importing and Working with Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/r_reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">R Functions and Packages Reference</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#choosing-good-controls" id="toc-choosing-good-controls" class="nav-link active" data-scroll-target="#choosing-good-controls"><span class="header-section-number">13.1</span> Choosing Good Controls</a>
  <ul class="collapse">
  <li><a href="#why-control-selection-matters" id="toc-why-control-selection-matters" class="nav-link" data-scroll-target="#why-control-selection-matters"><span class="header-section-number">13.1.1</span> Why Control Selection Matters</a></li>
  <li><a href="#method-1-intuitive-selection-based-on-institutional-knowledge" id="toc-method-1-intuitive-selection-based-on-institutional-knowledge" class="nav-link" data-scroll-target="#method-1-intuitive-selection-based-on-institutional-knowledge"><span class="header-section-number">13.1.2</span> Method 1: Intuitive Selection Based on Institutional Knowledge</a></li>
  <li><a href="#method-2-data-driven-control-selection" id="toc-method-2-data-driven-control-selection" class="nav-link" data-scroll-target="#method-2-data-driven-control-selection"><span class="header-section-number">13.1.3</span> Method 2: Data-Driven Control Selection</a></li>
  </ul></li>
  <li><a href="#ipw-did-propensity-score-weighting" id="toc-ipw-did-propensity-score-weighting" class="nav-link" data-scroll-target="#ipw-did-propensity-score-weighting"><span class="header-section-number">13.2</span> IPW-DiD: Propensity Score Weighting</a>
  <ul class="collapse">
  <li><a href="#setting-up-the-problem" id="toc-setting-up-the-problem" class="nav-link" data-scroll-target="#setting-up-the-problem"><span class="header-section-number">13.2.1</span> Setting Up the Problem</a></li>
  <li><a href="#the-intuition-behind-propensity-score-weighting" id="toc-the-intuition-behind-propensity-score-weighting" class="nav-link" data-scroll-target="#the-intuition-behind-propensity-score-weighting"><span class="header-section-number">13.2.2</span> The Intuition Behind Propensity Score Weighting</a></li>
  <li><a href="#step-1-estimate-propensity-scores" id="toc-step-1-estimate-propensity-scores" class="nav-link" data-scroll-target="#step-1-estimate-propensity-scores"><span class="header-section-number">13.2.3</span> Step 1: Estimate Propensity Scores</a></li>
  <li><a href="#step-2-calculate-inverse-propensity-weights" id="toc-step-2-calculate-inverse-propensity-weights" class="nav-link" data-scroll-target="#step-2-calculate-inverse-propensity-weights"><span class="header-section-number">13.2.4</span> Step 2: Calculate Inverse Propensity Weights</a></li>
  <li><a href="#visualizing-the-weighting" id="toc-visualizing-the-weighting" class="nav-link" data-scroll-target="#visualizing-the-weighting"><span class="header-section-number">13.2.5</span> Visualizing the Weighting</a></li>
  <li><a href="#step-3-run-the-weighted-twfe-regression" id="toc-step-3-run-the-weighted-twfe-regression" class="nav-link" data-scroll-target="#step-3-run-the-weighted-twfe-regression"><span class="header-section-number">13.2.6</span> Step 3: Run the Weighted TWFE Regression</a></li>
  <li><a href="#comparing-results" id="toc-comparing-results" class="nav-link" data-scroll-target="#comparing-results"><span class="header-section-number">13.2.7</span> Comparing Results</a></li>
  <li><a href="#summary-of-the-ipw-did-algorithm" id="toc-summary-of-the-ipw-did-algorithm" class="nav-link" data-scroll-target="#summary-of-the-ipw-did-algorithm"><span class="header-section-number">13.2.8</span> Summary of the IPW-DiD Algorithm</a></li>
  </ul></li>
  <li><a href="#dynamic-did-and-event-studies" id="toc-dynamic-did-and-event-studies" class="nav-link" data-scroll-target="#dynamic-did-and-event-studies"><span class="header-section-number">13.3</span> Dynamic DiD and Event Studies</a>
  <ul class="collapse">
  <li><a href="#why-treatment-effects-may-change-over-time" id="toc-why-treatment-effects-may-change-over-time" class="nav-link" data-scroll-target="#why-treatment-effects-may-change-over-time"><span class="header-section-number">13.3.1</span> Why Treatment Effects May Change Over Time</a></li>
  <li><a href="#relative-time" id="toc-relative-time" class="nav-link" data-scroll-target="#relative-time"><span class="header-section-number">13.3.2</span> Relative Time</a></li>
  <li><a href="#the-dynamic-did-model" id="toc-the-dynamic-did-model" class="nav-link" data-scroll-target="#the-dynamic-did-model"><span class="header-section-number">13.3.3</span> The Dynamic DiD Model</a></li>
  <li><a href="#constructing-the-data-for-dynamic-did" id="toc-constructing-the-data-for-dynamic-did" class="nav-link" data-scroll-target="#constructing-the-data-for-dynamic-did"><span class="header-section-number">13.3.4</span> Constructing the Data for Dynamic DiD</a></li>
  <li><a href="#example-environmental-policy-and-manufacturing-employment" id="toc-example-environmental-policy-and-manufacturing-employment" class="nav-link" data-scroll-target="#example-environmental-policy-and-manufacturing-employment"><span class="header-section-number">13.3.5</span> Example: Environmental Policy and Manufacturing Employment</a></li>
  <li><a href="#estimating-the-dynamic-model" id="toc-estimating-the-dynamic-model" class="nav-link" data-scroll-target="#estimating-the-dynamic-model"><span class="header-section-number">13.3.6</span> Estimating the Dynamic Model</a></li>
  <li><a href="#the-event-study-plot" id="toc-the-event-study-plot" class="nav-link" data-scroll-target="#the-event-study-plot"><span class="header-section-number">13.3.7</span> The Event Study Plot</a></li>
  <li><a href="#interpreting-the-event-study" id="toc-interpreting-the-event-study" class="nav-link" data-scroll-target="#interpreting-the-event-study"><span class="header-section-number">13.3.8</span> Interpreting the Event Study</a></li>
  <li><a href="#a-note-on-staggered-adoption" id="toc-a-note-on-staggered-adoption" class="nav-link" data-scroll-target="#a-note-on-staggered-adoption"><span class="header-section-number">13.3.9</span> A Note on Staggered Adoption</a></li>
  </ul></li>
  <li><a href="#cluster-robust-standard-errors" id="toc-cluster-robust-standard-errors" class="nav-link" data-scroll-target="#cluster-robust-standard-errors"><span class="header-section-number">13.4</span> Cluster-Robust Standard Errors</a>
  <ul class="collapse">
  <li><a href="#the-problem-non-independent-observations" id="toc-the-problem-non-independent-observations" class="nav-link" data-scroll-target="#the-problem-non-independent-observations"><span class="header-section-number">13.4.1</span> The Problem: Non-Independent Observations</a></li>
  <li><a href="#an-intuitive-example" id="toc-an-intuitive-example" class="nav-link" data-scroll-target="#an-intuitive-example"><span class="header-section-number">13.4.2</span> An Intuitive Example</a></li>
  <li><a href="#what-is-a-cluster" id="toc-what-is-a-cluster" class="nav-link" data-scroll-target="#what-is-a-cluster"><span class="header-section-number">13.4.3</span> What Is a “Cluster”?</a></li>
  <li><a href="#visualizing-clustered-data" id="toc-visualizing-clustered-data" class="nav-link" data-scroll-target="#visualizing-clustered-data"><span class="header-section-number">13.4.4</span> Visualizing Clustered Data</a></li>
  <li><a href="#the-statistical-violation" id="toc-the-statistical-violation" class="nav-link" data-scroll-target="#the-statistical-violation"><span class="header-section-number">13.4.5</span> The Statistical Violation</a></li>
  <li><a href="#simulation-type-i-error-rates-with-and-without-clustering" id="toc-simulation-type-i-error-rates-with-and-without-clustering" class="nav-link" data-scroll-target="#simulation-type-i-error-rates-with-and-without-clustering"><span class="header-section-number">13.4.6</span> Simulation: Type I Error Rates With and Without Clustering</a></li>
  <li><a href="#how-cluster-robust-standard-errors-work" id="toc-how-cluster-robust-standard-errors-work" class="nav-link" data-scroll-target="#how-cluster-robust-standard-errors-work"><span class="header-section-number">13.4.7</span> How Cluster-Robust Standard Errors Work</a></li>
  <li><a href="#implementing-cluster-robust-standard-errors-in-r" id="toc-implementing-cluster-robust-standard-errors-in-r" class="nav-link" data-scroll-target="#implementing-cluster-robust-standard-errors-in-r"><span class="header-section-number">13.4.8</span> Implementing Cluster-Robust Standard Errors in R</a></li>
  <li><a href="#choosing-the-right-cluster-level" id="toc-choosing-the-right-cluster-level" class="nav-link" data-scroll-target="#choosing-the-right-cluster-level"><span class="header-section-number">13.4.9</span> Choosing the Right Cluster Level</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">13.5</span> Summary</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding"><span class="header-section-number">13.6</span> Check Your Understanding</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-advanced-did" class="quarto-section-identifier"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Advanced Difference-in-Differences</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>



<style>
.problem {
    background-color: #f8f9fa;
    border: 1px solid #dee2e6;
    border-radius: 8px;
    padding: 20px;
    margin: 20px 0;
}
.context {
    background-color: #e8f4f8;
    padding: 12px;
    border-radius: 5px;
    margin-bottom: 15px;
    border-left: 4px solid #2874a6;
}
.question {
    margin: 15px 0;
    padding: 10px;
    background-color: #fff3cd;
    border-radius: 5px;
}
.answer-row {
    display: flex;
    align-items: center;
    margin: 10px 0;
    flex-wrap: wrap;
    gap: 10px;
}
.answer-row label {
    min-width: 320px;
    font-weight: 500;
}
select {
    padding: 8px 12px;
    font-size: 14px;
    border: 2px solid #ccc;
    border-radius: 5px;
    min-width: 300px;
    cursor: pointer;
}
select:focus {
    border-color: #2874a6;
    outline: none;
}
.correct {
    border-color: #28a745 !important;
    background-color: #d4edda !important;
}
.incorrect {
    border-color: #dc3545 !important;
    background-color: #f8d7da !important;
}
.explanation {
    margin-top: 10px;
    padding: 15px;
    background-color: #e7f3ff;
    border-radius: 5px;
    border-left: 4px solid #2874a6;
}
.note {
    font-size: 0.85em;
    color: #666;
    font-style: italic;
}
</style>

<script>
function checkAnswer(selectElement, correctValue) {
    if (selectElement.value === '') {
        selectElement.classList.remove('correct', 'incorrect');
    } else if (selectElement.value === correctValue) {
        selectElement.classList.remove('incorrect');
        selectElement.classList.add('correct');
    } else {
        selectElement.classList.remove('correct');
        selectElement.classList.add('incorrect');
    }
}
</script>

<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span><strong>Key Questions</strong>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>How can we use data to select better control units for DiD?</li>
<li>What are propensity scores and how do they improve DiD estimates?</li>
<li>How do we estimate treatment effects that change over time?</li>
<li>What is an event study and how do we interpret it?</li>
<li>Why do we need cluster-robust standard errors in panel data?</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span><strong>Suggested Readings</strong>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Cunningham, <em>Causal Inference: The Mixtape</em>, Chapter 9 (Difference-in-Differences)</li>
<li>Angrist and Pischke, <em>Mostly Harmless Econometrics</em>, Chapter 5</li>
<li>Abadie, Alberto (2005). “Semiparametric Difference-in-Differences Estimators.” <em>Review of Economic Studies</em> 72(1): 1-19.</li>
<li>Callaway, Brantly and Pedro H.C. Sant’Anna (2021). “Difference-in-Differences with Multiple Time Periods.” <em>Journal of Econometrics</em> 225(2): 200-230.</li>
</ul>
</div>
</div>
</div>
<p>The basic difference-in-differences framework from <a href="did.html" class="quarto-xref"><span>Chapter 12</span></a> gets us a long way, but real-world applications often demand more sophisticated tools. In that chapter, we assumed that our treated and control groups were already on parallel paths before the policy—an assumption that rarely holds without effort on the part of the researcher. We also estimated a single, constant treatment effect across all post-treatment periods, when in practice, the impact of a policy often grows, shrinks, or shifts as time passes.</p>
<p>This chapter tackles three important extensions to the basic DiD framework. First, we discuss how researchers <strong>choose good control groups</strong>, both through institutional knowledge and through data-driven methods like propensity score weighting. Second, we introduce <strong>dynamic DiD and event studies</strong>, which let treatment effects vary over time and provide a visual test for pre-trends. Finally, we cover <strong>cluster-robust standard errors</strong>, which fix a common inferential problem in panel data that can badly inflate Type I error rates.</p>
<section id="choosing-good-controls" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="choosing-good-controls"><span class="header-section-number">13.1</span> Choosing Good Controls</h2>
<section id="why-control-selection-matters" class="level3" data-number="13.1.1">
<h3 data-number="13.1.1" class="anchored" data-anchor-id="why-control-selection-matters"><span class="header-section-number">13.1.1</span> Why Control Selection Matters</h3>
<p>As we discussed in the previous chapter, a DiD estimate is only as credible as the counterfactual it relies on. The whole enterprise rests on the parallel trends assumption: in the absence of treatment, the treated units would have followed the same trajectory as the control units. If the control group is on a fundamentally different path, your DiD estimate picks up those diverging trends and attributes them—incorrectly—to the policy.</p>
<p>The chain of logic is simple:</p>
<ul>
<li><strong>Good controls</strong> <span class="math inline">\(\rightarrow\)</span> <strong>Good counterfactual</strong> <span class="math inline">\(\rightarrow\)</span> <strong>Credible DiD estimate</strong></li>
<li><strong>Bad controls</strong> <span class="math inline">\(\rightarrow\)</span> <strong>Bad counterfactual</strong> <span class="math inline">\(\rightarrow\)</span> <strong>Biased DiD estimate</strong></li>
</ul>
<p>So how do researchers go about choosing good controls? There are broadly two approaches: selecting controls based on institutional knowledge, and selecting controls using statistical methods.</p>
</section>
<section id="method-1-intuitive-selection-based-on-institutional-knowledge" class="level3" data-number="13.1.2">
<h3 data-number="13.1.2" class="anchored" data-anchor-id="method-1-intuitive-selection-based-on-institutional-knowledge"><span class="header-section-number">13.1.2</span> Method 1: Intuitive Selection Based on Institutional Knowledge</h3>
<p>The most traditional approach is to choose controls based on what you know about the institutional setting. The researcher identifies comparison units that, for reasons grounded in the context of the problem, should have been on similar trajectories to the treated units.</p>
<p>A classic example is the <strong>border discontinuity design</strong>. Imagine two counties that sit right next to each other, straddling a state border. The people who live in these counties shop at the same stores, watch the same local news, face the same weather patterns, and work in the same labor markets. They are, for most purposes, very similar—except that they are governed by different state legislatures. When one state changes a policy and the other does not, the untreated county just across the border is a natural control.</p>
<p>Card and Krueger (1994) used exactly this logic to study New Jersey’s 1992 minimum wage increase. They compared fast-food employment in New Jersey counties to employment in adjacent Pennsylvania counties. The idea is that restaurants on either side of the border faced the same local economic conditions, so any divergence in employment after the minimum wage hike could be attributed to the policy itself.</p>
<p>Dube, Lester, and Reich (2010) extended this idea to <em>all</em> contiguous county pairs along state borders where the two states had different minimum wages. Rather than relying on a single natural experiment, they exploited hundreds of such pairs simultaneously, greatly increasing statistical power while maintaining the logic that neighboring counties are good controls for one another.</p>
<p>This approach works well when the institutional setting provides a clear reason why certain untreated units should track treated units. But it requires detailed knowledge of the specific context, and it is not always possible to find such “natural” comparison groups.</p>
</section>
<section id="method-2-data-driven-control-selection" class="level3" data-number="13.1.3">
<h3 data-number="13.1.3" class="anchored" data-anchor-id="method-2-data-driven-control-selection"><span class="header-section-number">13.1.3</span> Method 2: Data-Driven Control Selection</h3>
<p>An alternative is to let the data guide the choice of controls. The idea is to use an algorithm to find untreated units that are similar to treated units based on observable characteristics. The hope is that if units share observable traits, they are also similar on the unobservable factors that drive trends in the outcome.</p>
<p>There are many data-driven methods for selecting controls: synthetic controls (which construct a weighted combination of untreated units to match the treated unit’s pre-treatment trajectory), nearest-neighbor matching (which pairs each treated unit with the most similar untreated unit), and propensity score methods (which reweight the control group based on predicted probability of treatment). All share the same goal—building a better counterfactual using data—but they differ in how they define “similar.”</p>
<p>We will focus on one method that combines naturally with the TWFE framework: <strong>Inverse Propensity Score Weighted DiD (IPW-DiD)</strong>.</p>
</section>
</section>
<section id="ipw-did-propensity-score-weighting" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="ipw-did-propensity-score-weighting"><span class="header-section-number">13.2</span> IPW-DiD: Propensity Score Weighting</h2>
<section id="setting-up-the-problem" class="level3" data-number="13.2.1">
<h3 data-number="13.2.1" class="anchored" data-anchor-id="setting-up-the-problem"><span class="header-section-number">13.2.1</span> Setting Up the Problem</h3>
<p>Consider estimating the effect of the Affordable Care Act (ACA) Medicaid expansion on health insurance coverage rates. In 2014, a number of states expanded Medicaid eligibility under the ACA, while others did not. A natural DiD approach would compare uninsured rates in expansion states (treated) to non-expansion states (control), before and after 2014.</p>
<p>The TWFE DiD model would be:</p>
<p><span class="math display">\[
y_{it} = \beta_0 + \beta_1 D_{it} + \alpha_i + \tau_t + \mu_{it}
\]</span></p>
<p>where <span class="math inline">\(y_{it}\)</span> is the uninsured rate in state <span class="math inline">\(i\)</span> in year <span class="math inline">\(t\)</span>, <span class="math inline">\(D_{it}\)</span> is a treatment indicator equal to 1 in expansion states after 2014, <span class="math inline">\(\alpha_i\)</span> are state fixed effects, <span class="math inline">\(\tau_t\)</span> are year fixed effects, and <span class="math inline">\(\mu_{it}\)</span> is the error term.</p>
<p>The problem is that states which expanded Medicaid are <em>very different</em> from states that did not. Expansion states tend to be more politically liberal, have different demographic profiles, different industry compositions, and different baseline health care systems. These are not random differences—they are systematically related to the decision to expand. And if these same characteristics also affect trends in uninsured rates, then parallel trends will fail.</p>
<p>The figure below plots average uninsured rates over time for expansion states and all non-expansion states, using our simulated data.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-naive-trends" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-naive-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.1: Without adjustment, treated and control states show diverging pre-trends. The control states are declining more slowly than the treated states even before the policy begins, which violates parallel trends.
</figcaption>
<div aria-describedby="fig-naive-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="advanced_did_files/figure-html/fig-naive-trends-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>Even <em>before</em> the ACA expansion in 2014, expansion states had steeper downward trends in uninsured rates. That pre-existing divergence would be incorrectly attributed to the policy if we ran a naive DiD. The treated states were already “improving” faster—perhaps because they had more liberal politics, invested more in public health, or had demographics that were trending toward higher coverage for other reasons.</p>
<p>Using all non-expanding states as controls gives us a bad counterfactual.</p>
</section>
<section id="the-intuition-behind-propensity-score-weighting" class="level3" data-number="13.2.2">
<h3 data-number="13.2.2" class="anchored" data-anchor-id="the-intuition-behind-propensity-score-weighting"><span class="header-section-number">13.2.2</span> The Intuition Behind Propensity Score Weighting</h3>
<p>So what can we do? One approach is to find untreated states that are <em>similar</em> to treated states—states that, based on their observable characteristics, looked like they <em>should have</em> expanded Medicaid but didn’t. The logic is straightforward: if a state had a high Democratic vote share, high poverty rates, and other features that strongly predicted expansion, yet it <em>didn’t</em> expand, then that state is probably a better counterfactual for expansion states than, say, a deep-red state that was never going to expand.</p>
<p><strong>Propensity score methods</strong> formalize this intuition. The procedure works in three steps:</p>
<ol type="1">
<li>Estimate each state’s probability of being treated, based on observable characteristics.</li>
<li>Give more weight to control states that “look like” they should have been treated.</li>
<li>Use these weights in the TWFE DiD regression.</li>
</ol>
<p>Control units with high propensity scores—high predicted probability of treatment—that were <em>not</em> actually treated become the primary comparison group. They are observably similar to treated units, which makes the parallel trends assumption more plausible among this reweighted comparison.</p>
</section>
<section id="step-1-estimate-propensity-scores" class="level3" data-number="13.2.3">
<h3 data-number="13.2.3" class="anchored" data-anchor-id="step-1-estimate-propensity-scores"><span class="header-section-number">13.2.3</span> Step 1: Estimate Propensity Scores</h3>
<p>The <strong>propensity score</strong> is the predicted probability that a unit receives treatment, conditional on a set of observable characteristics. We estimate it with a logistic regression:</p>
<p><span class="math display">\[
P(D_i = 1 \mid X) = G(\beta_0 + \beta_1 X_1 + \beta_2 X_2 + \ldots + \beta_k X_k)
\]</span></p>
<p>where <span class="math inline">\(D_i\)</span> is the treatment indicator (1 if the state expanded, 0 otherwise), <span class="math inline">\(G(\cdot)\)</span> is the logistic function, and the <span class="math inline">\(X\)</span> variables are pre-treatment characteristics that predict treatment.</p>
<p>For the ACA expansion example, we might include:</p>
<ul>
<li><span class="math inline">\(X_1\)</span>: Democratic vote share (political leaning)</li>
<li><span class="math inline">\(X_2\)</span>: Region of the country</li>
<li><span class="math inline">\(X_3\)</span>: Baseline poverty rates</li>
</ul>
<p>We estimate this using only pre-treatment data (i.e., data from before 2014), because we want characteristics that predict treatment <em>assignment</em>, not characteristics that were themselves affected by the treatment.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate to state level using only pre-treatment data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>state_data <span class="ot">&lt;-</span> panel_data <span class="sc">|&gt;</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(post <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(state_id, is_expanded) <span class="sc">|&gt;</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">dem_share =</span> <span class="fu">mean</span>(X1),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">region =</span> <span class="fu">mean</span>(X2),</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">poverty =</span> <span class="fu">mean</span>(X3),</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">.groups =</span> <span class="st">'drop'</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate propensity scores with logistic regression</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>ps_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(is_expanded <span class="sc">~</span> dem_share <span class="sc">+</span> region <span class="sc">+</span> poverty,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> state_data,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">family =</span> <span class="fu">binomial</span>(<span class="st">"logit"</span>))</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Get predicted probabilities (the propensity scores)</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>state_data <span class="ot">&lt;-</span> state_data <span class="sc">|&gt;</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">ps_score =</span> <span class="fu">predict</span>(ps_model, <span class="at">type =</span> <span class="st">"response"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="step-2-calculate-inverse-propensity-weights" class="level3" data-number="13.2.4">
<h3 data-number="13.2.4" class="anchored" data-anchor-id="step-2-calculate-inverse-propensity-weights"><span class="header-section-number">13.2.4</span> Step 2: Calculate Inverse Propensity Weights</h3>
<p>Once we have propensity scores, we compute the <strong>inverse propensity weights (IPW)</strong>. The formula is:</p>
<p><span class="math display">\[
IPW_i = D_i + (1 - D_i) \times \frac{\hat{P}_i}{1 - \hat{P}_i}
\]</span></p>
<p>What does this formula do?</p>
<ul>
<li><strong>If a unit is treated</strong> (<span class="math inline">\(D_i = 1\)</span>): the weight is simply <span class="math inline">\(IPW_i = 1\)</span>. All treated units get equal weight.</li>
<li><strong>If a unit is untreated</strong> (<span class="math inline">\(D_i = 0\)</span>): the weight is <span class="math inline">\(IPW_i = \frac{\hat{P}_i}{1 - \hat{P}_i}\)</span>.</li>
</ul>
<p>That second case is where the action is. The ratio <span class="math inline">\(\frac{\hat{P}_i}{1 - \hat{P}_i}\)</span> is the <em>odds</em> that the unit would have been treated. When the predicted probability is high (say, <span class="math inline">\(\hat{P}_i = 0.87\)</span>), the weight is large (<span class="math inline">\(\frac{0.87}{0.13} = 6.69\)</span>). When the predicted probability is low (say, <span class="math inline">\(\hat{P}_i = 0.16\)</span>), the weight is small (<span class="math inline">\(\frac{0.16}{0.84} = 0.19\)</span>).</p>
<p>The bottom line: <strong>control units that look like they should have been treated get a lot of weight; control units that look nothing like treated units get very little weight.</strong></p>
<p>A concrete example with specific states makes this clearer:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">State</th>
<th style="text-align: center;">Treatment Status</th>
<th style="text-align: center;"><span class="math inline">\(\hat{P}_i\)</span></th>
<th style="text-align: center;"><span class="math inline">\(IPW_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">MI</td>
<td style="text-align: center;"><span class="math inline">\(D_i = 1\)</span> (Treated)</td>
<td style="text-align: center;">0.91</td>
<td style="text-align: center;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">WI</td>
<td style="text-align: center;"><span class="math inline">\(D_i = 0\)</span> (Control)</td>
<td style="text-align: center;">0.87</td>
<td style="text-align: center;">6.69</td>
</tr>
<tr class="odd">
<td style="text-align: center;">TX</td>
<td style="text-align: center;"><span class="math inline">\(D_i = 0\)</span> (Control)</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">0.19</td>
</tr>
<tr class="even">
<td style="text-align: center;">PA</td>
<td style="text-align: center;"><span class="math inline">\(D_i = 0\)</span> (Control)</td>
<td style="text-align: center;">0.79</td>
<td style="text-align: center;">3.76</td>
</tr>
<tr class="odd">
<td style="text-align: center;">MA</td>
<td style="text-align: center;"><span class="math inline">\(D_i = 1\)</span> (Treated)</td>
<td style="text-align: center;">0.98</td>
<td style="text-align: center;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">LA</td>
<td style="text-align: center;"><span class="math inline">\(D_i = 0\)</span> (Control)</td>
<td style="text-align: center;">0.28</td>
<td style="text-align: center;">0.38</td>
</tr>
</tbody>
</table>
<p>Wisconsin and Pennsylvania—control states with high propensity scores—get weights of 6.69 and 3.76 respectively. They will dominate the weighted control group. Texas and Louisiana—control states with low propensity scores—get weights of 0.19 and 0.38. They barely contribute to the comparison. The effect is to build a weighted control group that is observably similar to the treated group.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate IPW weights</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>state_data <span class="ot">&lt;-</span> state_data <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ipw =</span> <span class="fu">case_when</span>(</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>            is_expanded <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>            is_expanded <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> ps_score <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> ps_score)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Show a sample of weights</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>state_data <span class="sc">|&gt;</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(state_id, is_expanded, ps_score, ipw) <span class="sc">|&gt;</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(ipw)) <span class="sc">|&gt;</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-ipw-weights" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ipw-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.1: Top 10 states by IPW weight. Control states with high propensity scores receive large weights.
</figcaption>
<div aria-describedby="tbl-ipw-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">state_id</th>
<th style="text-align: right;">is_expanded</th>
<th style="text-align: right;">ps_score</th>
<th style="text-align: right;">ipw</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">32</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">5.94</td>
</tr>
<tr class="even">
<td style="text-align: right;">181</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">3.77</td>
</tr>
<tr class="odd">
<td style="text-align: right;">51</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">3.06</td>
</tr>
<tr class="even">
<td style="text-align: right;">101</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.69</td>
<td style="text-align: right;">2.26</td>
</tr>
<tr class="odd">
<td style="text-align: right;">31</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">1.85</td>
</tr>
<tr class="even">
<td style="text-align: right;">150</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: right;">1.71</td>
</tr>
<tr class="odd">
<td style="text-align: right;">29</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">1.58</td>
</tr>
<tr class="even">
<td style="text-align: right;">106</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">1.41</td>
</tr>
<tr class="odd">
<td style="text-align: right;">87</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.54</td>
<td style="text-align: right;">1.15</td>
</tr>
<tr class="even">
<td style="text-align: right;">152</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">1.13</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="visualizing-the-weighting" class="level3" data-number="13.2.5">
<h3 data-number="13.2.5" class="anchored" data-anchor-id="visualizing-the-weighting"><span class="header-section-number">13.2.5</span> Visualizing the Weighting</h3>
<p>We should also check how the propensity score distribution differs between treated and control units. We want good <strong>overlap</strong>—treated and control units should have propensity scores in the same range. If the distributions barely overlap, then there are few untreated units that resemble treated units, and IPW will rely heavily on a handful of extreme weights.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ps-overlap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-ps-overlap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.2: Distribution of propensity scores by treatment status. Good overlap between the two distributions means we can find control units that resemble treated units.
</figcaption>
<div aria-describedby="fig-ps-overlap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="advanced_did_files/figure-html/fig-ps-overlap-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="step-3-run-the-weighted-twfe-regression" class="level3" data-number="13.2.6">
<h3 data-number="13.2.6" class="anchored" data-anchor-id="step-3-run-the-weighted-twfe-regression"><span class="header-section-number">13.2.6</span> Step 3: Run the Weighted TWFE Regression</h3>
<p>Finally, we estimate the standard TWFE DiD regression, but using the IPW weights. In <code>fixest</code>, this is done by passing the weights to the <code>weights</code> argument of <code>feols()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge weights into panel data</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>panel_weighted <span class="ot">&lt;-</span> panel_data <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">left_join</span>(<span class="fu">select</span>(state_data, state_id, ipw), <span class="at">by =</span> <span class="st">"state_id"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Naive (unweighted) DiD</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>did_naive <span class="ot">&lt;-</span> <span class="fu">feols</span>(uninsured_rate <span class="sc">~</span> treat_active <span class="sc">|</span> state_id <span class="sc">+</span> year,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">vcov =</span> <span class="st">"HC1"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> panel_data)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># IPW-weighted DiD</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>did_ipw <span class="ot">&lt;-</span> <span class="fu">feols</span>(uninsured_rate <span class="sc">~</span> treat_active <span class="sc">|</span> state_id <span class="sc">+</span> year,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">vcov =</span> <span class="st">"HC1"</span>,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>                 <span class="at">weights =</span> <span class="sc">~</span>ipw,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> panel_weighted)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="comparing-results" class="level3" data-number="13.2.7">
<h3 data-number="13.2.7" class="anchored" data-anchor-id="comparing-results"><span class="header-section-number">13.2.7</span> Comparing Results</h3>
<p>Let’s see what IPW weighting does to the parallel trends picture. The figure below shows the IPW-weighted average uninsured rates for treated and control states.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ipw-comparison" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-ipw-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.3: After IPW weighting, the control group’s pre-trends closely track the treated group’s pre-trends. Compare this to the naive comparison in the earlier figure.
</figcaption>
<div aria-describedby="fig-ipw-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="advanced_did_files/figure-html/fig-ipw-comparison-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>After reweighting, the control group tracks the treated group much more closely in the pre-treatment period. If the groups are on parallel paths before the policy, we can be more confident that the post-treatment divergence reflects the causal effect of the policy rather than pre-existing differences.</p>
<p>Now let’s compare the actual coefficient estimates side-by-side. Recall that the true ATT in our simulated data is <span class="math inline">\(-5\)</span> percentage points.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-side-by-side" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-side-by-side-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.4: Naive vs.&nbsp;IPW-weighted trends side by side. The left panel shows diverging pre-trends; the right panel shows the improvement after reweighting.
</figcaption>
<div aria-describedby="fig-side-by-side-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="advanced_did_files/figure-html/fig-side-by-side-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="cell">
<div id="tbl-ipw-comparison" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ipw-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.2: The naive estimate overshoots the true effect because it attributes pre-existing trends to the policy. The IPW estimate is much closer to the truth. Note how the naive 95% confidence interval does not even contain the true effect of -5.
</figcaption>
<div aria-describedby="tbl-ipw-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 45%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">95% CI Lower</th>
<th style="text-align: right;">95% CI Upper</th>
<th style="text-align: right;">True Effect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Naive DiD (all controls, equal weight)</td>
<td style="text-align: right;">-10.91</td>
<td style="text-align: right;">-11.50</td>
<td style="text-align: right;">-10.32</td>
<td style="text-align: right;">-5</td>
</tr>
<tr class="even">
<td style="text-align: left;">IPW-Weighted DiD</td>
<td style="text-align: right;">-6.24</td>
<td style="text-align: right;">-6.99</td>
<td style="text-align: right;">-5.50</td>
<td style="text-align: right;">-5</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The naive DiD estimate is substantially biased—it is too negative because it confounds the policy effect with the pre-existing trend differences. The IPW estimate is much closer to the true effect of <span class="math inline">\(-5\)</span> percentage points.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The IPW Estimate Is Only as Good as the Propensity Score Model
</div>
</div>
<div class="callout-body-container callout-body">
<p>IPW-DiD works by reweighting the control group to look more like the treatment group on observables. If you omit an important confounder from the propensity score model—something that predicts both treatment and the outcome trend—the bias remains. There is no free lunch here: the method corrects for the observable differences you model, not the ones you miss.</p>
</div>
</div>
</section>
<section id="summary-of-the-ipw-did-algorithm" class="level3" data-number="13.2.8">
<h3 data-number="13.2.8" class="anchored" data-anchor-id="summary-of-the-ipw-did-algorithm"><span class="header-section-number">13.2.8</span> Summary of the IPW-DiD Algorithm</h3>
<p>The full IPW-DiD procedure is:</p>
<ol type="1">
<li><strong>Estimate propensity scores.</strong> Run a logistic regression of treatment status on pre-treatment covariates. The predicted probabilities are the propensity scores.</li>
<li><strong>Compute IPW weights.</strong> Treated units get weight 1. Untreated units get weight <span class="math inline">\(\hat{P}_i / (1 - \hat{P}_i)\)</span>.</li>
<li><strong>Check overlap.</strong> Make sure the propensity score distributions for treated and control units overlap. If there are regions with no overlap, those units cannot be compared.</li>
<li><strong>Run the weighted TWFE regression.</strong> Use the IPW weights in your standard <code>feols()</code> call.</li>
</ol>
</section>
</section>
<section id="dynamic-did-and-event-studies" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="dynamic-did-and-event-studies"><span class="header-section-number">13.3</span> Dynamic DiD and Event Studies</h2>
<section id="why-treatment-effects-may-change-over-time" class="level3" data-number="13.3.1">
<h3 data-number="13.3.1" class="anchored" data-anchor-id="why-treatment-effects-may-change-over-time"><span class="header-section-number">13.3.1</span> Why Treatment Effects May Change Over Time</h3>
<p>The basic TWFE DiD model estimates a single treatment effect <span class="math inline">\(\hat{\beta}\)</span> that applies to every post-treatment period equally. This is a strong restriction. In practice, many policies have effects that <strong>evolve over time</strong>:</p>
<ul>
<li>A job training program might have small effects initially that grow as participants gain experience and find better jobs.</li>
<li>A minimum wage increase might cause immediate disemployment effects that fade as firms adjust their production processes.</li>
<li>An environmental regulation might have mounting effects as firms gradually come into compliance.</li>
<li>A public health intervention might show a burst of impact that then diminishes as the population adjusts.</li>
</ul>
<p>If the treatment effect is changing over time, a single coefficient averages over these different effects and may miss important dynamics. Worse, it might obscure the fact that the effect is growing, or that it peaked early and then faded.</p>
<p><strong>Dynamic DiD</strong> (sometimes called an <strong>event study</strong>) solves this by estimating separate treatment effects for each period relative to the treatment date.</p>
</section>
<section id="relative-time" class="level3" data-number="13.3.2">
<h3 data-number="13.3.2" class="anchored" data-anchor-id="relative-time"><span class="header-section-number">13.3.2</span> Relative Time</h3>
<p>Dynamic DiD models are built around <strong>relative time</strong>—the number of periods that have elapsed since the event occurred—rather than calendar time. If the policy was enacted in 2015, then:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Calendar Year</th>
<th style="text-align: center;">Relative Time (<span class="math inline">\(k\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2012</td>
<td style="text-align: center;"><span class="math inline">\(-3\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">2013</td>
<td style="text-align: center;"><span class="math inline">\(-2\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">2014</td>
<td style="text-align: center;"><span class="math inline">\(-1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>2015</strong> (treatment)</td>
<td style="text-align: center;"><strong>0</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;">2016</td>
<td style="text-align: center;"><span class="math inline">\(+1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">2017</td>
<td style="text-align: center;"><span class="math inline">\(+2\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">2018</td>
<td style="text-align: center;"><span class="math inline">\(+3\)</span></td>
</tr>
</tbody>
</table>
<p>Relative time <span class="math inline">\(k = 0\)</span> is the period in which treatment occurs. Negative values of <span class="math inline">\(k\)</span> represent the pre-treatment period; positive values represent the post-treatment period.</p>
<p>Why frame things this way? Because it lets us estimate the treatment effect at each distance from the event. And it lets us <em>test</em> whether there were “effects” before the policy even started—which there shouldn’t be, if parallel trends holds.</p>
</section>
<section id="the-dynamic-did-model" class="level3" data-number="13.3.3">
<h3 data-number="13.3.3" class="anchored" data-anchor-id="the-dynamic-did-model"><span class="header-section-number">13.3.3</span> The Dynamic DiD Model</h3>
<p>The dynamic DiD model replaces the single <span class="math inline">\(D_{it}\)</span> indicator with a set of dummy variables, one for each value of relative time:</p>
<p><span id="eq-dyn-did"><span class="math display">\[
y_{it} = \sum_{k \neq -1} \beta_k D_{it}^k + \alpha_i + \tau_t + \mu_{it}
\tag{13.1}\]</span></span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(D_{it}^k\)</span> is a dummy variable that equals 1 if unit <span class="math inline">\(i\)</span> is in the treatment group <strong>and</strong> period <span class="math inline">\(t\)</span> corresponds to relative time <span class="math inline">\(k\)</span> for that unit, and 0 otherwise.</li>
<li><span class="math inline">\(\alpha_i\)</span> and <span class="math inline">\(\tau_t\)</span> are unit and time fixed effects, as before.</li>
<li>We <strong>omit</strong> the dummy for <span class="math inline">\(k = -1\)</span> (the period just before treatment) as the <strong>reference category</strong>.</li>
</ul>
<p>Because <span class="math inline">\(k = -1\)</span> is omitted, all of the <span class="math inline">\(\hat{\beta}_k\)</span> coefficients are interpreted as the treatment effect at time <span class="math inline">\(k\)</span> <em>relative to the period just before treatment</em>.</p>
<ul>
<li>The <strong>pre-treatment coefficients</strong> (<span class="math inline">\(\hat{\beta}_{-2}, \hat{\beta}_{-3}, \ldots\)</span>) should all be close to zero if parallel trends holds. Why? Think about what these coefficients measure. The coefficient <span class="math inline">\(\hat{\beta}_{-3}\)</span>, for example, estimates the difference between treated and control groups at <span class="math inline">\(k = -3\)</span> relative to their difference at <span class="math inline">\(k = -1\)</span>. If both groups were on the same trajectory before the policy, then the gap between them should not have been changing in the pre-treatment period, and all of these coefficients should be near zero. If instead <span class="math inline">\(\hat{\beta}_{-3}\)</span> is large and statistically significant, it means the groups were already drifting apart three years before the policy started—an obvious warning sign that the control group was not on the same path as the treated group. In that case, we cannot credibly attribute any post-treatment divergence to the policy, because the groups were diverging anyway.</li>
<li>The <strong>post-treatment coefficients</strong> (<span class="math inline">\(\hat{\beta}_0, \hat{\beta}_1, \hat{\beta}_2, \ldots\)</span>) trace out the causal effect of the policy over time, again relative to the baseline period.</li>
</ul>
</section>
<section id="constructing-the-data-for-dynamic-did" class="level3" data-number="13.3.4">
<h3 data-number="13.3.4" class="anchored" data-anchor-id="constructing-the-data-for-dynamic-did"><span class="header-section-number">13.3.4</span> Constructing the Data for Dynamic DiD</h3>
<p>To estimate <a href="#eq-dyn-did" class="quarto-xref">Equation&nbsp;<span>13.1</span></a>, we need to create a set of dummy variables—one for each relative time period, interacted with treatment status. Let’s walk through the data construction with a small example.</p>
<p>Suppose we have 4 units (2 treated, 2 control), observed from 2014 to 2018, with treatment occurring in 2016. The standard DiD dataset has a single <code>treat_post</code> column. For dynamic DiD, we replace it with a series of <code>rel_t_treat</code> dummies:</p>
<div class="cell">
<div id="tbl-dynamic-dummies" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dynamic-dummies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.3: Relative time treatment dummies for a simple 4-unit, 5-year panel. For treated units, exactly one dummy equals 1 in each period.
</figcaption>
<div aria-describedby="tbl-dynamic-dummies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 14%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">unit_id</th>
<th style="text-align: right;">year</th>
<th style="text-align: right;">treatment_group</th>
<th style="text-align: right;">treat_post</th>
<th style="text-align: right;">rel_t_treat_-1</th>
<th style="text-align: right;">rel_t_treat_-2</th>
<th style="text-align: right;">rel_t_treat_0</th>
<th style="text-align: right;">rel_t_treat_1</th>
<th style="text-align: right;">rel_t_treat_2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2014</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2015</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2016</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2017</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2018</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2014</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2015</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2016</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2017</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2018</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2014</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2015</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2016</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2017</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2018</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">2014</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">2015</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">2016</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">2017</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">2018</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Notice the pattern: for treated units, exactly one of the <code>rel_t_treat</code> columns equals 1 in each period (corresponding to that period’s relative time). For control units, all the <code>rel_t_treat</code> columns are 0. When we regress the outcome on these dummies (omitting <code>rel_t_treat_-1</code>), each coefficient gives us the treatment effect at that specific distance from the policy.</p>
</section>
<section id="example-environmental-policy-and-manufacturing-employment" class="level3" data-number="13.3.5">
<h3 data-number="13.3.5" class="anchored" data-anchor-id="example-environmental-policy-and-manufacturing-employment"><span class="header-section-number">13.3.5</span> Example: Environmental Policy and Manufacturing Employment</h3>
<p>Suppose we want to estimate how an environmental regulation affects manufacturing employment in cities. We have data on 50 cities observed from 1995 to 2010. In 2005, 25 cities adopted the policy while 25 did not. The true effect in our simulation starts at <span class="math inline">\(-100\)</span> jobs in the adoption year, grows to <span class="math inline">\(-300\)</span> after one year, <span class="math inline">\(-450\)</span> after two years, and levels off at <span class="math inline">\(-500\)</span> from year three onward.</p>
<p>Let’s start by visualizing the raw trends:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-env-trends" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-env-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.5: Before the policy in 2005, treated and control cities follow parallel paths. After 2005, treated cities experience a growing decline in manufacturing employment.
</figcaption>
<div aria-describedby="fig-env-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="advanced_did_files/figure-html/fig-env-trends-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>The trends are parallel before 2005—good news for our identifying assumption. After the policy, treated cities experience a growing decline in manufacturing employment relative to control cities.</p>
<p>A standard (static) DiD would estimate a single average effect across all post-treatment years. But the figure suggests the effect is growing over time. Dynamic DiD lets us capture this.</p>
</section>
<section id="estimating-the-dynamic-model" class="level3" data-number="13.3.6">
<h3 data-number="13.3.6" class="anchored" data-anchor-id="estimating-the-dynamic-model"><span class="header-section-number">13.3.6</span> Estimating the Dynamic Model</h3>
<p>We estimate the model by including all the relative-time dummies (except <span class="math inline">\(k = -1\)</span>) along with city and year fixed effects:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate dynamic DiD (rel_t_treat_-1 omitted as reference)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dyn_did <span class="ot">&lt;-</span> <span class="fu">feols</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    manufacturing_emp <span class="sc">~</span> <span class="st">`</span><span class="at">rel_t_treat_-10</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">rel_t_treat_-9</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">rel_t_treat_-8</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">rel_t_treat_-7</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">rel_t_treat_-6</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">rel_t_treat_-5</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">rel_t_treat_-4</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">rel_t_treat_-3</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">rel_t_treat_-2</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">rel_t_treat_0</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">rel_t_treat_1</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">rel_t_treat_2</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">rel_t_treat_3</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">rel_t_treat_4</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">rel_t_treat_5</span><span class="st">`</span> <span class="sc">|</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>        city_id <span class="sc">+</span> year,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">vcov =</span> <span class="st">"HC1"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> env_data</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Each coefficient tells us the estimated treatment effect at that relative time, compared to the omitted period <span class="math inline">\(k = -1\)</span>.</p>
</section>
<section id="the-event-study-plot" class="level3" data-number="13.3.7">
<h3 data-number="13.3.7" class="anchored" data-anchor-id="the-event-study-plot"><span class="header-section-number">13.3.7</span> The Event Study Plot</h3>
<p>The standard way to present dynamic DiD results is an <strong>event study plot</strong>. We plot each estimated <span class="math inline">\(\hat{\beta}_k\)</span> coefficient along with its 95% confidence interval on the y-axis, and relative time on the x-axis. A horizontal line at zero and a vertical dashed line at the treatment date provide reference points.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-event-study" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-event-study-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.6: Event study plot. Pre-treatment coefficients cluster around zero, supporting parallel trends. Post-treatment coefficients show the growing negative effect of the environmental policy, starting at about -100 in the adoption year and leveling off near -500.
</figcaption>
<div aria-describedby="fig-event-study-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="advanced_did_files/figure-html/fig-event-study-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="interpreting-the-event-study" class="level3" data-number="13.3.8">
<h3 data-number="13.3.8" class="anchored" data-anchor-id="interpreting-the-event-study"><span class="header-section-number">13.3.8</span> Interpreting the Event Study</h3>
<p>Look at the event study plot. There are three regions worth discussing:</p>
<p><strong>Pre-treatment coefficients (<span class="math inline">\(k &lt; -1\)</span>).</strong> These are all close to zero, and their 95% confidence intervals include zero. This is the key test for parallel trends. Each pre-treatment coefficient estimates how the treated-control gap at time <span class="math inline">\(k\)</span> differs from the gap at <span class="math inline">\(k = -1\)</span>. If the two groups were trending in the same direction before the policy, these differences should all be small and statistically indistinguishable from zero.</p>
<p>Why does this work as a test? Consider what it would mean if <span class="math inline">\(\hat{\beta}_{-5}\)</span> were large and negative. That would say: “Five years before this policy was enacted, the treated cities already had lower employment relative to control cities than they did one year before the policy.” That is a <em>trend difference</em> that existed well before anyone passed a regulation. If such pre-treatment gaps exist, we have no way to know whether the post-treatment gaps are caused by the policy or are just a continuation of whatever was already happening. The pre-treatment coefficients are, in effect, a <strong>placebo test</strong>: we are estimating the “effect” of a policy in years when the policy did not yet exist. If we find statistically significant effects in those placebo years, something is wrong with our control group.</p>
<p>In our example, the pre-treatment coefficients are all small and bounce around zero with no discernible pattern. This is reassuring—it suggests that before the regulation, treated and control cities were on parallel paths.</p>
<p><strong>The reference period (<span class="math inline">\(k = -1\)</span>).</strong> This is zero by construction, since it is the omitted category. All other coefficients are measured relative to this period.</p>
<p><strong>Post-treatment coefficients (<span class="math inline">\(k \geq 0\)</span>).</strong> These trace out the causal effect of the policy over time. The effect starts at about <span class="math inline">\(-100\)</span> in the adoption year (<span class="math inline">\(k = 0\)</span>), grows to roughly <span class="math inline">\(-300\)</span> at <span class="math inline">\(k = 1\)</span>, reaches about <span class="math inline">\(-450\)</span> at <span class="math inline">\(k = 2\)</span>, and levels off near <span class="math inline">\(-500\)</span> from <span class="math inline">\(k = 3\)</span> onward. This matches the true effects we built into the simulation: the regulation reduced manufacturing employment, and the effect grew over several years before stabilizing.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Pre-Trends as a Diagnostic
</div>
</div>
<div class="callout-body-container callout-body">
<p>The pre-treatment coefficients are the most important part of an event study for judging whether a DiD design is credible. If you see large, statistically significant estimates before the policy was implemented, it means the treated and control groups were already diverging for reasons unrelated to the treatment. Any post-treatment divergence could just be a continuation of those pre-existing trends, and the DiD estimate cannot be trusted.</p>
<p>Note that <em>failing</em> to find significant pre-trends does not <em>prove</em> parallel trends holds—we might just lack the statistical power to detect a violation, or the violation could start right at the treatment date. But finding flat pre-treatment coefficients is a necessary (if not sufficient) condition for a credible DiD design.</p>
</div>
</div>
</section>
<section id="a-note-on-staggered-adoption" class="level3" data-number="13.3.9">
<h3 data-number="13.3.9" class="anchored" data-anchor-id="a-note-on-staggered-adoption"><span class="header-section-number">13.3.9</span> A Note on Staggered Adoption</h3>
<p>Our environmental policy example is a “simple” case: all 25 treated cities adopted the policy in the same year (2005). This is called <strong>simultaneous adoption</strong>. But many real-world policies are adopted at different times by different units—some states raise their minimum wage in 2015, others in 2017, and still others in 2020. This is called <strong>staggered adoption</strong>.</p>
<p>The standard TWFE dynamic DiD model can produce seriously biased estimates under staggered adoption. The problem, documented in a series of influential papers by Goodman-Bacon (2021), Callaway and Sant’Anna (2021), Sun and Abraham (2021), and others, arises because the TWFE estimator implicitly uses already-treated units as controls for later-treated units, which can create “negative weights” on some treatment effects.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Staggered Adoption Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>If units in your study are treated at different times, the simple TWFE estimator described here can be severely biased. You should use one of the newer estimators designed for staggered adoption (e.g., the Callaway-Sant’Anna estimator, implemented in the <code>did</code> R package, or the Sun-Abraham estimator). The details of these methods are beyond the scope of this chapter, but you should be aware that this is an active and important area of research.</p>
</div>
</div>
</section>
</section>
<section id="cluster-robust-standard-errors" class="level2" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="cluster-robust-standard-errors"><span class="header-section-number">13.4</span> Cluster-Robust Standard Errors</h2>
<section id="the-problem-non-independent-observations" class="level3" data-number="13.4.1">
<h3 data-number="13.4.1" class="anchored" data-anchor-id="the-problem-non-independent-observations"><span class="header-section-number">13.4.1</span> The Problem: Non-Independent Observations</h3>
<p>Everything we have discussed so far concerns getting the <em>point estimate</em> right—ensuring that <span class="math inline">\(\hat{\beta}\)</span> is close to the true <span class="math inline">\(\beta\)</span>. But a point estimate without a measure of uncertainty is not very useful. We also need our standard errors, p-values, and confidence intervals to be correct.</p>
<p>Standard OLS assumes that observations are <em>independent</em>. But in panel data, this assumption is almost always violated. Observations from the same unit across time are correlated: if a state has a high uninsured rate in 2012, it probably has a high uninsured rate in 2013 too. Students in the same classroom share a teacher, a curriculum, and a socioeconomic neighborhood. Workers at the same firm share management quality and corporate culture.</p>
<p>When errors are <strong>correlated within groups</strong> (or “clusters”), standard OLS standard errors are wrong. They are typically <em>too small</em>, which means:</p>
<ul>
<li>T-statistics are too large.</li>
<li>P-values are too small.</li>
<li>Confidence intervals are too narrow.</li>
<li>You commit <strong>Type I errors</strong> (false positives) far more often than you think.</li>
</ul>
<p>Recall that a <strong>Type I error</strong> is when you reject the null hypothesis even though it is actually true—you conclude that a policy had an effect when it really did not. We usually set our significance level at <span class="math inline">\(\alpha = 0.05\)</span>, meaning we accept a 5% false positive rate. But when you ignore clustering, your <em>actual</em> false positive rate can be 20%, 30%, or even higher, all while R happily reports a p-value below 0.05.</p>
</section>
<section id="an-intuitive-example" class="level3" data-number="13.4.2">
<h3 data-number="13.4.2" class="anchored" data-anchor-id="an-intuitive-example"><span class="header-section-number">13.4.2</span> An Intuitive Example</h3>
<p>Here is a simple way to think about the problem. Imagine you want to estimate the average height of 5th graders in a city. You have two sampling plans:</p>
<p><strong>Plan A (Simple Random Sample):</strong> Randomly select 1,000 students from across the entire city.</p>
<p><strong>Plan B (Cluster Sample):</strong> Randomly select 40 classrooms, and measure all 25 students in each classroom.</p>
<p>Both plans give you <span class="math inline">\(N = 1{,}000\)</span> observations. But they are not equally informative. In Plan B, students within the same classroom tend to be similar—they share a teacher, a neighborhood, and often a socioeconomic background. Measuring 25 students from the same classroom gives you much less new information than measuring 25 students drawn independently from across the city. The 25 students are not 25 independent data points; they are more like one and a half data points (exaggerating slightly to make the point).</p>
<p>If you compute a standard error pretending that all 1,000 observations are independent, you will badly understate the true sampling uncertainty. Your confidence interval will be far too narrow.</p>
</section>
<section id="what-is-a-cluster" class="level3" data-number="13.4.3">
<h3 data-number="13.4.3" class="anchored" data-anchor-id="what-is-a-cluster"><span class="header-section-number">13.4.3</span> What Is a “Cluster”?</h3>
<p>A <strong>cluster</strong> is a group of observations where errors are likely correlated within the group but independent across groups. Some common examples:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Individual Unit</th>
<th style="text-align: center;">Natural Cluster</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Students</td>
<td style="text-align: center;">Classroom</td>
</tr>
<tr class="even">
<td style="text-align: center;">Patients</td>
<td style="text-align: center;">Hospital</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Workers</td>
<td style="text-align: center;">Firm</td>
</tr>
<tr class="even">
<td style="text-align: center;">Counties</td>
<td style="text-align: center;">State</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Person-year observations</td>
<td style="text-align: center;">Person</td>
</tr>
</tbody>
</table>
<p>In DiD settings, the most natural cluster is usually the unit at which treatment is assigned. If the policy is set at the state level, then all observations within a state (across time) form a cluster.</p>
</section>
<section id="visualizing-clustered-data" class="level3" data-number="13.4.4">
<h3 data-number="13.4.4" class="anchored" data-anchor-id="visualizing-clustered-data"><span class="header-section-number">13.4.4</span> Visualizing Clustered Data</h3>
<p>The figure below illustrates what clustered data looks like. Each color represents a different cluster. Notice how observations within a cluster are bunched together—they are more similar to each other than to observations in other clusters. Standard OLS treats every dot as an independent piece of information, when in reality, dots of the same color are telling you largely the same thing.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cluster-visual" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-cluster-visual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.7: Each color represents a cluster. Observations within a cluster are correlated—they tend to cluster around the group mean (dashed lines). Standard errors that treat all observations as independent will be too small.
</figcaption>
<div aria-describedby="fig-cluster-visual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="advanced_did_files/figure-html/fig-cluster-visual-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="the-statistical-violation" class="level3" data-number="13.4.5">
<h3 data-number="13.4.5" class="anchored" data-anchor-id="the-statistical-violation"><span class="header-section-number">13.4.5</span> The Statistical Violation</h3>
<p>Formally, this is a violation of the Gauss-Markov assumptions of random sampling and homoskedasticity. In a standard OLS model, we assume that the error terms <span class="math inline">\(\mu_i\)</span> and <span class="math inline">\(\mu_j\)</span> are uncorrelated for any two observations <span class="math inline">\(i \neq j\)</span>. With clustered data, this fails: if observation <span class="math inline">\(i\)</span> has a high error, then other observations in the same cluster probably do too.</p>
<p>On the bright side, clustering does <strong>not</strong> bias the coefficient estimate <span class="math inline">\(\hat{\beta}\)</span>. Your point estimate is still unbiased. The problem is that it invalidates the standard error calculation, which means your inference—your t-tests, p-values, and confidence intervals—is wrong.</p>
<p>The degree of the problem depends on the <strong>intra-cluster correlation (ICC)</strong>: the fraction of total variance in the outcome that is attributable to between-cluster differences. When the ICC is high, within-cluster observations are very similar, and the effective sample size is much smaller than the nominal sample size. When the ICC is zero (no clustering), standard OLS inference is valid.</p>
</section>
<section id="simulation-type-i-error-rates-with-and-without-clustering" class="level3" data-number="13.4.6">
<h3 data-number="13.4.6" class="anchored" data-anchor-id="simulation-type-i-error-rates-with-and-without-clustering"><span class="header-section-number">13.4.6</span> Simulation: Type I Error Rates With and Without Clustering</h3>
<p>To see how bad the Type I error problem gets, let’s run a simulation. We will generate data where the <strong>true treatment effect is exactly zero</strong>, then run 500 regressions and count how often we incorrectly reject the null hypothesis—that is, how often we commit a Type I error. If our standard errors are correct, the Type I error rate should be about 5% (since we are testing at <span class="math inline">\(\alpha = 0.05\)</span>). If the standard errors are too small because we ignored clustering, the Type I error rate will be much higher.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cluster-sim" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-cluster-sim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.8: Under the null hypothesis (true effect = 0), p-values should be uniformly distributed and we should reject at most 5% of the time. With naive standard errors (left panel), the p-values pile up near zero and we reject far too often. Cluster-robust standard errors (right panel) fix the problem.
</figcaption>
<div aria-describedby="fig-cluster-sim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="advanced_did_files/figure-html/fig-cluster-sim-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>The results speak for themselves:</p>
<ul>
<li>With <strong>naive standard errors</strong>: The Type I error rate is 61%. Remember, the true effect is zero, so <em>every single rejection is a false positive</em>. We are supposed to be rejecting only 5% of the time, but instead we are committing Type I errors at a rate many times higher than that.</li>
<li>With <strong>cluster-robust standard errors</strong>: The Type I error rate is about 6%, which is close to the nominal 5% we intended.</li>
</ul>
<p>This is not a minor technical footnote. If you ignore clustering in your panel data, you will “discover” treatment effects that do not exist. You will write up results that look statistically significant but are just noise. Published papers have been called into question for exactly this reason.</p>
</section>
<section id="how-cluster-robust-standard-errors-work" class="level3" data-number="13.4.7">
<h3 data-number="13.4.7" class="anchored" data-anchor-id="how-cluster-robust-standard-errors-work"><span class="header-section-number">13.4.7</span> How Cluster-Robust Standard Errors Work</h3>
<p>The formula for cluster-robust standard errors is too involved for this class, but the intuition is not:</p>
<ol type="1">
<li>Compute the regression residuals (<span class="math inline">\(\hat{y}_i - y_i\)</span>) as usual.</li>
<li>Instead of treating each residual as independent, <strong>sum the residuals within each cluster</strong>.</li>
<li>Compute the variance of these cluster-level sums.</li>
<li>Use this to construct a standard error that reflects the true amount of independent variation in the data.</li>
</ol>
<p>What this means in practice is that your <strong>effective sample size</strong> is closer to the number of clusters (<span class="math inline">\(G\)</span>), not the total number of observations (<span class="math inline">\(N\)</span>). In our simulation, we had <span class="math inline">\(N = 1{,}500\)</span> observations but only <span class="math inline">\(G = 50\)</span> clusters. Naive standard errors acted as if we had 1,500 independent data points. Cluster-robust standard errors recognized that we really only had about 50 independent pieces of information.</p>
</section>
<section id="implementing-cluster-robust-standard-errors-in-r" class="level3" data-number="13.4.8">
<h3 data-number="13.4.8" class="anchored" data-anchor-id="implementing-cluster-robust-standard-errors-in-r"><span class="header-section-number">13.4.8</span> Implementing Cluster-Robust Standard Errors in R</h3>
<p>With the <code>fixest</code> package, cluster-robust standard errors are easy. Instead of using <code>vcov = "HC1"</code>, use the <code>cluster</code> argument and specify the clustering variable:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Naive (incorrect) standard errors</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>model_naive <span class="ot">&lt;-</span> <span class="fu">feols</span>(y <span class="sc">~</span> treatment <span class="sc">|</span> state <span class="sc">+</span> year,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">vcov =</span> <span class="st">"HC1"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> my_data)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Cluster-robust standard errors (correct for state-level clustering)</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>model_cluster <span class="ot">&lt;-</span> <span class="fu">feols</span>(y <span class="sc">~</span> treatment <span class="sc">|</span> state <span class="sc">+</span> year,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>                       <span class="at">cluster =</span> <span class="st">"state"</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> my_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>For the ACA expansion example, since the policy is set at the state level, we cluster at the state level:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cluster-robust standard errors for the ACA DiD</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>did_crse <span class="ot">&lt;-</span> <span class="fu">feols</span>(uninsured_rate <span class="sc">~</span> treat_active <span class="sc">|</span> state_id <span class="sc">+</span> year,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">cluster =</span> <span class="st">"state_id"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> panel_data)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(did_crse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: uninsured_rate
Observations: 1,800
Fixed-effects: state_id: 200,  year: 9
Standard-errors: Clustered (state_id) 
             Estimate Std. Error  t value  Pr(&gt;|t|)    
treat_active -10.9088   0.564271 -19.3325 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 2.69942     Adj. R2: 0.814526
                Within R2: 0.460845</code></pre>
</div>
</div>
<p>Notice that the coefficient is unchanged (clustering does not affect the point estimate), but the standard error is larger than it would be with naive standard errors, leading to a wider confidence interval and a larger p-value.</p>
</section>
<section id="choosing-the-right-cluster-level" class="level3" data-number="13.4.9">
<h3 data-number="13.4.9" class="anchored" data-anchor-id="choosing-the-right-cluster-level"><span class="header-section-number">13.4.9</span> Choosing the Right Cluster Level</h3>
<p>A common question is: what should I cluster on? The answer is not always obvious, and reasonable people sometimes disagree. The general rule is:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Rule of Thumb: Cluster at the Level of Treatment Assignment
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cluster your standard errors at the level where treatment varies. If policies are set at the state level, cluster by state. If a program is implemented at the school level, cluster by school. If an intervention targets individual patients within hospitals, you might cluster at the hospital level.</p>
</div>
</div>
<p>Some additional considerations:</p>
<ul>
<li>You generally need a reasonable number of clusters (at least 30-50) for the cluster-robust standard errors to work well. With very few clusters, they can be unreliable.</li>
<li>When in doubt, cluster at a broader level rather than a narrower one. Clustering at the state level when you could cluster at the county level is conservative—it gives you larger standard errors, which is the safer error.</li>
<li>In some settings, there may be good reasons to cluster at a different level than treatment assignment (e.g., if you believe there is spatial correlation across states). But treatment-level clustering is the default starting point.</li>
</ul>
</section>
</section>
<section id="summary" class="level2" data-number="13.5">
<h2 data-number="13.5" class="anchored" data-anchor-id="summary"><span class="header-section-number">13.5</span> Summary</h2>
<p>This chapter covered three extensions to the basic DiD framework that come up constantly in applied work.</p>
<p><strong>Choosing good controls</strong> is the foundation of any DiD analysis. Researchers can draw on institutional knowledge (border discontinuity designs, natural comparison groups) or use data-driven methods like propensity score weighting to build a better counterfactual. The key is that your control group must be on a similar trajectory to your treated group before the policy—otherwise, your estimate will be biased.</p>
<p><strong>IPW-DiD</strong> formalizes the data-driven approach by reweighting control units based on their predicted probability of treatment. Control units that resemble treated units on observables get high weights; dissimilar controls get low weights. The method is easy to implement (logistic regression <span class="math inline">\(\rightarrow\)</span> compute weights <span class="math inline">\(\rightarrow\)</span> weighted TWFE) but only corrects for the confounders you include in the propensity score model.</p>
<p><strong>Dynamic DiD and event studies</strong> let treatment effects vary over time and provide a built-in diagnostic for the parallel trends assumption. Pre-treatment coefficients near zero support the design; significant pre-treatment “effects” are a red flag. Event study plots are the standard way to present these results.</p>
<p><strong>Cluster-robust standard errors</strong> correct for correlated errors within groups. Without them, standard OLS inference in panel data produces standard errors that are too small, inflating the Type I error rate far beyond the intended 5%. The fix is simple in <code>fixest</code>: use the <code>cluster</code> argument and cluster at the level of treatment assignment.</p>
</section>
<section id="check-your-understanding" class="level2" data-number="13.6">
<h2 data-number="13.6" class="anchored" data-anchor-id="check-your-understanding"><span class="header-section-number">13.6</span> Check Your Understanding</h2>
<p>For each question below, select the best answer from the dropdown menu.</p>
<div class="question">
<div class="answer-row">
    <label>i. In IPW-DiD, control units with high propensity scores receive ______ weights. </label>
    <select onchange="checkAnswer(this, 'b')">
        <option value="">-- Select Answer --</option>
        <option value="a">Lower</option>
        <option value="b">Higher</option>
        <option value="c">Equal</option>
        <option value="d">Zero</option>
    </select>
</div>

<div class="answer-row">
    <label>ii. Why do we typically omit k = −1 in dynamic DiD? </label>
    <select onchange="checkAnswer(this, 'c')">
        <option value="">-- Select Answer --</option>
        <option value="a">Because there's no data for that period</option>
        <option value="b">Because the treatment effect is largest then</option>
        <option value="c">To serve as the reference category for interpreting other coefficients</option>
        <option value="d">Because parallel trends always holds at k = -1</option>
    </select>
</div>

<div class="answer-row">
    <label>iii. In an event study plot, what do pre-treatment coefficients (k &lt; -1) test? </label>
    <select onchange="checkAnswer(this, 'a')">
        <option value="">-- Select Answer --</option>
        <option value="a">The parallel trends assumption</option>
        <option value="b">The size of the treatment effect</option>
        <option value="c">Whether the policy was implemented correctly</option>
        <option value="d">The statistical power of the study</option>
    </select>
</div>

<div class="answer-row">
    <label>iv. What happens to standard errors if we ignore clustering in panel data? </label>
    <select onchange="checkAnswer(this, 'b')">
        <option value="">-- Select Answer --</option>
        <option value="a">They become too large (conservative)</option>
        <option value="b">They become too small (overconfident)</option>
        <option value="c">They are unbiased</option>
        <option value="d">They become negative</option>
    </select>
</div>

<div class="answer-row">
    <label>v. At what level should you cluster standard errors when studying state-level minimum wage policies? </label>
    <select onchange="checkAnswer(this, 'd')">
        <option value="">-- Select Answer --</option>
        <option value="a">Individual worker level</option>
        <option value="b">Firm level</option>
        <option value="c">Industry level</option>
        <option value="d">State level</option>
    </select>
</div>

<div class="answer-row">
    <label>vi. <strong>(Challenge)</strong> If your event study shows significant negative coefficients at k = -3 and k = -2, what should you conclude? </label>
    <select onchange="checkAnswer(this, 'c')">
        <option value="">-- Select Answer --</option>
        <option value="a">The treatment has anticipation effects</option>
        <option value="b">The treatment effect is very large</option>
        <option value="c">Parallel trends is likely violated; the control group may be invalid</option>
        <option value="d">You need more post-treatment periods</option>
    </select>
</div>
</div>

<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Show Explanation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="i">
<li><p>Control units with high propensity scores (high predicted probability of being treated) but who weren’t actually treated receive <strong>higher</strong> weights. The IPW formula gives them weight <span class="math inline">\(= \hat{P}/(1-\hat{P})\)</span>, which increases as <span class="math inline">\(\hat{P}\)</span> gets larger. The intuition is that these units are most similar to treated units on observables, making them better comparisons.</p></li>
<li><p>We need to omit one period to avoid perfect collinearity (similar to the dummy variable trap). We choose <span class="math inline">\(k = -1\)</span> because it is the natural baseline: all other coefficients are then interpreted as the treatment effect relative to the period immediately before treatment.</p></li>
<li><p>Pre-treatment coefficients serve as a <strong>placebo test</strong>. If we find large, statistically significant “effects” before the policy was implemented, it means treated and control groups were already diverging—contradicting the parallel trends assumption and casting doubt on the entire analysis.</p></li>
<li><p>When observations within clusters are correlated, naive standard errors treat them as independent and underestimate the true uncertainty. This produces standard errors that are too small, t-statistics that are too large, p-values that are too small, and confidence intervals that are too narrow—leading to excessive false positives.</p></li>
<li><p>The rule is to cluster at the level of treatment assignment. Minimum wage policies are set at the state level, so you cluster by state. This accounts for the correlation in outcomes among all workers within the same state who share the same policy environment.</p></li>
<li><p>Significant pre-treatment effects are a major red flag. They indicate that treated and control groups were on different trajectories <em>before</em> the policy, which means any post-treatment difference could reflect pre-existing trends rather than the policy’s causal effect. This calls the entire DiD design into question, and the researcher should consider finding better controls (e.g., through IPW) or using a different identification strategy.</p></li>
</ol>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/did.html" class="pagination-link" aria-label="Difference-in-Differences">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Difference-in-Differences</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/instrumental_variables.html" class="pagination-link" aria-label="Instrumental Variables">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Instrumental Variables</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><span class="faux-block"> © 2025 Raymond Caraher. All rights reserved. </span></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>