<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Multivariate Regression – EC325 Lecture Notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/statistical_inference.html" rel="next">
<link href="../chapters/bivariate_ols.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/multivariate_ols.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Multivariate Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">EC325 Lecture Notes</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../EC325-Lecture-Notes.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../EC325-Lecture-Notes.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/data_practices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Good Data Practices</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/rcts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Causality and Randomized Control Trials</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bivariate_ols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bivariate Regression and Ordinary Least Squares</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/multivariate_ols.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Multivariate Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/statistical_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/dummies_nonlins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dummy Variables and Non-Linear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/interaction_effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Interaction Effects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/heteroskedasticity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Heteroskedasticity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/binary_outcomes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Binary Outcomes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/panel_fe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Panel Data and Fixed Effects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/did.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Difference-in-Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/advanced_did.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Advanced Difference-in-Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/instrumental_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Instrumental Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/rdd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Regression Discontinuity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/putting_it_all_together.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Putting It All Together</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/installingR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Intro to R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/statsreview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Statistics and Probability Review</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/working_with_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Files, Folders, and Working with Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/r_reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">R Functions and Packages Reference</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-problem-with-bivariate-ols" id="toc-the-problem-with-bivariate-ols" class="nav-link active" data-scroll-target="#the-problem-with-bivariate-ols"><span class="header-section-number">5.1</span> The Problem with Bivariate OLS</a></li>
  <li><a href="#the-multivariate-solution" id="toc-the-multivariate-solution" class="nav-link" data-scroll-target="#the-multivariate-solution"><span class="header-section-number">5.2</span> The Multivariate Solution</a>
  <ul class="collapse">
  <li><a href="#the-general-multivariate-model" id="toc-the-general-multivariate-model" class="nav-link" data-scroll-target="#the-general-multivariate-model"><span class="header-section-number">5.2.1</span> The General Multivariate Model</a></li>
  <li><a href="#interpreting-coefficients" id="toc-interpreting-coefficients" class="nav-link" data-scroll-target="#interpreting-coefficients"><span class="header-section-number">5.2.2</span> Interpreting Coefficients</a></li>
  <li><a href="#the-zero-conditional-mean-assumption" id="toc-the-zero-conditional-mean-assumption" class="nav-link" data-scroll-target="#the-zero-conditional-mean-assumption"><span class="header-section-number">5.2.3</span> The Zero Conditional Mean Assumption</a></li>
  </ul></li>
  <li><a href="#deriving-the-multivariate-ols-estimator" id="toc-deriving-the-multivariate-ols-estimator" class="nav-link" data-scroll-target="#deriving-the-multivariate-ols-estimator"><span class="header-section-number">5.3</span> Deriving the Multivariate OLS Estimator</a>
  <ul class="collapse">
  <li><a href="#the-minimization-problem" id="toc-the-minimization-problem" class="nav-link" data-scroll-target="#the-minimization-problem"><span class="header-section-number">5.3.1</span> The Minimization Problem</a></li>
  <li><a href="#first-order-conditions" id="toc-first-order-conditions" class="nav-link" data-scroll-target="#first-order-conditions"><span class="header-section-number">5.3.2</span> First-Order Conditions</a></li>
  </ul></li>
  <li><a href="#estimating-multivariate-ols-in-r" id="toc-estimating-multivariate-ols-in-r" class="nav-link" data-scroll-target="#estimating-multivariate-ols-in-r"><span class="header-section-number">5.4</span> Estimating Multivariate OLS in R</a>
  <ul class="collapse">
  <li><a href="#example-mpg-horsepower-and-weight" id="toc-example-mpg-horsepower-and-weight" class="nav-link" data-scroll-target="#example-mpg-horsepower-and-weight"><span class="header-section-number">5.4.1</span> Example: MPG, Horsepower, and Weight</a></li>
  <li><a href="#interpreting-the-results" id="toc-interpreting-the-results" class="nav-link" data-scroll-target="#interpreting-the-results"><span class="header-section-number">5.4.2</span> Interpreting the Results</a></li>
  </ul></li>
  <li><a href="#multivariate-ols-as-matching" id="toc-multivariate-ols-as-matching" class="nav-link" data-scroll-target="#multivariate-ols-as-matching"><span class="header-section-number">5.5</span> Multivariate OLS as Matching</a>
  <ul class="collapse">
  <li><a href="#example-the-gender-wage-gap-and-occupation" id="toc-example-the-gender-wage-gap-and-occupation" class="nav-link" data-scroll-target="#example-the-gender-wage-gap-and-occupation"><span class="header-section-number">5.5.1</span> Example: The Gender Wage Gap and Occupation</a></li>
  <li><a href="#the-naive-comparison" id="toc-the-naive-comparison" class="nav-link" data-scroll-target="#the-naive-comparison"><span class="header-section-number">5.5.2</span> The Naive Comparison</a></li>
  <li><a href="#step-1-compute-within-occupation-differences" id="toc-step-1-compute-within-occupation-differences" class="nav-link" data-scroll-target="#step-1-compute-within-occupation-differences"><span class="header-section-number">5.5.3</span> Step 1: Compute Within-Occupation Differences</a></li>
  <li><a href="#step-2-compute-weights" id="toc-step-2-compute-weights" class="nav-link" data-scroll-target="#step-2-compute-weights"><span class="header-section-number">5.5.4</span> Step 2: Compute Weights</a></li>
  <li><a href="#step-3-compute-weighted-average" id="toc-step-3-compute-weighted-average" class="nav-link" data-scroll-target="#step-3-compute-weighted-average"><span class="header-section-number">5.5.5</span> Step 3: Compute Weighted Average</a></li>
  <li><a href="#the-regression-equivalent" id="toc-the-regression-equivalent" class="nav-link" data-scroll-target="#the-regression-equivalent"><span class="header-section-number">5.5.6</span> The Regression Equivalent</a></li>
  <li><a href="#how-ols-weights-the-groups" id="toc-how-ols-weights-the-groups" class="nav-link" data-scroll-target="#how-ols-weights-the-groups"><span class="header-section-number">5.5.7</span> How OLS Weights the Groups</a></li>
  </ul></li>
  <li><a href="#goodness-of-fit-adjusted-r-squared" id="toc-goodness-of-fit-adjusted-r-squared" class="nav-link" data-scroll-target="#goodness-of-fit-adjusted-r-squared"><span class="header-section-number">5.6</span> Goodness-of-Fit: Adjusted R-Squared</a>
  <ul class="collapse">
  <li><a href="#the-problem-with-r-squared" id="toc-the-problem-with-r-squared" class="nav-link" data-scroll-target="#the-problem-with-r-squared"><span class="header-section-number">5.6.1</span> The Problem with R-Squared</a></li>
  <li><a href="#the-adjusted-r-squared" id="toc-the-adjusted-r-squared" class="nav-link" data-scroll-target="#the-adjusted-r-squared"><span class="header-section-number">5.6.2</span> The Adjusted R-Squared</a></li>
  </ul></li>
  <li><a href="#gauss-markov-assumptions-for-multivariate-ols" id="toc-gauss-markov-assumptions-for-multivariate-ols" class="nav-link" data-scroll-target="#gauss-markov-assumptions-for-multivariate-ols"><span class="header-section-number">5.7</span> Gauss-Markov Assumptions for Multivariate OLS</a>
  <ul class="collapse">
  <li><a href="#assumption-1-linear-in-parameters" id="toc-assumption-1-linear-in-parameters" class="nav-link" data-scroll-target="#assumption-1-linear-in-parameters"><span class="header-section-number">5.7.1</span> Assumption 1: Linear in Parameters</a></li>
  <li><a href="#assumption-2-random-sampling" id="toc-assumption-2-random-sampling" class="nav-link" data-scroll-target="#assumption-2-random-sampling"><span class="header-section-number">5.7.2</span> Assumption 2: Random Sampling</a></li>
  <li><a href="#assumption-3-no-perfect-multicollinearity" id="toc-assumption-3-no-perfect-multicollinearity" class="nav-link" data-scroll-target="#assumption-3-no-perfect-multicollinearity"><span class="header-section-number">5.7.3</span> Assumption 3: No Perfect Multicollinearity</a></li>
  <li><a href="#assumption-4-zero-conditional-mean" id="toc-assumption-4-zero-conditional-mean" class="nav-link" data-scroll-target="#assumption-4-zero-conditional-mean"><span class="header-section-number">5.7.4</span> Assumption 4: Zero Conditional Mean</a></li>
  <li><a href="#assumption-5-homoskedasticity" id="toc-assumption-5-homoskedasticity" class="nav-link" data-scroll-target="#assumption-5-homoskedasticity"><span class="header-section-number">5.7.5</span> Assumption 5: Homoskedasticity</a></li>
  </ul></li>
  <li><a href="#unbiasedness-of-multivariate-ols" id="toc-unbiasedness-of-multivariate-ols" class="nav-link" data-scroll-target="#unbiasedness-of-multivariate-ols"><span class="header-section-number">5.8</span> Unbiasedness of Multivariate OLS</a>
  <ul class="collapse">
  <li><a href="#observed-vs.-unobserved-variables" id="toc-observed-vs.-unobserved-variables" class="nav-link" data-scroll-target="#observed-vs.-unobserved-variables"><span class="header-section-number">5.8.1</span> Observed vs.&nbsp;Unobserved Variables</a></li>
  </ul></li>
  <li><a href="#the-omitted-variable-bias-formula" id="toc-the-omitted-variable-bias-formula" class="nav-link" data-scroll-target="#the-omitted-variable-bias-formula"><span class="header-section-number">5.9</span> The Omitted Variable Bias Formula</a>
  <ul class="collapse">
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">5.9.1</span> Setup</a></li>
  <li><a href="#the-ovb-formula" id="toc-the-ovb-formula" class="nav-link" data-scroll-target="#the-ovb-formula"><span class="header-section-number">5.9.2</span> The OVB Formula</a></li>
  <li><a href="#interpreting-the-bias-formula" id="toc-interpreting-the-bias-formula" class="nav-link" data-scroll-target="#interpreting-the-bias-formula"><span class="header-section-number">5.9.3</span> Interpreting the Bias Formula</a></li>
  <li><a href="#example-education-wages-and-ability" id="toc-example-education-wages-and-ability" class="nav-link" data-scroll-target="#example-education-wages-and-ability"><span class="header-section-number">5.9.4</span> Example: Education, Wages, and Ability</a></li>
  <li><a href="#example-policing-crime-and-poverty" id="toc-example-policing-crime-and-poverty" class="nav-link" data-scroll-target="#example-policing-crime-and-poverty"><span class="header-section-number">5.9.5</span> Example: Policing, Crime, and Poverty</a></li>
  <li><a href="#example-study-hours-course-difficulty-and-gpa" id="toc-example-study-hours-course-difficulty-and-gpa" class="nav-link" data-scroll-target="#example-study-hours-course-difficulty-and-gpa"><span class="header-section-number">5.9.6</span> Example: Study Hours, Course Difficulty, and GPA</a></li>
  </ul></li>
  <li><a href="#variance-in-multivariate-ols" id="toc-variance-in-multivariate-ols" class="nav-link" data-scroll-target="#variance-in-multivariate-ols"><span class="header-section-number">5.10</span> Variance in Multivariate OLS</a>
  <ul class="collapse">
  <li><a href="#what-increases-variance" id="toc-what-increases-variance" class="nav-link" data-scroll-target="#what-increases-variance"><span class="header-section-number">5.10.1</span> What Increases Variance?</a></li>
  <li><a href="#estimating-sigma2-from-the-data" id="toc-estimating-sigma2-from-the-data" class="nav-link" data-scroll-target="#estimating-sigma2-from-the-data"><span class="header-section-number">5.10.2</span> Estimating <span class="math inline">\(\sigma^2\)</span> from the Data</a></li>
  <li><a href="#from-hatsigma2-to-the-standard-error" id="toc-from-hatsigma2-to-the-standard-error" class="nav-link" data-scroll-target="#from-hatsigma2-to-the-standard-error"><span class="header-section-number">5.10.3</span> From <span class="math inline">\(\hat{\sigma}^2\)</span> to the Standard Error</a></li>
  <li><a href="#simulation-does-hatsigma2-actually-work" id="toc-simulation-does-hatsigma2-actually-work" class="nav-link" data-scroll-target="#simulation-does-hatsigma2-actually-work"><span class="header-section-number">5.10.4</span> Simulation: Does <span class="math inline">\(\hat{\sigma}^2\)</span> Actually Work?</a></li>
  </ul></li>
  <li><a href="#the-bias-variance-tradeoff" id="toc-the-bias-variance-tradeoff" class="nav-link" data-scroll-target="#the-bias-variance-tradeoff"><span class="header-section-number">5.11</span> The Bias-Variance Tradeoff</a>
  <ul class="collapse">
  <li><a href="#the-costs-of-omitting-a-relevant-variable" id="toc-the-costs-of-omitting-a-relevant-variable" class="nav-link" data-scroll-target="#the-costs-of-omitting-a-relevant-variable"><span class="header-section-number">5.11.1</span> The Costs of Omitting a Relevant Variable</a></li>
  <li><a href="#the-costs-of-including-an-irrelevant-variable" id="toc-the-costs-of-including-an-irrelevant-variable" class="nav-link" data-scroll-target="#the-costs-of-including-an-irrelevant-variable"><span class="header-section-number">5.11.2</span> The Costs of Including an Irrelevant Variable</a></li>
  <li><a href="#the-tradeoff" id="toc-the-tradeoff" class="nav-link" data-scroll-target="#the-tradeoff"><span class="header-section-number">5.11.3</span> The Tradeoff</a></li>
  <li><a href="#practical-guidance" id="toc-practical-guidance" class="nav-link" data-scroll-target="#practical-guidance"><span class="header-section-number">5.11.4</span> Practical Guidance</a></li>
  </ul></li>
  <li><a href="#simulation-bias-vs.-variance" id="toc-simulation-bias-vs.-variance" class="nav-link" data-scroll-target="#simulation-bias-vs.-variance"><span class="header-section-number">5.12</span> Simulation: Bias vs.&nbsp;Variance</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">5.13</span> Summary</a>
  <ul class="collapse">
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways"><span class="header-section-number">5.13.1</span> Key Takeaways</a></li>
  </ul></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding"><span class="header-section-number">5.14</span> Check Your Understanding</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-multivariate" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Multivariate Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>



<style>
.problem {
    background-color: #f8f9fa;
    border: 1px solid #dee2e6;
    border-radius: 8px;
    padding: 20px;
    margin: 20px 0;
}
.context {
    background-color: #e8f4f8;
    padding: 12px;
    border-radius: 5px;
    margin-bottom: 15px;
    border-left: 4px solid #2874a6;
}
.question {
    margin: 15px 0;
    padding: 10px;
    background-color: #fff3cd;
    border-radius: 5px;
}
.answer-row {
    display: flex;
    align-items: center;
    margin: 10px 0;
    flex-wrap: wrap;
    gap: 10px;
}
.answer-row label {
    min-width: 320px;
    font-weight: 500;
}
select {
    padding: 8px 12px;
    font-size: 14px;
    border: 2px solid #ccc;
    border-radius: 5px;
    min-width: 300px;
    cursor: pointer;
}
select:focus {
    border-color: #2874a6;
    outline: none;
}
.correct {
    border-color: #28a745 !important;
    background-color: #d4edda !important;
}
.incorrect {
    border-color: #dc3545 !important;
    background-color: #f8d7da !important;
}
.explanation {
    margin-top: 10px;
    padding: 15px;
    background-color: #e7f3ff;
    border-radius: 5px;
    border-left: 4px solid #2874a6;
}
.note {
    font-size: 0.85em;
    color: #666;
    font-style: italic;
}
</style>

<script>
function checkAnswer(selectElement, correctValue) {
    if (selectElement.value === '') {
        selectElement.classList.remove('correct', 'incorrect');
    } else if (selectElement.value === correctValue) {
        selectElement.classList.remove('incorrect');
        selectElement.classList.add('correct');
    } else {
        selectElement.classList.remove('correct');
        selectElement.classList.add('incorrect');
    }
}
</script>

<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>Key Questions</strong>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Why do we need multivariate regression?</li>
<li>How do we interpret coefficients when there are multiple independent variables?</li>
<li>What is the zero conditional mean assumption in the multivariate case?</li>
<li>How does multivariate OLS function as a “matching” estimator?</li>
<li>What is the omitted variable bias formula and how do we use it?</li>
<li>What is the bias-variance tradeoff when deciding which controls to include?</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>Suggested Readings</strong>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><span class="citation" data-cites="wooldridge_introductory_2019">Wooldridge (<a href="references.html#ref-wooldridge_introductory_2019" role="doc-biblioref">2019</a>)</span>, Ch. 3</li>
</ul>
</div>
</div>
</div>
<p>In <a href="bivariate_ols.html" class="quarto-xref"><span>Chapter 4</span></a>, we introduced bivariate OLS and saw that causal interpretation requires the zero conditional mean assumption: <span class="math inline">\(E[\mu | x] = 0\)</span>. We also saw that this assumption is <em>very</em> difficult to justify.</p>
<p>This chapter introduces <strong>multivariate OLS</strong>, which allows us to explicitly control for confounding variables. By including additional variables on the right-hand side of our regression, we can make the zero conditional mean assumption more plausible and get closer to causal estimates.</p>
<section id="the-problem-with-bivariate-ols" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="the-problem-with-bivariate-ols"><span class="header-section-number">5.1</span> The Problem with Bivariate OLS</h2>
<p>Let’s revisit why bivariate OLS often fails to give us causal estimates.</p>
<p>Consider a regression of wages on education:</p>
<p><span class="math display">\[
wage = \beta_0 + \beta_1 \cdot educ + \mu
\]</span></p>
<p>For <span class="math inline">\(\hat{\beta}_1\)</span> to be an unbiased estimate of the causal effect of education, we need <span class="math inline">\(E[\mu | educ] = 0\)</span>. But the error term <span class="math inline">\(\mu\)</span> contains everything else that affects wages: ability, family connections, motivation, and countless other factors.</p>
<p>Many of these factors are likely correlated with education. For example, people from wealthier families tend to get more education (better schools, tutors, college is affordable) <em>and</em> earn higher wages (family connections, inherited wealth). If family income is in <span class="math inline">\(\mu\)</span> and correlated with education, then <span class="math inline">\(E[\mu | educ] \neq 0\)</span>, and our estimate is biased.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The Core Problem
</div>
</div>
<div class="callout-body-container callout-body">
<p>With bivariate OLS, the zero conditional mean assumption requires that <em>all</em> factors affecting <span class="math inline">\(y\)</span> (other than <span class="math inline">\(x\)</span>) be uncorrelated with <span class="math inline">\(x\)</span>. This is almost never plausible in observational data.</p>
</div>
</div>
</section>
<section id="the-multivariate-solution" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="the-multivariate-solution"><span class="header-section-number">5.2</span> The Multivariate Solution</h2>
<p>Multivariate OLS offers a solution: <strong>explicitly control</strong> for variables that might be confounders.</p>
<p>If we’re worried that family income confounds the education-wage relationship, we can include it in our population regression model by simply adding additional right-hand side, independent variables:</p>
<p><span class="math display">\[
wage = \beta_0 + \beta_1 \cdot educ + \beta_2 \cdot family\_income + \mu
\]</span></p>
<p>Now <span class="math inline">\(\beta_1\)</span> represents the effect of education on wages <strong>holding family income constant</strong>. The error term <span class="math inline">\(\mu\)</span> no longer contains family income, so that specific source of bias is eliminated.</p>
<section id="the-general-multivariate-model" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="the-general-multivariate-model"><span class="header-section-number">5.2.1</span> The General Multivariate Model</h3>
<p>If we are worried about additional sources of omitted variable bias (as we probably should be), it is easy to expand our regression model and include even more control variables.</p>
<p>The general multivariate linear regression model with <span class="math inline">\(k\)</span> independent variables is:</p>
<p><span id="eq-multivariate"><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_k x_k + \mu
\tag{5.1}\]</span></span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(y\)</span> is the dependent variable</li>
<li><span class="math inline">\(x_1, x_2, \ldots, x_k\)</span> are the independent/control variables</li>
<li><span class="math inline">\(\beta_0\)</span> is the intercept</li>
<li><span class="math inline">\(\beta_j\)</span> is the coefficient on <span class="math inline">\(x_j\)</span> (for <span class="math inline">\(j = 1, 2, \ldots, k\)</span>)</li>
<li><span class="math inline">\(\mu\)</span> is the error term containing all factors not included in the model</li>
</ul>
</section>
<section id="interpreting-coefficients" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="interpreting-coefficients"><span class="header-section-number">5.2.2</span> Interpreting Coefficients</h3>
<p>In multivariate regression, each coefficient has a <strong>ceteris paribus</strong> interpretation:</p>
<p><span class="math display">\[
\beta_j = \frac{\partial y}{\partial x_j}
\]</span></p>
<p>This is the change in <span class="math inline">\(y\)</span> associated with a one-unit increase in <span class="math inline">\(x_j\)</span>, <strong>holding all other independent variables constant</strong>.</p>
<p>For example, in the model:</p>
<p><span class="math display">\[
wage = \beta_0 + \beta_1 \cdot educ + \beta_2 \cdot family\_income + \mu
\]</span></p>
<ul>
<li><span class="math inline">\(\beta_1\)</span>: The change in wages for one additional year of education, <strong>holding family income constant</strong></li>
<li><span class="math inline">\(\beta_2\)</span>: The change in wages for one additional dollar of family income, <strong>holding education constant</strong></li>
</ul>
</section>
<section id="the-zero-conditional-mean-assumption" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="the-zero-conditional-mean-assumption"><span class="header-section-number">5.2.3</span> The Zero Conditional Mean Assumption</h3>
<p>In multivariate OLS, the zero conditional mean assumption becomes:</p>
<p><span class="math display">\[
E[\mu | x_1, x_2, \ldots, x_k] = 0
\]</span></p>
<p>This states that the average of unobserved factors is zero for <em>all unique combinations</em> of the independent variables. In particular, nothing in <span class="math inline">\(\mu\)</span> can be correlated with <em>any</em> of the variables we’ve included.</p>
<p>This assumption is much more plausible than its bivariate counterpart. By including relevant control variables, we’ve removed them from <span class="math inline">\(\mu\)</span>, making it more likely that what remains is uncorrelated with our variables of interest. We will discuss this more below.</p>
</section>
</section>
<section id="deriving-the-multivariate-ols-estimator" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="deriving-the-multivariate-ols-estimator"><span class="header-section-number">5.3</span> Deriving the Multivariate OLS Estimator</h2>
<p>The derivation follows the same logic as bivariate OLS: we minimize the sum of squared residuals.</p>
<section id="the-minimization-problem" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="the-minimization-problem"><span class="header-section-number">5.3.1</span> The Minimization Problem</h3>
<p>Given a sample of <span class="math inline">\(n\)</span> observations, we want to find values <span class="math inline">\(\hat{\beta}_0, \hat{\beta}_1, \ldots, \hat{\beta}_k\)</span> that minimize:</p>
<p><span class="math display">\[
SSR = \sum_{i=1}^{n} (y_i - \hat{\beta}_0 - \hat{\beta}_1 x_{1i} - \hat{\beta}_2 x_{2i} - \cdots - \hat{\beta}_k x_{ki})^2
\]</span></p>
</section>
<section id="first-order-conditions" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="first-order-conditions"><span class="header-section-number">5.3.2</span> First-Order Conditions</h3>
<p>Taking partial derivatives with respect to each <span class="math inline">\(\hat{\beta}_j\)</span> and setting them equal to zero yields <span class="math inline">\(k + 1\)</span> first-order conditions:</p>
<p><span class="math display">\[
\sum_{i=1}^{n}(y_i - \hat{\beta}_0 - \hat{\beta}_1 x_{1i} - \cdots - \hat{\beta}_k x_{ki}) = 0
\]</span></p>
<p><span class="math display">\[
\sum_{i=1}^{n} x_{1i}(y_i - \hat{\beta}_0 - \hat{\beta}_1 x_{1i} - \cdots - \hat{\beta}_k x_{ki}) = 0
\]</span></p>
<p><span class="math display">\[
\vdots
\]</span></p>
<p><span class="math display">\[
\sum_{i=1}^{n} x_{ki}(y_i - \hat{\beta}_0 - \hat{\beta}_1 x_{1i} - \cdots - \hat{\beta}_k x_{ki}) = 0
\]</span></p>
<p>Solving this system of equations yields the OLS estimates. The algebra is tedious (and typically handled with matrix methods), so we won’t derive the explicit formulas here. Fortunately, your computer does this effortlessly.</p>
</section>
</section>
<section id="estimating-multivariate-ols-in-r" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="estimating-multivariate-ols-in-r"><span class="header-section-number">5.4</span> Estimating Multivariate OLS in R</h2>
<p>In R, we estimate multivariate regression using the same <code>lm()</code> function, simply adding variables with the <code>+</code> symbol.</p>
<section id="example-mpg-horsepower-and-weight" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="example-mpg-horsepower-and-weight"><span class="header-section-number">5.4.1</span> Example: MPG, Horsepower, and Weight</h3>
<p>Let’s estimate the effect of horsepower on fuel efficiency, first without and then with a control for vehicle weight.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Bivariate regression</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>lm_bivariate <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> mtcars)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Multivariate regression (adding weight as control)</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>lm_multivariate <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp <span class="sc">+</span> wt, <span class="at">data =</span> mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Bivariate results:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_bivariate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.7121 -2.1122 -0.8854  1.5819  8.2360 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 30.09886    1.63392  18.421  &lt; 2e-16 ***
hp          -0.06823    0.01012  -6.742 1.79e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.863 on 30 degrees of freedom
Multiple R-squared:  0.6024,    Adjusted R-squared:  0.5892 
F-statistic: 45.46 on 1 and 30 DF,  p-value: 1.788e-07</code></pre>
</div>
</div>
<p><strong>Multivariate results:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_multivariate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp + wt, data = mtcars)

Residuals:
   Min     1Q Median     3Q    Max 
-3.941 -1.600 -0.182  1.050  5.854 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 37.22727    1.59879  23.285  &lt; 2e-16 ***
hp          -0.03177    0.00903  -3.519  0.00145 ** 
wt          -3.87783    0.63273  -6.129 1.12e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.593 on 29 degrees of freedom
Multiple R-squared:  0.8268,    Adjusted R-squared:  0.8148 
F-statistic: 69.21 on 2 and 29 DF,  p-value: 9.109e-12</code></pre>
</div>
</div>
</section>
<section id="interpreting-the-results" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="interpreting-the-results"><span class="header-section-number">5.4.2</span> Interpreting the Results</h3>
<p>In the <strong>bivariate</strong> regression, the coefficient on horsepower is <span class="math inline">\(-0.068\)</span>: each additional unit of horsepower is associated with 0.068 fewer miles per gallon.</p>
<p>In the <strong>multivariate</strong> regression (controlling for weight), the coefficient on horsepower drops to <span class="math inline">\(-0.032\)</span>—less than half the size!</p>
<p>What happened? Horsepower and weight are positively correlated (more powerful engines tend to be in heavier vehicles), and weight independently reduces fuel efficiency. The bivariate estimate was conflating the effect of horsepower with the effect of weight. Once we control for weight, we remove the part of the bivariate relationship that was really about weight. (Other differences between cars could still be confounding the estimate—more on that below.)</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What Changed?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The coefficient on <code>hp</code> dropped from <span class="math inline">\(-0.068\)</span> to <span class="math inline">\(-0.032\)</span> when we added <code>wt</code>. This suggests that much of what appeared to be the “effect” of horsepower was actually the effect of weight. This is what controlling for a confounder does: it takes that variable out of the comparison.</p>
</div>
</div>
</section>
</section>
<section id="multivariate-ols-as-matching" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="multivariate-ols-as-matching"><span class="header-section-number">5.5</span> Multivariate OLS as Matching</h2>
<p>What is actually happening “under the hood” when we say we want to “control” for a given variable?</p>
<p>There’s an intuitive way to understand what multivariate OLS does: it’s essentially a <strong>matching</strong> estimator. When we “control for” a variable <span class="math inline">\(x_2\)</span>, we compare observations that have different values of <span class="math inline">\(x_1\)</span> but similar values of <span class="math inline">\(x_2\)</span>. In other words, we compare like with like.</p>
<section id="example-the-gender-wage-gap-and-occupation" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="example-the-gender-wage-gap-and-occupation"><span class="header-section-number">5.5.1</span> Example: The Gender Wage Gap and Occupation</h3>
<p>Suppose we want to measure the gender wage gap. A simple comparison of average wages for men and women might be misleading if men and women tend to work in occupations that pay differently.</p>
<p>Let’s work through this with simulated data to see exactly how controlling for occupation works. Specifically, let’s create an imaginary population of 2,000 workers where:</p>
<ol type="1">
<li>About half of workers are women</li>
<li>Every worker has either an office job or a manual job, and women are more likely to work in office jobs (70% of women vs.&nbsp;40% of men)</li>
<li>The “true” population regression model is:</li>
</ol>
<p><span class="math display">\[
wage = 30000 - 5000 \cdot female + 20000 \cdot office + \mu
\]</span></p>
<p>where <span class="math inline">\(\mu\)</span> is random noise with a standard deviation of $6,000.</p>
<p>So, holding occupation constant, women earn $5,000 less than men, and office jobs pay a $20,000 premium over manual jobs.</p>
<div class="cell">
<details class="code-fold">
<summary>Code: Simulated Population Data</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate wage data</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">2000</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>wage_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># About half of workers are women</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">female =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), n, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Women are more likely to work in (higher-paying) office jobs</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">office =</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="at">prob =</span> <span class="fu">ifelse</span>(female <span class="sc">==</span> <span class="dv">1</span>, <span class="fl">0.70</span>, <span class="fl">0.40</span>)),</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Wages depend on gender AND occupation</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">wage   =</span> <span class="dv">30000</span> <span class="sc">-</span> <span class="dv">5000</span> <span class="sc">*</span> female <span class="sc">+</span> <span class="dv">20000</span> <span class="sc">*</span> office <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">6000</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gender =</span> <span class="fu">ifelse</span>(female <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Female"</span>, <span class="st">"Male"</span>),</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">occupation =</span> <span class="fu">ifelse</span>(office <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Office"</span>, <span class="st">"Manual"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="the-naive-comparison" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="the-naive-comparison"><span class="header-section-number">5.5.2</span> The Naive Comparison</h3>
<p>First, let’s compare average wages for men and women without any controls:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>naive_means <span class="ot">&lt;-</span> wage_data <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gender) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_wage =</span> <span class="fu">mean</span>(wage), <span class="at">n =</span> <span class="fu">n</span>())</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>naive_means <span class="sc">|&gt;</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Gender"</span>, <span class="st">"Avg Wage ($)"</span>, <span class="st">"N"</span>),</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">0</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Gender</th>
<th style="text-align: right;">Avg Wage ($)</th>
<th style="text-align: right;">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Female</td>
<td style="text-align: right;">38,521</td>
<td style="text-align: right;">983</td>
</tr>
<tr class="even">
<td style="text-align: left;">Male</td>
<td style="text-align: right;">38,534</td>
<td style="text-align: right;">1,017</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The naive comparison suggests there is almost no gender wage gap at all: the difference in average wages (women minus men) is only -13 dollars.</p>
<p>But wait! We built a $5,000 wage penalty for women into our simulation. Why doesn’t it show up?</p>
<p>Because women are much more likely to work in office jobs, and office jobs pay $20,000 more. The office premium that women disproportionately receive offsets the wage penalty they face <em>within</em> each occupation, so the naive comparison <strong>understates</strong> the gap. By failing to account for the fact that some occupations simply pay more than others, our simple comparison mixes up the gender gap with the occupation premium.</p>
<p>We can also see this in the results if we run a simple bivariate regression:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>lm_naive <span class="ot">&lt;-</span> <span class="fu">lm</span>(wage <span class="sc">~</span> female, <span class="at">data =</span> wage_data)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_naive)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wage ~ female, data = wage_data)

Residuals:
   Min     1Q Median     3Q    Max 
-30492  -9431   1031   9137  32291 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 38534.08     360.86 106.785   &lt;2e-16 ***
female        -13.36     514.72  -0.026    0.979    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11510 on 1998 degrees of freedom
Multiple R-squared:  3.371e-07, Adjusted R-squared:  -0.0005002 
F-statistic: 0.0006736 on 1 and 1998 DF,  p-value: 0.9793</code></pre>
</div>
</div>
<p>With a single dummy variable on the right-hand side, the coefficient on <code>female</code> is exactly the difference in average wages between women and men—the same naive gap as above.</p>
</section>
<section id="step-1-compute-within-occupation-differences" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="step-1-compute-within-occupation-differences"><span class="header-section-number">5.5.3</span> Step 1: Compute Within-Occupation Differences</h3>
<p>To control for occupation, we compare men and women <strong>within</strong> each occupation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>within_diffs <span class="ot">&lt;-</span> wage_data <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(occupation) <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">male_wage   =</span> <span class="fu">mean</span>(wage[gender <span class="sc">==</span> <span class="st">"Male"</span>]),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">female_wage =</span> <span class="fu">mean</span>(wage[gender <span class="sc">==</span> <span class="st">"Female"</span>]),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">gap         =</span> female_wage <span class="sc">-</span> male_wage,   <span class="co"># gender gap within each occupation</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n           =</span> <span class="fu">n</span>()</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>within_diffs <span class="sc">|&gt;</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Occupation"</span>, <span class="st">"Male Avg ($)"</span>, <span class="st">"Female Avg ($)"</span>, <span class="st">"Gap (F - M)"</span>, <span class="st">"N"</span>),</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">0</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-matching-detailed" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-matching-detailed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.1: Average wages by gender within each occupation
</figcaption>
<div aria-describedby="tbl-matching-detailed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Occupation</th>
<th style="text-align: right;">Male Avg (<span class="math inline">\()| Female Avg (\)</span>)</th>
<th style="text-align: right;">Gap (F - M)</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Manual</td>
<td style="text-align: right;">29,842</td>
<td style="text-align: right;">24,604</td>
<td style="text-align: right;">-5,237</td>
<td style="text-align: right;">894</td>
</tr>
<tr class="even">
<td style="text-align: left;">Office</td>
<td style="text-align: right;">50,258</td>
<td style="text-align: right;">44,931</td>
<td style="text-align: right;">-5,327</td>
<td style="text-align: right;">1,106</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Notice that within each occupation, the gap is close to the true value: women earn $5,237 less than men among manual workers and $5,327 less among office workers.</p>
</section>
<section id="step-2-compute-weights" class="level3" data-number="5.5.4">
<h3 data-number="5.5.4" class="anchored" data-anchor-id="step-2-compute-weights"><span class="header-section-number">5.5.4</span> Step 2: Compute Weights</h3>
<p>To combine these within-occupation estimates into a single number, we take a <strong>weighted average</strong>. For our matching estimate, we’ll weight each occupation by its share of workers:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>within_diffs <span class="ot">&lt;-</span> within_diffs <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weight =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>within_diffs <span class="sc">|&gt;</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(occupation, gap, n, weight) <span class="sc">|&gt;</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Occupation"</span>, <span class="st">"Gap (F - M)"</span>, <span class="st">"N"</span>, <span class="st">"Weight"</span>),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Occupation</th>
<th style="text-align: right;">Gap (F - M)</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Manual</td>
<td style="text-align: right;">-5,237</td>
<td style="text-align: right;">894</td>
<td style="text-align: right;">0.447</td>
</tr>
<tr class="even">
<td style="text-align: left;">Office</td>
<td style="text-align: right;">-5,327</td>
<td style="text-align: right;">1,106</td>
<td style="text-align: right;">0.553</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="step-3-compute-weighted-average" class="level3" data-number="5.5.5">
<h3 data-number="5.5.5" class="anchored" data-anchor-id="step-3-compute-weighted-average"><span class="header-section-number">5.5.5</span> Step 3: Compute Weighted Average</h3>
<p>Now we combine the within-occupation gaps using these weights:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>weighted_estimate <span class="ot">&lt;-</span> <span class="fu">sum</span>(within_diffs<span class="sc">$</span>gap <span class="sc">*</span> within_diffs<span class="sc">$</span>weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The weighted average is:</p>
<p><span class="math display">\[
(-5{,}237 \times 0.447) + (-5{,}327 \times 0.553) = -5{,}287
\]</span></p>
<p>This is very close to the true gap of −$5,000!</p>
</section>
<section id="the-regression-equivalent" class="level3" data-number="5.5.6">
<h3 data-number="5.5.6" class="anchored" data-anchor-id="the-regression-equivalent"><span class="header-section-number">5.5.6</span> The Regression Equivalent</h3>
<p>Now let’s see what regression gives us:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression controlling for occupation</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>lm_ctrl <span class="ot">&lt;-</span> <span class="fu">lm</span>(wage <span class="sc">~</span> female <span class="sc">+</span> office, <span class="at">data =</span> wage_data)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_ctrl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wage ~ female + office, data = wage_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-19056.6  -3954.8    -12.7   3984.1  20591.4 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  29859.3      224.7  132.86   &lt;2e-16 ***
female       -5287.9      280.6  -18.84   &lt;2e-16 ***
office       20374.7      282.1   72.21   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6057 on 1997 degrees of freedom
Multiple R-squared:  0.7231,    Adjusted R-squared:  0.7228 
F-statistic:  2607 on 2 and 1997 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The coefficient on <code>female</code> is about −$5,288—almost exactly our matching estimate, and close to the true value we built into the simulation. Let’s put all three side by side:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="st">"Naive"</span>      <span class="ot">=</span> <span class="fu">unname</span>(<span class="fu">coef</span>(lm_naive)[<span class="st">"female"</span>]),</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Matching"</span>   <span class="ot">=</span> weighted_estimate,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Regression"</span> <span class="ot">=</span> <span class="fu">unname</span>(<span class="fu">coef</span>(lm_ctrl)[<span class="st">"female"</span>]),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Truth"</span>      <span class="ot">=</span> <span class="sc">-</span><span class="dv">5000</span>) <span class="sc">|&gt;</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Naive   Matching Regression      Truth 
       -13      -5287      -5288      -5000 </code></pre>
</div>
</div>
<p>The naive estimate is badly off because women sort into the higher-paying office jobs. Matching and regression both land near the truth.</p>
</section>
<section id="how-ols-weights-the-groups" class="level3" data-number="5.5.7">
<h3 data-number="5.5.7" class="anchored" data-anchor-id="how-ols-weights-the-groups"><span class="header-section-number">5.5.7</span> How OLS Weights the Groups</h3>
<p>Notice that the matching and regression estimates are <em>nearly</em> identical, but not exactly the same. Why?</p>
<p>Our matching estimate weighted each occupation by its share of workers. OLS uses slightly different weights. It weights each group by its size <strong>and</strong> by how much the variable of interest varies within that group:</p>
<p><span class="math display">\[
\text{weight}_g \propto n_g \times Var(female \mid g)
\]</span></p>
<p>The intuition is that a group can only tell us about the gender gap if it contains both men and women. An occupation that is half women and half men is very informative about the gap. An occupation that is 99% men tells us very little, because there are hardly any women to compare against. OLS puts more weight on groups with more variation in the variable of interest.</p>
<p>We can check this directly. For a 0/1 variable, the variance is <span class="math inline">\(p(1-p)\)</span>, where <span class="math inline">\(p\)</span> is the share of observations equal to 1:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ols_weights <span class="ot">&lt;-</span> wage_data <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(occupation) <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">share_female =</span> <span class="fu">mean</span>(female)) <span class="sc">|&gt;</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">var_female =</span> share_female <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> share_female),   <span class="co"># variance of a 0/1 variable</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">ols_weight =</span> n <span class="sc">*</span> var_female <span class="sc">/</span> <span class="fu">sum</span>(n <span class="sc">*</span> var_female)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(<span class="fu">select</span>(within_diffs, occupation, gap, weight), <span class="at">by =</span> <span class="st">"occupation"</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>ols_weights <span class="sc">|&gt;</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(occupation, gap, weight, ols_weight) <span class="sc">|&gt;</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Occupation"</span>, <span class="st">"Gap (F - M)"</span>, <span class="st">"Matching Weight"</span>, <span class="st">"OLS Weight"</span>),</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">3</span>),</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Occupation</th>
<th style="text-align: right;">Gap (F - M)</th>
<th style="text-align: right;">Matching Weight</th>
<th style="text-align: right;">OLS Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Manual</td>
<td style="text-align: right;">-5,237</td>
<td style="text-align: right;">0.447</td>
<td style="text-align: right;">0.435</td>
</tr>
<tr class="even">
<td style="text-align: left;">Office</td>
<td style="text-align: right;">-5,327</td>
<td style="text-align: right;">0.553</td>
<td style="text-align: right;">0.565</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Weighted average using the OLS weights</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(ols_weights<span class="sc">$</span>gap <span class="sc">*</span> ols_weights<span class="sc">$</span>ols_weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -5287.908</code></pre>
</div>
</div>
<p>Using the OLS weights reproduces the regression coefficient exactly. In this example, the two sets of weights are very similar, and the gap is about the same in both occupations, so matching and regression give almost the same answer. If the gap differed a lot across groups, and the variable of interest varied much more in some groups than in others, the two estimates could differ noticeably.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Multivariate OLS as Matching
</div>
</div>
<div class="callout-body-container callout-body">
<p>When you include control variables, OLS is effectively:</p>
<ol type="1">
<li><strong>Grouping</strong> observations by similar values of the control variables</li>
<li><strong>Computing</strong> the relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> within each group</li>
<li><strong>Taking a weighted average</strong> across groups, where each group’s weight depends on its size <em>and</em> on how much <span class="math inline">\(x\)</span> varies within it</li>
</ol>
<p>This is why multivariate regression can sometimes be thought of as a “matching” estimator—we’re matching people who work in the same occupation and then comparing the wages of men and women. The same logic applies if we have multiple control variables, although the grouping gets complicated fast.</p>
</div>
</div>
</section>
</section>
<section id="goodness-of-fit-adjusted-r-squared" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="goodness-of-fit-adjusted-r-squared"><span class="header-section-number">5.6</span> Goodness-of-Fit: Adjusted R-Squared</h2>
<p>In bivariate OLS, we used <span class="math inline">\(R^2\)</span> to measure how much variation in <span class="math inline">\(y\)</span> our model explains. The same concept applies to multivariate OLS, but with an important caveat.</p>
<section id="the-problem-with-r-squared" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="the-problem-with-r-squared"><span class="header-section-number">5.6.1</span> The Problem with R-Squared</h3>
<p>The <span class="math inline">\(R^2\)</span> can never decrease when you add more variables—it can only increase or stay the same. This is because adding variables can only improve (or maintain) the fit, even if those variables are irrelevant.</p>
<p>This creates a problem: <span class="math inline">\(R^2\)</span> mechanically increases as you add more variables, potentially making a bloated model look better than a parsimonious one.</p>
</section>
<section id="the-adjusted-r-squared" class="level3" data-number="5.6.2">
<h3 data-number="5.6.2" class="anchored" data-anchor-id="the-adjusted-r-squared"><span class="header-section-number">5.6.2</span> The Adjusted R-Squared</h3>
<p>The <strong>adjusted R-squared</strong> penalizes for the number of parameters:</p>
<p><span class="math display">\[
\bar{R}^2 = 1 - \frac{(1 - R^2)(n - 1)}{n - k - 1}
\]</span></p>
<p>where <span class="math inline">\(n\)</span> is the sample size and <span class="math inline">\(k\)</span> is the number of independent variables.</p>
<p>The adjusted <span class="math inline">\(R^2\)</span>:</p>
<ul>
<li>Is always smaller than the regular <span class="math inline">\(R^2\)</span></li>
<li>Can decrease when you add irrelevant variables</li>
<li>Provides a better comparison between models with different numbers of variables</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare R-squared and Adjusted R-squared</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Bivariate R-sq"</span> <span class="ot">=</span> <span class="fu">summary</span>(lm_bivariate)<span class="sc">$</span>r.squared,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Bivariate Adj R-sq"</span> <span class="ot">=</span> <span class="fu">summary</span>(lm_bivariate)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Multivariate R-sq"</span> <span class="ot">=</span> <span class="fu">summary</span>(lm_multivariate)<span class="sc">$</span>r.squared,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Multivariate Adj R-sq"</span> <span class="ot">=</span> <span class="fu">summary</span>(lm_multivariate)<span class="sc">$</span>adj.r.squared</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Bivariate R-sq    Bivariate Adj R-sq     Multivariate R-sq 
            0.6024373             0.5891853             0.8267855 
Multivariate Adj R-sq 
            0.8148396 </code></pre>
</div>
</div>
</section>
</section>
<section id="gauss-markov-assumptions-for-multivariate-ols" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="gauss-markov-assumptions-for-multivariate-ols"><span class="header-section-number">5.7</span> Gauss-Markov Assumptions for Multivariate OLS</h2>
<p>The Gauss-Markov assumptions extend naturally to the multivariate case, with one important addition.</p>
<section id="assumption-1-linear-in-parameters" class="level3" data-number="5.7.1">
<h3 data-number="5.7.1" class="anchored" data-anchor-id="assumption-1-linear-in-parameters"><span class="header-section-number">5.7.1</span> Assumption 1: Linear in Parameters</h3>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_k x_k + \mu
\]</span></p>
<p>As in the bivariate case, we can transform variables to model non-linear relationships while maintaining linearity in parameters.</p>
</section>
<section id="assumption-2-random-sampling" class="level3" data-number="5.7.2">
<h3 data-number="5.7.2" class="anchored" data-anchor-id="assumption-2-random-sampling"><span class="header-section-number">5.7.2</span> Assumption 2: Random Sampling</h3>
<p>We have a random sample <span class="math inline">\(\{(x_{1i}, x_{2i}, \ldots, x_{ki}, y_i) : i = 1, \ldots, n\}\)</span> from the population.</p>
</section>
<section id="assumption-3-no-perfect-multicollinearity" class="level3" data-number="5.7.3">
<h3 data-number="5.7.3" class="anchored" data-anchor-id="assumption-3-no-perfect-multicollinearity"><span class="header-section-number">5.7.3</span> Assumption 3: No Perfect Multicollinearity</h3>
<p>This assumption has two parts:</p>
<ol type="1">
<li><strong>No constant variables:</strong> Each independent variable must have some variation in the sample</li>
<li><strong>No exact linear relationships:</strong> No independent variable can be a perfect linear function of other independent variables</li>
</ol>
<p>The second part is new and important in multivariate regression.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Perfect Multicollinearity
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Perfect multicollinearity</strong> occurs when one independent variable is an exact linear combination of others. Examples:</p>
<ul>
<li>Including both <code>family_income</code> and <code>family_income_thousands</code> (one is just the other divided by 1000)</li>
<li>Including <code>parent1_income</code>, <code>parent2_income</code>, and <code>family_income</code> when <code>family_income = parent1_income + parent2_income</code></li>
<li>Including dummy variables for all categories of a categorical variable plus an intercept</li>
</ul>
<p>When perfect multicollinearity exists, the OLS formulas break down (the system of equations has no unique solution). R will drop one of the collinear variables automatically, but <code>lm()</code> does <em>not</em> issue a warning. Instead, the dropped variable’s coefficient is reported as <code>NA</code>, and <code>summary()</code> notes that it was “not defined because of singularities.” Always check your output for <code>NA</code> coefficients.</p>
</div>
</div>
</section>
<section id="assumption-4-zero-conditional-mean" class="level3" data-number="5.7.4">
<h3 data-number="5.7.4" class="anchored" data-anchor-id="assumption-4-zero-conditional-mean"><span class="header-section-number">5.7.4</span> Assumption 4: Zero Conditional Mean</h3>
<p><span class="math display">\[
E[\mu | x_1, x_2, \ldots, x_k] = 0
\]</span></p>
<p>The error term has mean zero for all combinations of the independent variables. This can still fail due to:</p>
<ul>
<li>Omitted variables correlated with included variables</li>
<li>Wrong functional form</li>
<li>Measurement error in independent variables</li>
<li>Simultaneous causality</li>
</ul>
</section>
<section id="assumption-5-homoskedasticity" class="level3" data-number="5.7.5">
<h3 data-number="5.7.5" class="anchored" data-anchor-id="assumption-5-homoskedasticity"><span class="header-section-number">5.7.5</span> Assumption 5: Homoskedasticity</h3>
<p><span class="math display">\[
Var(\mu | x_1, x_2, \ldots, x_k) = \sigma^2
\]</span></p>
<p>The variance of the error term is constant across all combinations of independent variable values.</p>
</section>
</section>
<section id="unbiasedness-of-multivariate-ols" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="unbiasedness-of-multivariate-ols"><span class="header-section-number">5.8</span> Unbiasedness of Multivariate OLS</h2>
<p>Just like with bivariate OLS, if Gauss-Markov assumptions 1–4 hold, then our multivariate OLS estimates are <strong>unbiased:</strong></p>
<p><span class="math display">\[
E[\hat{\beta_j}] = \beta_j, j = {0, 1, ..., k}.
\]</span></p>
<p>We can then interpret our estimates as <em>ceteris paribus</em> comparisons, or apples-to-apples comparisons <em>conditional on control variables</em>.</p>
<section id="observed-vs.-unobserved-variables" class="level3" data-number="5.8.1">
<h3 data-number="5.8.1" class="anchored" data-anchor-id="observed-vs.-unobserved-variables"><span class="header-section-number">5.8.1</span> Observed vs.&nbsp;Unobserved Variables</h3>
<p>However, just because we are able to control for lots of variables doesn’t mean we have a causal estimate. In many cases, if we have lots of <em>observed</em> correlation between control variables and our independent variable of interest, we also probably have lots of <strong>unobserved</strong> correlation between variables.</p>
<p>For example, there could be important components of <span class="math inline">\(\mu\)</span> that we simply cannot measure sufficiently—inherent motivation in a wage regression, for example. Labor market surveys generally do not have an effective way to capture this, so this important determinant of wages is considered <em>unobserved</em>. We cannot include it in our multivariate regression model, so we will end up with a biased estimate.</p>
<p>But this is not the end of the world. Throughout the course, we are going to cover some methods which allow us to deal with some of these issues.</p>
</section>
</section>
<section id="the-omitted-variable-bias-formula" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="the-omitted-variable-bias-formula"><span class="header-section-number">5.9</span> The Omitted Variable Bias Formula</h2>
<p>Even when we can’t include an omitted variable (perhaps because it’s unobservable), we can still reason about the <strong>direction</strong> of the bias.</p>
<section id="setup" class="level3" data-number="5.9.1">
<h3 data-number="5.9.1" class="anchored" data-anchor-id="setup"><span class="header-section-number">5.9.1</span> Setup</h3>
<p>Let’s say our independent variable of interest is <span class="math inline">\(x_1\)</span> (e.g., education).</p>
<p>Suppose the true population regression model is:</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \mu
\]</span></p>
<p>In an ideal world, we would be able to estimate the correctly specified model, which gives unbiased estimates:</p>
<p><span class="math display">\[
\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x_1 + \hat{\beta}_2 x_2
\]</span></p>
<p>But we can’t observe <span class="math inline">\(x_2\)</span> (it may be motivation or ability, for example), so instead we estimate the misspecified model:</p>
<p><span class="math display">\[
\tilde{y} = \tilde{\beta}_0 + \tilde{\beta}_1 x_1
\]</span></p>
<p>where the tilde (<span class="math inline">\(\tilde{}\)</span>) indicates estimates from the misspecified model.</p>
</section>
<section id="the-ovb-formula" class="level3" data-number="5.9.2">
<h3 data-number="5.9.2" class="anchored" data-anchor-id="the-ovb-formula"><span class="header-section-number">5.9.2</span> The OVB Formula</h3>
<p>It turns out there is a simple relationship between our biased estimate from the misspecified model, <span class="math inline">\(\tilde{\beta}_1\)</span>, and our unbiased, correctly specified model <span class="math inline">\(\hat{\beta}_1\)</span>:</p>
<p>It can be shown that:</p>
<p><span id="eq-ovb-formula"><span class="math display">\[
\tilde{\beta}_1 = \hat{\beta}_1 + \hat{\beta}_2 \tilde{\delta}_1
\tag{5.2}\]</span></span></p>
<p>where <span class="math inline">\(\tilde{\delta}_1\)</span> is the coefficient from regressing <span class="math inline">\(x_2\)</span> on <span class="math inline">\(x_1\)</span>:</p>
<p><span class="math display">\[
x_2 = \tilde{\delta}_0 + \tilde{\delta}_1 x_1 + \text{error}.
\]</span></p>
<p>Taking expectations:</p>
<p><span class="math display">\[
E[\tilde{\beta}_1] = \beta_1 + \beta_2 \tilde{\delta}_1
\]</span></p>
<p>Therefore, the <strong>bias</strong> is:</p>
<p><span id="eq-ovb-bias"><span class="math display">\[
\text{Bias}(\tilde{\beta}_1) = \beta_2 \cdot \tilde{\delta}_1
\tag{5.3}\]</span></span></p>
</section>
<section id="interpreting-the-bias-formula" class="level3" data-number="5.9.3">
<h3 data-number="5.9.3" class="anchored" data-anchor-id="interpreting-the-bias-formula"><span class="header-section-number">5.9.3</span> Interpreting the Bias Formula</h3>
<p>The bias depends on two factors:</p>
<ol type="1">
<li><strong><span class="math inline">\(\beta_2\)</span>:</strong> The effect of the omitted variable on <span class="math inline">\(y\)</span></li>
<li><strong><span class="math inline">\(\tilde{\delta}_1\)</span>:</strong> The relationship between the omitted variable (<span class="math inline">\(x_2\)</span>) and the included variable (<span class="math inline">\(x_1\)</span>). Technically, it is the slope from regressing <span class="math inline">\(x_2\)</span> on <span class="math inline">\(x_1\)</span>, but it always has the same sign as <span class="math inline">\(Corr(x_1, x_2)\)</span>, which is all we need to sign the bias</li>
</ol>
<p>If either factor is zero, there is no bias. But if both are non-zero, bias exists, and its direction depends on the signs:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 44%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(Corr(x_1, x_2) &gt; 0\)</span></th>
<th><span class="math inline">\(Corr(x_1, x_2) &lt; 0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\beta_2 &gt; 0\)</span></td>
<td>Positive bias (overestimate)</td>
<td>Negative bias (underestimate)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta_2 &lt; 0\)</span></td>
<td>Negative bias (underestimate)</td>
<td>Positive bias (overestimate)</td>
</tr>
</tbody>
</table>
</section>
<section id="example-education-wages-and-ability" class="level3" data-number="5.9.4">
<h3 data-number="5.9.4" class="anchored" data-anchor-id="example-education-wages-and-ability"><span class="header-section-number">5.9.4</span> Example: Education, Wages, and Ability</h3>
<p>Consider estimating the return to education while omitting ability:</p>
<ul>
<li><strong><span class="math inline">\(\beta_2\)</span> (effect of ability on wages):</strong> Positive (more able people earn more)</li>
<li><strong><span class="math inline">\(\tilde{\delta}_1\)</span> (correlation of ability with education):</strong> Positive (more able people get more education)</li>
</ul>
<p>Therefore: <span class="math display">\[\text{Bias} = (+)(+) = \text{Positive}\]</span></p>
<p>Our estimate of the return to education is <strong>too large</strong>—it includes part of the return to ability.</p>
</section>
<section id="example-policing-crime-and-poverty" class="level3" data-number="5.9.5">
<h3 data-number="5.9.5" class="anchored" data-anchor-id="example-policing-crime-and-poverty"><span class="header-section-number">5.9.5</span> Example: Policing, Crime, and Poverty</h3>
<p>Consider estimating the effect of policing on crime while omitting local poverty:</p>
<ul>
<li><strong>Effect of poverty on crime (<span class="math inline">\(\beta_2\)</span>):</strong> Positive (higher poverty → more crime)</li>
<li><strong>Correlation of poverty with policing (<span class="math inline">\(\tilde{\delta}_1\)</span>):</strong> Positive (high-poverty areas get more policing)</li>
</ul>
<p>Therefore: <span class="math display">\[\text{Bias} = (+)(+) = \text{Positive}\]</span></p>
<p>Our estimate suggests policing <em>increases</em> crime more than it actually does (or reduces it less than it actually does). This is why naive correlations between police presence and crime can be misleading.</p>
</section>
<section id="example-study-hours-course-difficulty-and-gpa" class="level3" data-number="5.9.6">
<h3 data-number="5.9.6" class="anchored" data-anchor-id="example-study-hours-course-difficulty-and-gpa"><span class="header-section-number">5.9.6</span> Example: Study Hours, Course Difficulty, and GPA</h3>
<p>Consider estimating the effect of study hours on GPA while omitting course difficulty:</p>
<ul>
<li><strong>Effect of course difficulty on GPA (<span class="math inline">\(\beta_2\)</span>):</strong> Negative (harder courses → lower GPA)</li>
<li><strong>Correlation of course difficulty with study hours (<span class="math inline">\(\tilde{\delta}_1\)</span>):</strong> Positive (harder courses → students study more)</li>
</ul>
<p>Therefore: <span class="math display">\[\text{Bias} = (-)(+) = \text{Negative}\]</span></p>
<p>Our estimate understates the true benefit of studying. Students who study the most tend to be taking harder courses that drag down their GPAs, so the naive estimate makes studying look <em>less</em> effective than it actually is.</p>
</section>
</section>
<section id="variance-in-multivariate-ols" class="level2" data-number="5.10">
<h2 data-number="5.10" class="anchored" data-anchor-id="variance-in-multivariate-ols"><span class="header-section-number">5.10</span> Variance in Multivariate OLS</h2>
<p>Under the Gauss-Markov assumptions, the variance of <span class="math inline">\(\hat{\beta}_j\)</span> is:</p>
<p><span id="eq-multivar-variance"><span class="math display">\[
Var(\hat{\beta}_j) = \frac{\sigma^2}{SST_j (1 - R_j^2)}
\tag{5.4}\]</span></span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\sigma^2\)</span> is the error variance</li>
<li><span class="math inline">\(SST_j = \sum(x_{ji} - \bar{x}_j)^2\)</span> is the total variation in <span class="math inline">\(x_j\)</span></li>
<li><span class="math inline">\(R_j^2\)</span> is the R-squared from regressing <span class="math inline">\(x_j\)</span> on all other independent variables</li>
</ul>
<section id="what-increases-variance" class="level3" data-number="5.10.1">
<h3 data-number="5.10.1" class="anchored" data-anchor-id="what-increases-variance"><span class="header-section-number">5.10.1</span> What Increases Variance?</h3>
<p>From <a href="#eq-multivar-variance" class="quarto-xref">Equation&nbsp;<span>5.4</span></a>, the variance of <span class="math inline">\(\hat{\beta}_j\)</span> increases when:</p>
<ol type="1">
<li><strong>More noise (<span class="math inline">\(\sigma^2\)</span>):</strong> Higher error variance means less precise estimates</li>
<li><strong>Less variation in <span class="math inline">\(x_j\)</span> (<span class="math inline">\(SST_j\)</span>):</strong> Less information about how <span class="math inline">\(x_j\)</span> relates to <span class="math inline">\(y\)</span></li>
<li><strong>Higher <span class="math inline">\(R_j^2\)</span>:</strong> More correlation between <span class="math inline">\(x_j\)</span> and other independent variables</li>
</ol>
<p>The third point is crucial: when your variable of interest is highly correlated with control variables, your estimate becomes less precise. This is sometimes called <strong>high multicollinearity</strong> or the <strong>multicollinearity problem</strong>.</p>
<p>Note this is different from <strong>perfect multicollinearity</strong>, which makes it <em>impossible</em> to get an estimate. Here, we still will be able to estimate our <span class="math inline">\(\beta_j\)</span> successfully, but it will have a high variance and be “noisy”.</p>
</section>
<section id="estimating-sigma2-from-the-data" class="level3" data-number="5.10.2">
<h3 data-number="5.10.2" class="anchored" data-anchor-id="estimating-sigma2-from-the-data"><span class="header-section-number">5.10.2</span> Estimating <span class="math inline">\(\sigma^2\)</span> from the Data</h3>
<p>Look carefully at the variance formula above. The denominator contains quantities we can compute directly from our sample: <span class="math inline">\(SST_j\)</span> (the total variation in <span class="math inline">\(x_j\)</span>) and <span class="math inline">\(R^2_j\)</span> (how much of <span class="math inline">\(x_j\)</span> is explained by the other regressors). But the numerator contains <span class="math inline">\(\sigma^2\)</span>—the <strong>variance of the population error term</strong>. This is a population parameter that we cannot observe directly.</p>
<p>So how do we estimate <span class="math inline">\(\sigma^2\)</span>?</p>
<p>Recall from the homoskedasticity assumption (Assumption 5) that <span class="math inline">\(Var(\mu_i | \mathbf{x}_i) = \sigma^2\)</span> for all observations <span class="math inline">\(i\)</span>. Combined with the zero conditional mean assumption (Assumption 4), which gives us <span class="math inline">\(E[\mu_i | \mathbf{x}_i] = 0\)</span>, we can show that <span class="math inline">\(\sigma^2 = E[\mu_i^2]\)</span>. Let’s work through why.</p>
<p>From <a href="statsreview.html" class="quarto-xref"><span>Appendix B</span></a>, the definition of variance is <span class="math inline">\(Var(X) = E[(X - E[X])^2]\)</span>—the expected squared deviation from the mean. (In <a href="statsreview.html" class="quarto-xref"><span>Appendix B</span></a> we wrote the mean as <span class="math inline">\(\mu\)</span>; here we write <span class="math inline">\(E[X]\)</span> so it isn’t confused with the error term <span class="math inline">\(\mu_i\)</span>.) Applying this to <span class="math inline">\(\mu_i\)</span> and using the fact that <span class="math inline">\(E[\mu_i] = 0\)</span> from Assumption 4:</p>
<p><span class="math display">\[Var(\mu_i) = E[(\mu_i - 0)^2] = E[\mu_i^2]\]</span></p>
<p>And from Assumption 5, <span class="math inline">\(Var(\mu_i) = \sigma^2\)</span>, giving us:</p>
<p><span class="math display">\[\sigma^2 = E[\mu_i^2]\]</span></p>
<p>In other words, <span class="math inline">\(\sigma^2\)</span> is simply the expected value of the squared error terms. If we could observe the true errors <span class="math inline">\(\mu_i\)</span>, we’d just compute their average squared value. But we can’t observe the true errors—they’re the difference between the actual outcome <span class="math inline">\(y_i\)</span> and the <strong>population</strong> regression line, which we don’t know.</p>
<p>What we <em>can</em> compute are the <strong>residuals</strong>:</p>
<p><span class="math display">\[\hat{\mu}_i = y_i - \hat{y}_i = y_i - \hat{\beta}_0 - \hat{\beta}_1 x_{1i} - \dots - \hat{\beta}_k x_{ki}\]</span></p>
<p>The residuals are the sample analog of the population errors. They measure the difference between the actual outcome and the <strong>estimated</strong> regression line. Since the residuals approximate the true errors, we can use them to estimate <span class="math inline">\(\sigma^2\)</span>.</p>
<p>It turns out that the average squared residual, adjusted for <strong>degrees of freedom</strong>, is an unbiased estimator of <span class="math inline">\(\sigma^2\)</span>:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Estimating <span class="math inline">\(\sigma^2\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[\hat{\sigma}^2 = \frac{\sum_{i=1}^{n} \hat{\mu}_i^2}{n - k - 1} = \frac{SSR}{n - k - 1}\]</span></p>
<p>where <span class="math inline">\(SSR = \sum_{i=1}^{n}\hat{\mu}_i^2\)</span> is the sum of squared residuals and <span class="math inline">\(n - k - 1\)</span> is the degrees of freedom (sample size minus the number of estimated parameters).</p>
</div>
</div>
<p>Why do we divide by <span class="math inline">\(n - k - 1\)</span> instead of <span class="math inline">\(n\)</span>? Because we used <span class="math inline">\(k + 1\)</span> estimated coefficients (<span class="math inline">\(\hat{\beta}_0, \hat{\beta}_1, \dots, \hat{\beta}_k\)</span>) to compute the residuals. Each estimated coefficient “uses up” one degree of freedom, so we need to correct for this to get an unbiased estimate. This is the same logic behind the degrees-of-freedom correction in the adjusted <span class="math inline">\(R^2\)</span>.</p>
<p>The square root <span class="math inline">\(\hat{\sigma} = \sqrt{\hat{\sigma}^2}\)</span> is sometimes called the <strong>standard error of the regression</strong> (SER) or the <strong>root mean squared error</strong> (RMSE). In R output, this appears as <strong>Residual standard error</strong>.</p>
</section>
<section id="from-hatsigma2-to-the-standard-error" class="level3" data-number="5.10.3">
<h3 data-number="5.10.3" class="anchored" data-anchor-id="from-hatsigma2-to-the-standard-error"><span class="header-section-number">5.10.3</span> From <span class="math inline">\(\hat{\sigma}^2\)</span> to the Standard Error</h3>
<p>Now we can plug our estimate <span class="math inline">\(\hat{\sigma}^2\)</span> into the variance formula. The <strong>standard error</strong> of <span class="math inline">\(\hat{\beta}_j\)</span> is:</p>
<p><span class="math display">\[
se(\hat{\beta}_j) = \frac{\hat{\sigma}}{\sqrt{SST_j(1 - R_j^2)}}
\]</span></p>
<p>The standard error is the estimated standard deviation of the sampling distribution of <span class="math inline">\(\hat{\beta}_j\)</span>. It tells us how much our estimate would typically vary across repeated samples. Every time you see <span class="math inline">\(se(\hat{\beta}_j)\)</span> in a regression table, a formula, or R output, this is what’s being computed behind the scenes.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The Big Picture
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[Var(\hat{\beta}_j) = \frac{\sigma^2}{SST_j(1-R_j^2)} \xrightarrow{\text{estimate } \sigma^2 \text{ with residuals}} se(\hat{\beta}_j) = \frac{\hat{\sigma}}{\sqrt{SST_j(1-R_j^2)}}\]</span></p>
<p>We go from a formula involving an unknown population parameter (<span class="math inline">\(\sigma^2\)</span>) to a fully computable <strong>standard error</strong> by replacing <span class="math inline">\(\sigma^2\)</span> with its sample estimate <span class="math inline">\(\hat{\sigma}^2 = SSR/(n-k-1)\)</span>. The standard error is the foundation of statistical inference: t-statistics, p-values, and confidence intervals (covered in the next unit) all depend on it.</p>
</div>
</div>
</section>
<section id="simulation-does-hatsigma2-actually-work" class="level3" data-number="5.10.4">
<h3 data-number="5.10.4" class="anchored" data-anchor-id="simulation-does-hatsigma2-actually-work"><span class="header-section-number">5.10.4</span> Simulation: Does <span class="math inline">\(\hat{\sigma}^2\)</span> Actually Work?</h3>
<p>Let’s verify that <span class="math inline">\(\hat{\sigma}^2 = SSR/(n-k-1)\)</span> is a good estimator of <span class="math inline">\(\sigma^2\)</span> with a simulation. We’ll set up a known population where we <em>choose</em> the true <span class="math inline">\(\sigma^2\)</span>, then check whether our estimator recovers it.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">325</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Population parameters ---</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">20</span>           <span class="co"># sample size (small, so the degrees-of-freedom correction is easy to see)</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>true_sigma2 <span class="ot">&lt;-</span> <span class="dv">4</span>  <span class="co"># the TRUE error variance (σ² = 4)</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>n_sims <span class="ot">&lt;-</span> <span class="dv">5000</span>    <span class="co"># number of simulations</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Run the simulation ---</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>sigma2_hat <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n_sims)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_sims) {</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Generate data from a known DGP: y = 2 + 3*x1 + 1*x2 + μ</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  x2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  mu <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="fu">sqrt</span>(true_sigma2))  <span class="co"># errors with σ² = 4</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> x1 <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> x2 <span class="sc">+</span> mu</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Estimate the model</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>  reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2)</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Compute σ̂² = SSR / (n - k - 1)</span></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>  residuals_sq <span class="ot">&lt;-</span> <span class="fu">residuals</span>(reg)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>  sigma2_hat[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(residuals_sq) <span class="sc">/</span> (n <span class="sc">-</span> <span class="dv">2</span> <span class="sc">-</span> <span class="dv">1</span>)  <span class="co"># n - k - 1 = 20 - 2 - 1 = 17</span></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Visualize the results ---</span></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">tibble</span>(sigma2_hat), <span class="fu">aes</span>(<span class="at">x =</span> sigma2_hat)) <span class="sc">+</span></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">bins =</span> <span class="dv">50</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> true_sigma2, <span class="at">color =</span> <span class="st">"darkred"</span>, <span class="at">linewidth =</span> <span class="fl">1.5</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(sigma2_hat), <span class="at">color =</span> <span class="st">"darkgreen"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> true_sigma2 <span class="sc">+</span> <span class="fl">0.15</span>, <span class="at">y =</span> <span class="cn">Inf</span>, <span class="at">vjust =</span> <span class="dv">2</span>,</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"True σ² = "</span>, true_sigma2),</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"darkred"</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">fontface =</span> <span class="st">"italic"</span>) <span class="sc">+</span></span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fu">mean</span>(sigma2_hat) <span class="sc">+</span> <span class="fl">0.15</span>, <span class="at">y =</span> <span class="cn">Inf</span>, <span class="at">vjust =</span> <span class="dv">4</span>,</span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"Average σ̂² = "</span>, <span class="fu">round</span>(<span class="fu">mean</span>(sigma2_hat), <span class="dv">3</span>)),</span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"darkgreen"</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">fontface =</span> <span class="st">"italic"</span>) <span class="sc">+</span></span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(sigma)<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frequency"</span>,</span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">"Sampling Distribution of "</span>, <span class="fu">hat</span>(sigma)<span class="sc">^</span><span class="dv">2</span>))) <span class="sc">+</span></span>
<span id="cb22-40"><a href="#cb22-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-sigma-hat-sim" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-sigma-hat-sim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Distribution of <span class="math inline">\(\hat{\sigma}^2\)</span> across 5,000 simulated samples. The estimator is centered on the true <span class="math inline">\(\sigma^2 = 4\)</span>, confirming it is unbiased.
</figcaption>
<div aria-describedby="fig-sigma-hat-sim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="multivariate_ols_files/figure-html/fig-sigma-hat-sim-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>The simulation confirms that <span class="math inline">\(\hat{\sigma}^2\)</span> is unbiased: the average across all 5,000 samples is very close to the true <span class="math inline">\(\sigma^2 = 4\)</span>. Any <em>single</em> estimate of <span class="math inline">\(\hat{\sigma}^2\)</span> can land well above or below the true value, but the distribution is centered in the right place.</p>
<p>What happens if we divide by <span class="math inline">\(n\)</span> instead of <span class="math inline">\(n - k - 1\)</span>? Let’s check:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the naive (biased) estimator that divides by n</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>sigma2_naive <span class="ot">&lt;-</span> sigma2_hat <span class="sc">*</span> (n <span class="sc">-</span> <span class="dv">2</span> <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> n  <span class="co"># convert back: multiply by (n-k-1) then divide by n</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">estimate =</span> sigma2_hat, <span class="at">type =</span> <span class="st">"SSR / (n - k - 1)  [unbiased]"</span>),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">estimate =</span> sigma2_naive, <span class="at">type =</span> <span class="st">"SSR / n  [biased]"</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">fill =</span> type)) <span class="sc">+</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">bins =</span> <span class="dv">50</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">position =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Solid lines: the average of each estimator across the 5,000 samples</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(sigma2_hat), <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(sigma2_naive), <span class="at">color =</span> <span class="st">"darkorange"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> true_sigma2, <span class="at">color =</span> <span class="st">"darkred"</span>, <span class="at">linewidth =</span> <span class="fl">1.5</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"steelblue"</span>, <span class="st">"orange"</span>)) <span class="sc">+</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> true_sigma2 <span class="sc">+</span> <span class="fl">0.1</span>, <span class="at">y =</span> <span class="cn">Inf</span>, <span class="at">vjust =</span> <span class="dv">2</span>,</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"True σ² = "</span>, true_sigma2),</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"darkred"</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">fontface =</span> <span class="st">"italic"</span>) <span class="sc">+</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(sigma)<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frequency"</span>,</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Estimator"</span>,</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Why the Degrees-of-Freedom Correction Matters"</span>) <span class="sc">+</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-sigma-hat-biased" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-sigma-hat-biased-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Comparing the unbiased estimator <span class="math inline">\(SSR/(n-k-1)\)</span> to the naive estimator <span class="math inline">\(SSR/n\)</span>. Dividing by <span class="math inline">\(n\)</span> systematically underestimates <span class="math inline">\(\sigma^2\)</span>.
</figcaption>
<div aria-describedby="fig-sigma-hat-biased-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="multivariate_ols_files/figure-html/fig-sigma-hat-biased-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>The orange distribution (dividing by <span class="math inline">\(n\)</span>) is shifted to the left—it systematically <em>underestimates</em> <span class="math inline">\(\sigma^2\)</span>. With <span class="math inline">\(n = 20\)</span> and <span class="math inline">\(k = 2\)</span>, dividing by <span class="math inline">\(n\)</span> instead of <span class="math inline">\(n - k - 1 = 17\)</span> understates <span class="math inline">\(\sigma^2\)</span> by 15% on average. The degrees-of-freedom correction fixes this bias. The intuition is that the residuals are computed from the <em>estimated</em> regression line, which is already chosen to fit the data as closely as possible. This makes the residuals systematically smaller than the true errors, and dividing by <span class="math inline">\(n - k - 1\)</span> instead of <span class="math inline">\(n\)</span> corrects for this. In large samples the correction barely matters: with <span class="math inline">\(n = 1{,}000\)</span>, dividing by <span class="math inline">\(n\)</span> would understate <span class="math inline">\(\sigma^2\)</span> by only 0.3%.</p>
</section>
</section>
<section id="the-bias-variance-tradeoff" class="level2" data-number="5.11">
<h2 data-number="5.11" class="anchored" data-anchor-id="the-bias-variance-tradeoff"><span class="header-section-number">5.11</span> The Bias-Variance Tradeoff</h2>
<p>Should you include a variable in your regression? The answer depends on a tradeoff.</p>
<section id="the-costs-of-omitting-a-relevant-variable" class="level3" data-number="5.11.1">
<h3 data-number="5.11.1" class="anchored" data-anchor-id="the-costs-of-omitting-a-relevant-variable"><span class="header-section-number">5.11.1</span> The Costs of Omitting a Relevant Variable</h3>
<p>If a variable truly belongs in the model (<span class="math inline">\(\beta_2 \neq 0\)</span>) and is correlated with <span class="math inline">\(x_1\)</span>, omitting it causes <strong>bias</strong>. Your estimate systematically misses the true value.</p>
</section>
<section id="the-costs-of-including-an-irrelevant-variable" class="level3" data-number="5.11.2">
<h3 data-number="5.11.2" class="anchored" data-anchor-id="the-costs-of-including-an-irrelevant-variable"><span class="header-section-number">5.11.2</span> The Costs of Including an Irrelevant Variable</h3>
<p>What if you include a variable that doesn’t belong (<span class="math inline">\(\beta_2 = 0\)</span>)?</p>
<p>In that case, the true model is just</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + 0 \cdot x_2 + \mu,
\]</span></p>
<p>so the regression that includes <span class="math inline">\(x_2\)</span> is still correctly specified. Assumptions 1–4 still hold, which means:</p>
<p><span class="math display">\[
E[\hat{\beta}_1] = \beta_1 \quad \text{and} \quad E[\hat{\beta}_2] = 0
\]</span></p>
<p>No bias! Including an irrelevant variable doesn’t bias your estimate.</p>
<p>But look at the variance formula. If the extra variable is correlated with <span class="math inline">\(x_1\)</span>, including it increases <span class="math inline">\(R_1^2\)</span> (the share of the variation in <span class="math inline">\(x_1\)</span> explained by the other independent variables), which increases the variance of <span class="math inline">\(\hat{\beta}_1\)</span>.</p>
<p><strong>Including irrelevant variables that are correlated with <span class="math inline">\(x_1\)</span> inflates variance without reducing bias.</strong></p>
</section>
<section id="the-tradeoff" class="level3" data-number="5.11.3">
<h3 data-number="5.11.3" class="anchored" data-anchor-id="the-tradeoff"><span class="header-section-number">5.11.3</span> The Tradeoff</h3>
<p>For a variable that is correlated with <span class="math inline">\(x_1\)</span>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Action</th>
<th>Bias</th>
<th>Variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Omit relevant variable</td>
<td>Increases</td>
<td>Usually decreases</td>
</tr>
<tr class="even">
<td>Include irrelevant variable</td>
<td>No change</td>
<td>Increases</td>
</tr>
</tbody>
</table>
<p>Why only “usually”? When you omit <span class="math inline">\(x_2\)</span>, its effect (<span class="math inline">\(\beta_2 x_2\)</span>) becomes part of the error term, which makes the error variance larger. If <span class="math inline">\(\beta_2\)</span> is big, that extra noise can outweigh the precision you gain from dropping <span class="math inline">\(x_2\)</span>, and the short model can end up <em>noisier</em> than the long one.</p>
<p>This is the <strong>bias-variance tradeoff</strong>:</p>
<ul>
<li>If you’re too conservative (omit too many variables), you risk bias</li>
<li>If you’re too liberal (include everything), you inflate variance</li>
</ul>
</section>
<section id="practical-guidance" class="level3" data-number="5.11.4">
<h3 data-number="5.11.4" class="anchored" data-anchor-id="practical-guidance"><span class="header-section-number">5.11.4</span> Practical Guidance</h3>
<p>There’s no perfect solution, but some principles help:</p>
<ol type="1">
<li><p><strong>Include variables you have strong theoretical reasons to believe are confounders.</strong> Use economic theory and prior research to guide variable selection.</p></li>
<li><p><strong>Be cautious about highly correlated controls.</strong> If two controls are very highly correlated with each other, including both can dramatically inflate variance.</p></li>
<li><p><strong>Larger samples help.</strong> As <span class="math inline">\(n\)</span> increases, variance decreases, making the “include it just in case” strategy less costly.</p></li>
<li><p><strong>Check how estimates change.</strong> If adding a control substantially changes your coefficient of interest, that control is probably important.</p></li>
</ol>
</section>
</section>
<section id="simulation-bias-vs.-variance" class="level2" data-number="5.12">
<h2 data-number="5.12" class="anchored" data-anchor-id="simulation-bias-vs.-variance"><span class="header-section-number">5.12</span> Simulation: Bias vs.&nbsp;Variance</h2>
<p>Let’s see the bias-variance tradeoff in action with a simulation. We generate two populations—one where <span class="math inline">\(x_2\)</span> is irrelevant (<span class="math inline">\(\beta_2 = 0\)</span>) and one where <span class="math inline">\(x_2\)</span> is relevant (<span class="math inline">\(\beta_2 \neq 0\)</span>)—then repeatedly estimate <span class="math inline">\(\hat{\beta}_1\)</span> using either the short model (omit <span class="math inline">\(x_2\)</span>) or the long model (include <span class="math inline">\(x_2\)</span>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bias-variance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-bias-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: The bias-variance tradeoff across all four cases. Each panel shows the sampling distribution of <span class="math inline">\(\hat{\beta}_1\)</span> from 1,000 simulations. The dashed red line marks the true <span class="math inline">\(\beta_1 = 2.21\)</span>.
</figcaption>
<div aria-describedby="fig-bias-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="multivariate_ols_files/figure-html/fig-bias-variance-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
</figure>
</div>
</div>
</div>
<p>Each panel shows one of the four possible scenarios:</p>
<ul>
<li><p><strong>Case 1</strong> (top-left): <span class="math inline">\(x_2\)</span> is irrelevant and we omit it. Both bias and variance are small. This is the <em>best case</em>—we correctly leave out a variable that doesn’t belong.</p></li>
<li><p><strong>Case 2</strong> (top-right): <span class="math inline">\(x_2\)</span> is irrelevant but we include it anyway. The estimates are still centered on the true value (no bias), but the distribution is <em>wider</em> (higher variance). Including an irrelevant variable costs us precision for no benefit.</p></li>
<li><p><strong>Case 3</strong> (bottom-left): <span class="math inline">\(x_2\)</span> is relevant but we omit it. The distribution shifts away from the true <span class="math inline">\(\beta_1\)</span>—this is <strong>omitted variable bias</strong>. The variance is lower than in Case 4, but the estimates are <em>systematically wrong</em>.</p></li>
<li><p><strong>Case 4</strong> (bottom-right): <span class="math inline">\(x_2\)</span> is relevant and we include it. The distribution is centered on the true value (no bias), though it is wider than in Cases 1 and 3. This is the <em>correct</em> specification—the variance cost is worth paying to eliminate bias.</p></li>
</ul>
<p>Case 3 is narrower than Case 4 here, as the table above predicts. That isn’t guaranteed, though. With a larger effect of <span class="math inline">\(x_2\)</span> (say, <span class="math inline">\(\beta_2 = 1.5\)</span> instead of <span class="math inline">\(0.5\)</span>), omitting <span class="math inline">\(x_2\)</span> would add so much noise to the error term that Case 3 would actually be <em>wider</em> than Case 4.</p>
</section>
<section id="summary" class="level2" data-number="5.13">
<h2 data-number="5.13" class="anchored" data-anchor-id="summary"><span class="header-section-number">5.13</span> Summary</h2>
<p>This chapter extended OLS to the multivariate case, allowing us to control for confounding variables.</p>
<section id="key-takeaways" class="level3" data-number="5.13.1">
<h3 data-number="5.13.1" class="anchored" data-anchor-id="key-takeaways"><span class="header-section-number">5.13.1</span> Key Takeaways</h3>
<ul>
<li><p><strong>Multivariate OLS</strong> includes multiple independent variables: <span class="math display">\[y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_k x_k + \mu\]</span></p></li>
<li><p><strong>Coefficients have ceteris paribus interpretations:</strong> <span class="math inline">\(\beta_j\)</span> is the effect of <span class="math inline">\(x_j\)</span> holding all other variables constant</p></li>
<li><p><strong>The zero conditional mean assumption</strong> now requires <span class="math inline">\(E[\mu | x_1, \ldots, x_k] = 0\)</span>—more plausible with good controls</p></li>
<li><p><strong>Multivariate OLS is like matching:</strong> It compares observations within groups defined by control variables, then takes a weighted average across groups (weighting by each group’s size and by how much <span class="math inline">\(x\)</span> varies within it)</p></li>
<li><p><strong>Adjusted <span class="math inline">\(R^2\)</span></strong> penalizes for the number of independent variables; regular <span class="math inline">\(R^2\)</span> never falls when you add a variable</p></li>
<li><p><strong>The OVB formula</strong> tells us the direction of bias from omitting a variable: <span class="math display">\[\text{Bias} = \beta_2 \cdot \tilde{\delta}_1\]</span></p></li>
<li><p><strong>The variance of <span class="math inline">\(\hat{\beta}_j\)</span></strong> is <span class="math inline">\(\sigma^2 / [SST_j(1 - R_j^2)]\)</span>. We estimate <span class="math inline">\(\sigma^2\)</span> with <span class="math inline">\(\hat{\sigma}^2 = SSR/(n - k - 1)\)</span>, which gives the standard error <span class="math inline">\(se(\hat{\beta}_j) = \hat{\sigma} / \sqrt{SST_j(1 - R_j^2)}\)</span></p></li>
<li><p><strong>There’s a bias-variance tradeoff:</strong> Omitting relevant variables causes bias; including irrelevant variables that are correlated with <span class="math inline">\(x_1\)</span> inflates variance</p></li>
<li><p><strong>Perfect multicollinearity</strong> occurs when one variable is an exact linear function of others; it must be avoided</p></li>
</ul>
</section>
</section>
<section id="check-your-understanding" class="level2" data-number="5.14">
<h2 data-number="5.14" class="anchored" data-anchor-id="check-your-understanding"><span class="header-section-number">5.14</span> Check Your Understanding</h2>
<div class="question">
<div class="answer-row">
    <label>i. In the model \(y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \mu\), what does \(\beta_1\) represent? </label>
    <select onchange="checkAnswer(this, 'c')">
        <option value="">-- Select Answer --</option>
        <option value="a">The total effect of \(x_1\) on \(y\)</option>
        <option value="b">The correlation between \(x_1\) and \(y\)</option>
        <option value="c">The effect of \(x_1\) on \(y\), holding \(x_2\) constant</option>
        <option value="d">The effect of \(x_1\) on \(y\), ignoring \(x_2\)</option>
    </select>
</div>

<div class="answer-row">
    <label>ii. The zero conditional mean assumption in multivariate OLS states: </label>
    <select onchange="checkAnswer(this, 'b')">
        <option value="">-- Select Answer --</option>
        <option value="a">\(E[\mu] = 0\)</option>
        <option value="b">\(E[\mu | x_1, x_2, \ldots, x_k] = 0\)</option>
        <option value="c">\(E[y | x_1, x_2, \ldots, x_k] = 0\)</option>
        <option value="d">\(Var(\mu | x_1, x_2, \ldots, x_k) = \sigma^2\)</option>
    </select>
</div>

<div class="answer-row">
    <label>iii. Perfect multicollinearity occurs when: </label>
    <select onchange="checkAnswer(this, 'd')">
        <option value="">-- Select Answer --</option>
        <option value="a">Two independent variables are correlated</option>
        <option value="b">The R-squared is very high</option>
        <option value="c">The error term is correlated with an independent variable</option>
        <option value="d">One independent variable is an exact linear function of others</option>
    </select>
</div>

<div class="answer-row">
    <label>iv. The adjusted R-squared differs from the regular R-squared because it: </label>
    <select onchange="checkAnswer(this, 'a')">
        <option value="">-- Select Answer --</option>
        <option value="a">Penalizes for the number of independent variables</option>
        <option value="b">Is always larger</option>
        <option value="c">Measures causality rather than correlation</option>
        <option value="d">Only applies to bivariate regression</option>
    </select>
</div>

<div class="answer-row">
    <label>v. According to the OVB formula, bias equals zero when: </label>
    <select onchange="checkAnswer(this, 'c')">
        <option value="">-- Select Answer --</option>
        <option value="a">The omitted variable is important</option>
        <option value="b">The sample size is large</option>
        <option value="c">Either \(\beta_2 = 0\) or the omitted variable is uncorrelated with \(x_1\)</option>
        <option value="d">The R-squared is high</option>
    </select>
</div>

<div class="answer-row">
    <label>vi. If you include an irrelevant variable (one with \(\beta = 0\)) that is correlated with \(x_1\), your estimate of \(\beta_1\) will be: </label>
    <select onchange="checkAnswer(this, 'b')">
        <option value="">-- Select Answer --</option>
        <option value="a">Biased with lower variance</option>
        <option value="b">Unbiased with higher variance</option>
        <option value="c">Biased with higher variance</option>
        <option value="d">Unbiased with lower variance</option>
    </select>
</div>
</div>

<div class="context" style="margin-top: 30px; margin-bottom: 20px;">
<strong>OVB Direction Practice:</strong> For each scenario, determine the likely direction of bias.
</div>

<div class="question">
<div class="answer-row">
    <label>vii. Model: \(health = \beta_0 + \beta_1(exercise) + \mu\). Omitted variable: income. If higher income → more exercise AND higher income → better health, the bias on \(\hat{\beta}_1\) is: </label>
    <select onchange="checkAnswer(this, 'a')">
        <option value="">-- Select Answer --</option>
        <option value="a">Positive (overestimate)</option>
        <option value="b">Negative (underestimate)</option>
        <option value="c">Zero</option>
        <option value="d">Cannot determine</option>
    </select>
</div>

<div class="answer-row">
    <label>viii. Model: \(test\_score = \beta_0 + \beta_1(class\_size) + \mu\). Omitted variable: school funding. If more funding → smaller classes AND more funding → higher scores, the bias on \(\hat{\beta}_1\) is: </label>
    <select onchange="checkAnswer(this, 'b')">
        <option value="">-- Select Answer --</option>
        <option value="a">Positive (makes class size look beneficial)</option>
        <option value="b">Negative (makes class size look more harmful)</option>
        <option value="c">Zero</option>
        <option value="d">Cannot determine</option>
    </select>
</div>

<div class="answer-row">
    <label>ix. <strong>(Challenge)</strong> In a wage regression controlling for education and experience, you add a control for "IQ score." The coefficient on education drops substantially. This suggests: </label>
    <select onchange="checkAnswer(this, 'c')">
        <option value="">-- Select Answer --</option>
        <option value="a">IQ is irrelevant to wages</option>
        <option value="b">Education has no causal effect on wages</option>
        <option value="c">Part of the original "education effect" was actually capturing ability differences</option>
        <option value="d">The new regression is biased</option>
    </select>
</div>
</div>

<div class="context" style="margin-top: 30px; margin-bottom: 20px;">
<strong>Practice: Interpreting Multivariate Regression Output</strong>
</div>

<div class="context" style="margin-bottom: 20px;">
<strong>Regression 1:</strong> A researcher estimates the determinants of house prices:
<pre style="background-color: #f5f5f5; padding: 10px; margin-top: 10px; font-family: monospace;">Dependent variable: price (house price in $1000s)

             Estimate  Std. Error
(Intercept)    50.23      12.45
sqft            0.15       0.02
bedrooms       -8.72       3.21
bathrooms      24.56       4.89

n = 546, Adjusted R-squared = 0.68
</pre>
</div>

<div class="question">
<div class="answer-row">
    <label>x. According to this regression, an additional 100 square feet is associated with a price increase of: </label>
    <select onchange="checkAnswer(this, 'b')">
        <option value="">-- Select Answer --</option>
        <option value="a">$0.15</option>
        <option value="b">$15,000</option>
        <option value="c">$150</option>
        <option value="d">$1,500</option>
    </select>
</div>

<div class="answer-row">
    <label>xi. The negative coefficient on bedrooms (-8.72) means: </label>
    <select onchange="checkAnswer(this, 'c')">
        <option value="">-- Select Answer --</option>
        <option value="a">Houses with more bedrooms are always cheaper</option>
        <option value="b">Bedrooms reduce house prices by $8,720 on average</option>
        <option value="c">Holding sqft and bathrooms constant, an extra bedroom is associated with $8,720 lower price</option>
        <option value="d">The regression is incorrectly specified</option>
    </select>
</div>

<div class="answer-row">
    <label>xii. Why might the coefficient on bedrooms be negative even though houses with more bedrooms typically sell for more? </label>
    <select onchange="checkAnswer(this, 'd')">
        <option value="">-- Select Answer --</option>
        <option value="a">Measurement error in the data</option>
        <option value="b">The sample is not representative</option>
        <option value="c">Omitted variable bias</option>
        <option value="d">Holding square footage constant, more bedrooms means smaller rooms on average</option>
    </select>
</div>
</div>

<div class="context" style="margin-top: 30px; margin-bottom: 20px;">
<strong>Regression 2:</strong> An economist studies student test performance:
<pre style="background-color: #f5f5f5; padding: 10px; margin-top: 10px; font-family: monospace;">Dependent variable: test_score (standardized, mean=0, sd=1)

                  Estimate  Std. Error
(Intercept)        -0.892      0.156
hours_studied       0.045      0.008
parent_college      0.312      0.067
free_lunch         -0.287      0.071

n = 1,200, Adjusted R-squared = 0.23
</pre>
<em>Note: hours_studied = hours of study per week; parent_college = 1 if at least one parent has college degree; free_lunch = 1 if eligible for free lunch program (proxy for low income)</em>
</div>

<div class="question">
<div class="answer-row">
    <label>xiii. A student who studies 10 more hours per week is predicted to score how much higher? </label>
    <select onchange="checkAnswer(this, 'a')">
        <option value="">-- Select Answer --</option>
        <option value="a">0.45 standard deviations higher</option>
        <option value="b">0.045 standard deviations higher</option>
        <option value="c">4.5 points higher</option>
        <option value="d">45 points higher</option>
    </select>
</div>

<div class="answer-row">
    <label>xiv. Comparing two students who study the same amount and have the same free lunch status, a student with a college-educated parent scores on average: </label>
    <select onchange="checkAnswer(this, 'b')">
        <option value="">-- Select Answer --</option>
        <option value="a">0.312 points higher</option>
        <option value="b">0.312 standard deviations higher</option>
        <option value="c">31.2% higher</option>
        <option value="d">Cannot determine from this output</option>
    </select>
</div>

<div class="answer-row">
    <label>xv. <strong>(Challenge)</strong> A naive regression of test_score on hours_studied alone yields a coefficient of 0.062. Why might this be larger than the 0.045 in the full model? </label>
    <select onchange="checkAnswer(this, 'c')">
        <option value="">-- Select Answer --</option>
        <option value="a">The full model has more noise</option>
        <option value="b">Hours studied has less variation in the full model</option>
        <option value="c">Students from advantaged backgrounds (college parents, higher income) study more AND score higher for other reasons</option>
        <option value="d">The adjusted R-squared is too low</option>
    </select>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Explanation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="i">
<li><p>In multivariate regression, <span class="math inline">\(\beta_1\)</span> is the partial effect of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span>, holding <span class="math inline">\(x_2\)</span> (and all other included variables) constant. This is the ceteris paribus interpretation.</p></li>
<li><p>The multivariate zero conditional mean assumption requires that the error term have mean zero for all combinations of the independent variables, not just unconditionally.</p></li>
<li><p>Perfect multicollinearity means one variable is a perfect linear combination of others (like including income in dollars and income in thousands, or including all categories of a dummy variable plus an intercept). Simple correlation between variables is not perfect multicollinearity.</p></li>
<li><p>The adjusted R-squared penalizes for adding more variables, preventing the mechanical increase that happens with regular R-squared when you add irrelevant variables.</p></li>
<li><p>From the OVB formula: <span class="math inline">\(\text{Bias} = \beta_2 \cdot \tilde{\delta}_1\)</span>. Bias equals zero if either <span class="math inline">\(\beta_2 = 0\)</span> (the omitted variable doesn’t affect <span class="math inline">\(y\)</span>) or <span class="math inline">\(\tilde{\delta}_1 = 0\)</span> (the omitted variable is uncorrelated with <span class="math inline">\(x_1\)</span>).</p></li>
<li><p>Including an irrelevant variable doesn’t cause bias: with <span class="math inline">\(\beta_2 = 0\)</span>, the model that includes <span class="math inline">\(x_2\)</span> is still correctly specified, so Assumptions 1–4 still hold. But because the irrelevant variable is correlated with <span class="math inline">\(x_1\)</span>, it increases variance through the <span class="math inline">\((1 - R_j^2)\)</span> term in the variance formula.</p></li>
<li><p>Income is positively correlated with both exercise and health. $ = (+)(+) = $ Positive. We overestimate the effect of exercise because part of what we’re measuring is actually the effect of income.</p></li>
<li><p>More funding means smaller classes (negative correlation: <span class="math inline">\(\tilde{\delta}_1 &lt; 0\)</span>) and higher scores (<span class="math inline">\(\beta_2 &gt; 0\)</span>). $ = (+)(-) = $ Negative. The estimate of class size’s effect is too negative—we attribute to large classes what is actually due to low funding.</p></li>
<li><p>When adding a control causes the coefficient of interest to change substantially, it suggests the original estimate was confounded. Here, part of what looked like a “return to education” was actually capturing the fact that higher-ability people get more education and earn more.</p></li>
</ol>
<p><strong>Regression Interpretation Questions:</strong></p>
<ol start="24" type="a">
<li>The coefficient on sqft is 0.15, meaning each additional square foot is associated with $150 more (since price is in $1000s). For 100 square feet: <span class="math inline">\(100 \times 0.15 = 15\)</span>, which is $15,000.</li>
</ol>
<ol start="11" type="i">
<li><p>The coefficient on bedrooms has a ceteris paribus interpretation: holding square footage and bathrooms constant, an additional bedroom is associated with $8,720 lower price. This doesn’t mean bedrooms reduce prices overall—it’s the partial effect.</p></li>
<li><p>The key is “holding square footage constant.” If total space is fixed, adding a bedroom means dividing that space into more (smaller) rooms. Buyers may prefer fewer, larger rooms to more cramped ones. This illustrates why we must interpret multivariate coefficients carefully—they hold other variables constant.</p></li>
<li><p>The coefficient on hours_studied is 0.045, so 10 additional hours predicts: <span class="math inline">\(10 \times 0.045 = 0.45\)</span> standard deviations higher. Since the outcome is standardized, we interpret in standard deviation units.</p></li>
<li><p>The coefficient on parent_college (0.312) is the difference in predicted test scores between students with and without college-educated parents, holding study hours and free lunch status constant. Since test scores are standardized, this is 0.312 standard deviations.</p></li>
<li><p>The naive coefficient (0.062) is larger than the controlled coefficient (0.045) because of omitted variable bias. Students from advantaged backgrounds (college-educated parents, higher income) likely study more AND have other advantages (better schools, tutoring, resources) that boost scores. The naive estimate conflates the effect of studying with these background advantages.</p></li>
</ol>
</div>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-wooldridge_introductory_2019" class="csl-entry" role="listitem">
Wooldridge, Jeffrey M. 2019. <em>Introductory Econometrics: A Modern Approach</em>. 7th ed. Cengage Learning.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/bivariate_ols.html" class="pagination-link" aria-label="Bivariate Regression and Ordinary Least Squares">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bivariate Regression and Ordinary Least Squares</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/statistical_inference.html" class="pagination-link" aria-label="Statistical Inference">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Statistical Inference</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><span class="faux-block"> © 2025-2026 Raymond Caraher. All rights reserved. </span></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>