<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Multivariate Regression – EC325 Workbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/unit5.html" rel="next">
<link href="../chapters/unit3.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/unit4.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Multivariate Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">EC325 Workbook</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../EC325-Workbook.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../EC325-Workbook.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Good Data Practices</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Causality and Randomized Control Trials</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bivariate Regression and Ordinary Least Squares</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit4.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Multivariate Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dummy Variables and Non-Linear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/unit7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Interaction Effects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/heteroskedasticity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Heteroskedasticity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/panel_fe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Panel Data and Fixed Effects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/did.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Difference-in-Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/advanced_did.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Advanced Difference-in-Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/instrumental_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Instrumental Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/installingR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Intro to R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/statsreview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Statistics and Probability Review</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-problem-with-bivariate-ols" id="toc-the-problem-with-bivariate-ols" class="nav-link active" data-scroll-target="#the-problem-with-bivariate-ols"><span class="header-section-number">5.1</span> The Problem with Bivariate OLS</a></li>
  <li><a href="#the-multivariate-solution" id="toc-the-multivariate-solution" class="nav-link" data-scroll-target="#the-multivariate-solution"><span class="header-section-number">5.2</span> The Multivariate Solution</a>
  <ul class="collapse">
  <li><a href="#the-general-multivariate-model" id="toc-the-general-multivariate-model" class="nav-link" data-scroll-target="#the-general-multivariate-model"><span class="header-section-number">5.2.1</span> The General Multivariate Model</a></li>
  <li><a href="#interpreting-coefficients" id="toc-interpreting-coefficients" class="nav-link" data-scroll-target="#interpreting-coefficients"><span class="header-section-number">5.2.2</span> Interpreting Coefficients</a></li>
  <li><a href="#the-zero-conditional-mean-assumption" id="toc-the-zero-conditional-mean-assumption" class="nav-link" data-scroll-target="#the-zero-conditional-mean-assumption"><span class="header-section-number">5.2.3</span> The Zero Conditional Mean Assumption</a></li>
  </ul></li>
  <li><a href="#deriving-the-multivariate-ols-estimator" id="toc-deriving-the-multivariate-ols-estimator" class="nav-link" data-scroll-target="#deriving-the-multivariate-ols-estimator"><span class="header-section-number">5.3</span> Deriving the Multivariate OLS Estimator</a>
  <ul class="collapse">
  <li><a href="#the-minimization-problem" id="toc-the-minimization-problem" class="nav-link" data-scroll-target="#the-minimization-problem"><span class="header-section-number">5.3.1</span> The Minimization Problem</a></li>
  <li><a href="#first-order-conditions" id="toc-first-order-conditions" class="nav-link" data-scroll-target="#first-order-conditions"><span class="header-section-number">5.3.2</span> First-Order Conditions</a></li>
  </ul></li>
  <li><a href="#estimating-multivariate-ols-in-r" id="toc-estimating-multivariate-ols-in-r" class="nav-link" data-scroll-target="#estimating-multivariate-ols-in-r"><span class="header-section-number">5.4</span> Estimating Multivariate OLS in R</a>
  <ul class="collapse">
  <li><a href="#example-mpg-horsepower-and-weight" id="toc-example-mpg-horsepower-and-weight" class="nav-link" data-scroll-target="#example-mpg-horsepower-and-weight"><span class="header-section-number">5.4.1</span> Example: MPG, Horsepower, and Weight</a></li>
  <li><a href="#interpreting-the-results" id="toc-interpreting-the-results" class="nav-link" data-scroll-target="#interpreting-the-results"><span class="header-section-number">5.4.2</span> Interpreting the Results</a></li>
  </ul></li>
  <li><a href="#multivariate-ols-as-matching" id="toc-multivariate-ols-as-matching" class="nav-link" data-scroll-target="#multivariate-ols-as-matching"><span class="header-section-number">5.5</span> Multivariate OLS as Matching</a>
  <ul class="collapse">
  <li><a href="#the-returns-to-education-example" id="toc-the-returns-to-education-example" class="nav-link" data-scroll-target="#the-returns-to-education-example"><span class="header-section-number">5.5.1</span> The Returns to Education Example</a></li>
  <li><a href="#the-naive-comparison" id="toc-the-naive-comparison" class="nav-link" data-scroll-target="#the-naive-comparison"><span class="header-section-number">5.5.2</span> The Naive Comparison</a></li>
  <li><a href="#step-1-compute-within-industry-differences" id="toc-step-1-compute-within-industry-differences" class="nav-link" data-scroll-target="#step-1-compute-within-industry-differences"><span class="header-section-number">5.5.3</span> Step 1: Compute Within-Industry Differences</a></li>
  <li><a href="#step-2-compute-weights" id="toc-step-2-compute-weights" class="nav-link" data-scroll-target="#step-2-compute-weights"><span class="header-section-number">5.5.4</span> Step 2: Compute Weights</a></li>
  <li><a href="#step-3-compute-weighted-average" id="toc-step-3-compute-weighted-average" class="nav-link" data-scroll-target="#step-3-compute-weighted-average"><span class="header-section-number">5.5.5</span> Step 3: Compute Weighted Average</a></li>
  <li><a href="#the-regression-equivalent" id="toc-the-regression-equivalent" class="nav-link" data-scroll-target="#the-regression-equivalent"><span class="header-section-number">5.5.6</span> The Regression Equivalent</a></li>
  </ul></li>
  <li><a href="#goodness-of-fit-adjusted-r-squared" id="toc-goodness-of-fit-adjusted-r-squared" class="nav-link" data-scroll-target="#goodness-of-fit-adjusted-r-squared"><span class="header-section-number">5.6</span> Goodness-of-Fit: Adjusted R-Squared</a>
  <ul class="collapse">
  <li><a href="#the-problem-with-r-squared" id="toc-the-problem-with-r-squared" class="nav-link" data-scroll-target="#the-problem-with-r-squared"><span class="header-section-number">5.6.1</span> The Problem with R-Squared</a></li>
  <li><a href="#the-adjusted-r-squared" id="toc-the-adjusted-r-squared" class="nav-link" data-scroll-target="#the-adjusted-r-squared"><span class="header-section-number">5.6.2</span> The Adjusted R-Squared</a></li>
  </ul></li>
  <li><a href="#gauss-markov-assumptions-for-multivariate-ols" id="toc-gauss-markov-assumptions-for-multivariate-ols" class="nav-link" data-scroll-target="#gauss-markov-assumptions-for-multivariate-ols"><span class="header-section-number">5.7</span> Gauss-Markov Assumptions for Multivariate OLS</a>
  <ul class="collapse">
  <li><a href="#assumption-1-linear-in-parameters" id="toc-assumption-1-linear-in-parameters" class="nav-link" data-scroll-target="#assumption-1-linear-in-parameters"><span class="header-section-number">5.7.1</span> Assumption 1: Linear in Parameters</a></li>
  <li><a href="#assumption-2-random-sampling" id="toc-assumption-2-random-sampling" class="nav-link" data-scroll-target="#assumption-2-random-sampling"><span class="header-section-number">5.7.2</span> Assumption 2: Random Sampling</a></li>
  <li><a href="#assumption-3-no-perfect-multicollinearity" id="toc-assumption-3-no-perfect-multicollinearity" class="nav-link" data-scroll-target="#assumption-3-no-perfect-multicollinearity"><span class="header-section-number">5.7.3</span> Assumption 3: No Perfect Multicollinearity</a></li>
  <li><a href="#assumption-4-zero-conditional-mean" id="toc-assumption-4-zero-conditional-mean" class="nav-link" data-scroll-target="#assumption-4-zero-conditional-mean"><span class="header-section-number">5.7.4</span> Assumption 4: Zero Conditional Mean</a></li>
  <li><a href="#assumption-5-homoskedasticity" id="toc-assumption-5-homoskedasticity" class="nav-link" data-scroll-target="#assumption-5-homoskedasticity"><span class="header-section-number">5.7.5</span> Assumption 5: Homoskedasticity</a></li>
  </ul></li>
  <li><a href="#the-omitted-variable-bias-formula" id="toc-the-omitted-variable-bias-formula" class="nav-link" data-scroll-target="#the-omitted-variable-bias-formula"><span class="header-section-number">5.8</span> The Omitted Variable Bias Formula</a>
  <ul class="collapse">
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">5.8.1</span> Setup</a></li>
  <li><a href="#the-ovb-formula" id="toc-the-ovb-formula" class="nav-link" data-scroll-target="#the-ovb-formula"><span class="header-section-number">5.8.2</span> The OVB Formula</a></li>
  <li><a href="#interpreting-the-bias-formula" id="toc-interpreting-the-bias-formula" class="nav-link" data-scroll-target="#interpreting-the-bias-formula"><span class="header-section-number">5.8.3</span> Interpreting the Bias Formula</a></li>
  <li><a href="#example-education-wages-and-ability" id="toc-example-education-wages-and-ability" class="nav-link" data-scroll-target="#example-education-wages-and-ability"><span class="header-section-number">5.8.4</span> Example: Education, Wages, and Ability</a></li>
  <li><a href="#example-policing-crime-and-poverty" id="toc-example-policing-crime-and-poverty" class="nav-link" data-scroll-target="#example-policing-crime-and-poverty"><span class="header-section-number">5.8.5</span> Example: Policing, Crime, and Poverty</a></li>
  </ul></li>
  <li><a href="#variance-in-multivariate-ols" id="toc-variance-in-multivariate-ols" class="nav-link" data-scroll-target="#variance-in-multivariate-ols"><span class="header-section-number">5.9</span> Variance in Multivariate OLS</a>
  <ul class="collapse">
  <li><a href="#what-increases-variance" id="toc-what-increases-variance" class="nav-link" data-scroll-target="#what-increases-variance"><span class="header-section-number">5.9.1</span> What Increases Variance?</a></li>
  <li><a href="#standard-errors" id="toc-standard-errors" class="nav-link" data-scroll-target="#standard-errors"><span class="header-section-number">5.9.2</span> Standard Errors</a></li>
  </ul></li>
  <li><a href="#the-bias-variance-tradeoff" id="toc-the-bias-variance-tradeoff" class="nav-link" data-scroll-target="#the-bias-variance-tradeoff"><span class="header-section-number">5.10</span> The Bias-Variance Tradeoff</a>
  <ul class="collapse">
  <li><a href="#the-costs-of-omitting-a-relevant-variable" id="toc-the-costs-of-omitting-a-relevant-variable" class="nav-link" data-scroll-target="#the-costs-of-omitting-a-relevant-variable"><span class="header-section-number">5.10.1</span> The Costs of Omitting a Relevant Variable</a></li>
  <li><a href="#the-costs-of-including-an-irrelevant-variable" id="toc-the-costs-of-including-an-irrelevant-variable" class="nav-link" data-scroll-target="#the-costs-of-including-an-irrelevant-variable"><span class="header-section-number">5.10.2</span> The Costs of Including an Irrelevant Variable</a></li>
  <li><a href="#the-tradeoff" id="toc-the-tradeoff" class="nav-link" data-scroll-target="#the-tradeoff"><span class="header-section-number">5.10.3</span> The Tradeoff</a></li>
  <li><a href="#practical-guidance" id="toc-practical-guidance" class="nav-link" data-scroll-target="#practical-guidance"><span class="header-section-number">5.10.4</span> Practical Guidance</a></li>
  </ul></li>
  <li><a href="#simulation-bias-vs.-variance" id="toc-simulation-bias-vs.-variance" class="nav-link" data-scroll-target="#simulation-bias-vs.-variance"><span class="header-section-number">5.11</span> Simulation: Bias vs.&nbsp;Variance</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">5.12</span> Summary</a>
  <ul class="collapse">
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways"><span class="header-section-number">5.12.1</span> Key Takeaways</a></li>
  </ul></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding"><span class="header-section-number">5.13</span> Check Your Understanding</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-multivariate" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Multivariate Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>



<style>
.problem {
    background-color: #f8f9fa;
    border: 1px solid #dee2e6;
    border-radius: 8px;
    padding: 20px;
    margin: 20px 0;
}
.context {
    background-color: #e8f4f8;
    padding: 12px;
    border-radius: 5px;
    margin-bottom: 15px;
    border-left: 4px solid #2874a6;
}
.question {
    margin: 15px 0;
    padding: 10px;
    background-color: #fff3cd;
    border-radius: 5px;
}
.answer-row {
    display: flex;
    align-items: center;
    margin: 10px 0;
    flex-wrap: wrap;
    gap: 10px;
}
.answer-row label {
    min-width: 320px;
    font-weight: 500;
}
select {
    padding: 8px 12px;
    font-size: 14px;
    border: 2px solid #ccc;
    border-radius: 5px;
    min-width: 300px;
    cursor: pointer;
}
select:focus {
    border-color: #2874a6;
    outline: none;
}
.correct {
    border-color: #28a745 !important;
    background-color: #d4edda !important;
}
.incorrect {
    border-color: #dc3545 !important;
    background-color: #f8d7da !important;
}
.explanation {
    margin-top: 10px;
    padding: 15px;
    background-color: #e7f3ff;
    border-radius: 5px;
    border-left: 4px solid #2874a6;
}
.note {
    font-size: 0.85em;
    color: #666;
    font-style: italic;
}
</style>

<script>
function checkAnswer(selectElement, correctValue) {
    if (selectElement.value === '') {
        selectElement.classList.remove('correct', 'incorrect');
    } else if (selectElement.value === correctValue) {
        selectElement.classList.remove('incorrect');
        selectElement.classList.add('correct');
    } else {
        selectElement.classList.remove('correct');
        selectElement.classList.add('incorrect');
    }
}
</script>

<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>Key Questions</strong>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Why do we need multivariate regression?</li>
<li>How do we interpret coefficients when there are multiple independent variables?</li>
<li>What is the zero conditional mean assumption in the multivariate case?</li>
<li>How does multivariate OLS function as a “matching” estimator?</li>
<li>What is the omitted variable bias formula and how do we use it?</li>
<li>What is the bias-variance tradeoff when deciding which controls to include?</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>Suggested Readings</strong>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><span class="citation" data-cites="wooldridge_introductory_2019">Wooldridge (<a href="references.html#ref-wooldridge_introductory_2019" role="doc-biblioref">2019</a>)</span>, Ch. 3</li>
</ul>
</div>
</div>
</div>
<p>In <a href="unit3.html" class="quarto-xref"><span>Chapter 4</span></a>, we introduced bivariate OLS and saw that causal interpretation requires the zero conditional mean assumption: <span class="math inline">\(E[\mu | x] = 0\)</span>. We also saw that this assumption is frequently violated due to omitted variables—factors in the error term that are correlated with both <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</p>
<p>This chapter introduces <strong>multivariate OLS</strong>, which allows us to explicitly control for confounding variables. By including additional variables on the right-hand side of our regression, we can make the zero conditional mean assumption more plausible and get closer to causal estimates.</p>
<section id="the-problem-with-bivariate-ols" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="the-problem-with-bivariate-ols"><span class="header-section-number">5.1</span> The Problem with Bivariate OLS</h2>
<p>Let’s revisit why bivariate OLS often fails to give us causal estimates.</p>
<p>Consider a regression of wages on education:</p>
<p><span class="math display">\[
wage = \beta_0 + \beta_1 \cdot educ + \mu
\]</span></p>
<p>For <span class="math inline">\(\hat{\beta}_1\)</span> to be an unbiased estimate of the causal effect of education, we need <span class="math inline">\(E[\mu | educ] = 0\)</span>. But the error term <span class="math inline">\(\mu\)</span> contains everything else that affects wages: ability, family connections, motivation, and countless other factors.</p>
<p>Many of these factors are likely correlated with education. For example, people from wealthier families tend to get more education (better schools, tutors, college is affordable) <em>and</em> earn higher wages (family connections, inherited wealth). If family income is in <span class="math inline">\(\mu\)</span> and correlated with education, then <span class="math inline">\(E[\mu | educ] \neq 0\)</span>, and our estimate is biased.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The Core Problem
</div>
</div>
<div class="callout-body-container callout-body">
<p>With bivariate OLS, the zero conditional mean assumption requires that <em>all</em> factors affecting <span class="math inline">\(y\)</span> (other than <span class="math inline">\(x\)</span>) be uncorrelated with <span class="math inline">\(x\)</span>. This is almost never plausible in observational data.</p>
</div>
</div>
</section>
<section id="the-multivariate-solution" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="the-multivariate-solution"><span class="header-section-number">5.2</span> The Multivariate Solution</h2>
<p>Multivariate OLS offers a solution: <strong>explicitly control</strong> for variables that might be confounders.</p>
<p>If we’re worried that family income confounds the education-wage relationship, we can include it in our model:</p>
<p><span class="math display">\[
wage = \beta_0 + \beta_1 \cdot educ + \beta_2 \cdot family\_income + \mu
\]</span></p>
<p>Now <span class="math inline">\(\beta_1\)</span> represents the effect of education on wages <strong>holding family income constant</strong>. The error term <span class="math inline">\(\mu\)</span> no longer contains family income, so that source of bias is eliminated.</p>
<section id="the-general-multivariate-model" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="the-general-multivariate-model"><span class="header-section-number">5.2.1</span> The General Multivariate Model</h3>
<p>The general multivariate linear regression model with <span class="math inline">\(k\)</span> independent variables is:</p>
<p><span id="eq-multivariate"><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_k x_k + \mu
\tag{5.1}\]</span></span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(y\)</span> is the dependent variable</li>
<li><span class="math inline">\(x_1, x_2, \ldots, x_k\)</span> are the independent variables</li>
<li><span class="math inline">\(\beta_0\)</span> is the intercept</li>
<li><span class="math inline">\(\beta_j\)</span> is the coefficient on <span class="math inline">\(x_j\)</span> (for <span class="math inline">\(j = 1, 2, \ldots, k\)</span>)</li>
<li><span class="math inline">\(\mu\)</span> is the error term containing all factors not included in the model</li>
</ul>
</section>
<section id="interpreting-coefficients" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="interpreting-coefficients"><span class="header-section-number">5.2.2</span> Interpreting Coefficients</h3>
<p>In multivariate regression, each coefficient has a <strong>ceteris paribus</strong> interpretation:</p>
<p><span class="math display">\[
\beta_j = \frac{\partial y}{\partial x_j}
\]</span></p>
<p>This is the change in <span class="math inline">\(y\)</span> associated with a one-unit increase in <span class="math inline">\(x_j\)</span>, <strong>holding all other independent variables constant</strong>.</p>
<p>For example, in the model:</p>
<p><span class="math display">\[
wage = \beta_0 + \beta_1 \cdot educ + \beta_2 \cdot family\_income + \mu
\]</span></p>
<ul>
<li><span class="math inline">\(\beta_1\)</span>: The change in wages for one additional year of education, <strong>holding family income constant</strong></li>
<li><span class="math inline">\(\beta_2\)</span>: The change in wages for one additional dollar of family income, <strong>holding education constant</strong></li>
</ul>
</section>
<section id="the-zero-conditional-mean-assumption" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="the-zero-conditional-mean-assumption"><span class="header-section-number">5.2.3</span> The Zero Conditional Mean Assumption</h3>
<p>In multivariate OLS, the zero conditional mean assumption becomes:</p>
<p><span class="math display">\[
E[\mu | x_1, x_2, \ldots, x_k] = 0
\]</span></p>
<p>This states that the average of unobserved factors is zero for <em>all unique combinations</em> of the independent variables. In other words, everything in <span class="math inline">\(\mu\)</span> must be uncorrelated with <em>all</em> the variables we’ve included.</p>
<p>This assumption is much more plausible than its bivariate counterpart. By including relevant control variables, we’ve removed them from <span class="math inline">\(\mu\)</span>, making it more likely that what remains is uncorrelated with our variables of interest.</p>
</section>
</section>
<section id="deriving-the-multivariate-ols-estimator" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="deriving-the-multivariate-ols-estimator"><span class="header-section-number">5.3</span> Deriving the Multivariate OLS Estimator</h2>
<p>The derivation follows the same logic as bivariate OLS: we minimize the sum of squared residuals.</p>
<section id="the-minimization-problem" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="the-minimization-problem"><span class="header-section-number">5.3.1</span> The Minimization Problem</h3>
<p>Given a sample of <span class="math inline">\(n\)</span> observations, we want to find values <span class="math inline">\(\hat{\beta}_0, \hat{\beta}_1, \ldots, \hat{\beta}_k\)</span> that minimize:</p>
<p><span class="math display">\[
SSR = \sum_{i=1}^{n} (y_i - \hat{\beta}_0 - \hat{\beta}_1 x_{1i} - \hat{\beta}_2 x_{2i} - \cdots - \hat{\beta}_k x_{ki})^2
\]</span></p>
</section>
<section id="first-order-conditions" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="first-order-conditions"><span class="header-section-number">5.3.2</span> First-Order Conditions</h3>
<p>Taking partial derivatives with respect to each <span class="math inline">\(\hat{\beta}_j\)</span> and setting them equal to zero yields <span class="math inline">\(k + 1\)</span> first-order conditions:</p>
<p><span class="math display">\[
\sum_{i=1}^{n}(y_i - \hat{\beta}_0 - \hat{\beta}_1 x_{1i} - \cdots - \hat{\beta}_k x_{ki}) = 0
\]</span></p>
<p><span class="math display">\[
\sum_{i=1}^{n} x_{1i}(y_i - \hat{\beta}_0 - \hat{\beta}_1 x_{1i} - \cdots - \hat{\beta}_k x_{ki}) = 0
\]</span></p>
<p><span class="math display">\[
\vdots
\]</span></p>
<p><span class="math display">\[
\sum_{i=1}^{n} x_{ki}(y_i - \hat{\beta}_0 - \hat{\beta}_1 x_{1i} - \cdots - \hat{\beta}_k x_{ki}) = 0
\]</span></p>
<p>Solving this system of equations yields the OLS estimates. The algebra is tedious (and typically handled with matrix methods), so we won’t derive the explicit formulas here. Fortunately, your computer does this effortlessly.</p>
</section>
</section>
<section id="estimating-multivariate-ols-in-r" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="estimating-multivariate-ols-in-r"><span class="header-section-number">5.4</span> Estimating Multivariate OLS in R</h2>
<p>In R, we estimate multivariate regression using the same <code>lm()</code> function, simply adding variables with the <code>+</code> symbol.</p>
<section id="example-mpg-horsepower-and-weight" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="example-mpg-horsepower-and-weight"><span class="header-section-number">5.4.1</span> Example: MPG, Horsepower, and Weight</h3>
<p>Let’s estimate the effect of horsepower on fuel efficiency, first without and then with a control for vehicle weight.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Bivariate regression</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>lm_bivariate <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> mtcars)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Multivariate regression (adding weight as control)</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>lm_multivariate <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp <span class="sc">+</span> wt, <span class="at">data =</span> mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Bivariate results:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_bivariate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.7121 -2.1122 -0.8854  1.5819  8.2360 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 30.09886    1.63392  18.421  &lt; 2e-16 ***
hp          -0.06823    0.01012  -6.742 1.79e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.863 on 30 degrees of freedom
Multiple R-squared:  0.6024,    Adjusted R-squared:  0.5892 
F-statistic: 45.46 on 1 and 30 DF,  p-value: 1.788e-07</code></pre>
</div>
</div>
<p><strong>Multivariate results:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_multivariate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp + wt, data = mtcars)

Residuals:
   Min     1Q Median     3Q    Max 
-3.941 -1.600 -0.182  1.050  5.854 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 37.22727    1.59879  23.285  &lt; 2e-16 ***
hp          -0.03177    0.00903  -3.519  0.00145 ** 
wt          -3.87783    0.63273  -6.129 1.12e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.593 on 29 degrees of freedom
Multiple R-squared:  0.8268,    Adjusted R-squared:  0.8148 
F-statistic: 69.21 on 2 and 29 DF,  p-value: 9.109e-12</code></pre>
</div>
</div>
</section>
<section id="interpreting-the-results" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="interpreting-the-results"><span class="header-section-number">5.4.2</span> Interpreting the Results</h3>
<p>In the <strong>bivariate</strong> regression, the coefficient on horsepower is <span class="math inline">\(-0.068\)</span>: each additional unit of horsepower is associated with 0.068 fewer miles per gallon.</p>
<p>In the <strong>multivariate</strong> regression (controlling for weight), the coefficient on horsepower drops to <span class="math inline">\(-0.032\)</span>—less than half the size!</p>
<p>What happened? Horsepower and weight are positively correlated (more powerful engines tend to be in heavier vehicles), and weight independently reduces fuel efficiency. The bivariate estimate was conflating the effect of horsepower with the effect of weight. Once we control for weight, we isolate the effect of horsepower alone.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What Changed?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The coefficient on <code>hp</code> dropped from <span class="math inline">\(-0.068\)</span> to <span class="math inline">\(-0.032\)</span> when we added <code>wt</code>. This suggests that much of what appeared to be the “effect” of horsepower was actually the effect of weight. This is precisely what controlling for confounders accomplishes.</p>
</div>
</div>
</section>
</section>
<section id="multivariate-ols-as-matching" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="multivariate-ols-as-matching"><span class="header-section-number">5.5</span> Multivariate OLS as Matching</h2>
<p>There’s an intuitive way to understand what multivariate OLS does: it’s essentially a <strong>matching</strong> estimator. When we “control for” a variable, we’re comparing observations that have similar values of that control variable.</p>
<section id="the-returns-to-education-example" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="the-returns-to-education-example"><span class="header-section-number">5.5.1</span> The Returns to Education Example</h3>
<p>Suppose we want to estimate the effect of education on wages. A simple comparison of average wages across education levels might be misleading because people with more education tend to work in higher-paying industries. Part of the apparent “return to education” might actually be an “industry premium.”</p>
<p>Let’s work through this with simulated data to see exactly how controlling for industry works.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate wage data</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">2000</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create data where:</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># - More educated workers are more likely to be in high-paying industries</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># - Industry independently affects wages</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>wage_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Education: 1 = HS, 2 = Some College, 3 = Bachelor's+</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">educ_years =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">14</span>, <span class="dv">16</span>), n, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.4</span>, <span class="fl">0.3</span>, <span class="fl">0.3</span>)),</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Higher education -&gt; more likely in professional services (high pay industry)</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">ind_professional =</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="at">prob =</span> <span class="fu">case_when</span>(</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    educ_years <span class="sc">==</span> <span class="dv">12</span> <span class="sc">~</span> <span class="fl">0.20</span>,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    educ_years <span class="sc">==</span> <span class="dv">14</span> <span class="sc">~</span> <span class="fl">0.40</span>,</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    educ_years <span class="sc">==</span> <span class="dv">16</span> <span class="sc">~</span> <span class="fl">0.65</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  )),</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Wages depend on education AND industry</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">wage =</span> <span class="dv">25000</span> <span class="sc">+</span> </span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    <span class="dv">3000</span> <span class="sc">*</span> (educ_years <span class="sc">-</span> <span class="dv">12</span>) <span class="sc">+</span>     <span class="co"># True education effect: $3000 per year</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    <span class="dv">15000</span> <span class="sc">*</span> ind_professional <span class="sc">+</span>      <span class="co"># Industry premium: $15000</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">8000</span>)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">educ_cat =</span> <span class="fu">case_when</span>(</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>      educ_years <span class="sc">==</span> <span class="dv">12</span> <span class="sc">~</span> <span class="st">"HS Only"</span>,</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>      educ_years <span class="sc">==</span> <span class="dv">14</span> <span class="sc">~</span> <span class="st">"Some College"</span>, </span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>      educ_years <span class="sc">==</span> <span class="dv">16</span> <span class="sc">~</span> <span class="st">"Bachelor's+"</span></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">industry =</span> <span class="fu">ifelse</span>(ind_professional <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Professional"</span>, <span class="st">"Other"</span>)</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-naive-comparison" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="the-naive-comparison"><span class="header-section-number">5.5.2</span> The Naive Comparison</h3>
<p>First, let’s compute average wages by education level without any controls:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>naive_means <span class="ot">&lt;-</span> wage_data <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(educ_cat, educ_years) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_wage =</span> <span class="fu">mean</span>(wage), <span class="at">n =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(educ_years)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>naive_means <span class="sc">|&gt;</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Education"</span>, <span class="st">"Years"</span>, <span class="st">"Avg Wage ($)"</span>, <span class="st">"N"</span>),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">0</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Education</th>
<th style="text-align: right;">Years</th>
<th style="text-align: right;">Avg Wage ($)</th>
<th style="text-align: right;">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">HS Only</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">28575</td>
<td style="text-align: right;">829</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some College</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">36961</td>
<td style="text-align: right;">604</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bachelor’s+</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">46341</td>
<td style="text-align: right;">567</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The naive comparison suggests that going from high school to some college is associated with about $8,386 higher wages, and going from high school to a bachelor’s degree is associated with about $17,766 higher wages.</p>
<p>But wait—the true effect of education in our simulation is only $3,000 per year (so $6,000 for 2 extra years and $12,000 for 4 extra years). The naive estimates are too large! This is because more educated workers are more likely to be in high-paying industries.</p>
</section>
<section id="step-1-compute-within-industry-differences" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="step-1-compute-within-industry-differences"><span class="header-section-number">5.5.3</span> Step 1: Compute Within-Industry Differences</h3>
<p>To control for industry, we first compute average wages separately for each education-industry combination:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>cell_means <span class="ot">&lt;-</span> wage_data <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(industry, educ_cat, educ_years) <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_wage =</span> <span class="fu">mean</span>(wage), <span class="at">n =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(industry, educ_years)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>cell_means <span class="sc">|&gt;</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(industry, educ_cat, avg_wage, n) <span class="sc">|&gt;</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Industry"</span>, <span class="st">"Education"</span>, <span class="st">"Avg Wage ($)"</span>, <span class="st">"N"</span>),</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">0</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-matching-detailed" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-matching-detailed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.1: Average wages by education and industry
</figcaption>
<div aria-describedby="tbl-matching-detailed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Industry</th>
<th style="text-align: left;">Education</th>
<th style="text-align: right;">Avg Wage ($)</th>
<th style="text-align: right;">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Other</td>
<td style="text-align: left;">HS Only</td>
<td style="text-align: right;">25275</td>
<td style="text-align: right;">648</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Some College</td>
<td style="text-align: right;">30351</td>
<td style="text-align: right;">349</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Bachelor’s+</td>
<td style="text-align: right;">36802</td>
<td style="text-align: right;">199</td>
</tr>
<tr class="even">
<td style="text-align: left;">Professional</td>
<td style="text-align: left;">HS Only</td>
<td style="text-align: right;">40388</td>
<td style="text-align: right;">181</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Professional</td>
<td style="text-align: left;">Some College</td>
<td style="text-align: right;">46008</td>
<td style="text-align: right;">255</td>
</tr>
<tr class="even">
<td style="text-align: left;">Professional</td>
<td style="text-align: left;">Bachelor’s+</td>
<td style="text-align: right;">51499</td>
<td style="text-align: right;">368</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Now let’s compute the wage differences <strong>within</strong> each industry:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>within_industry <span class="ot">&lt;-</span> cell_means <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(industry) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_from_hs =</span> avg_wage <span class="sc">-</span> avg_wage[educ_years <span class="sc">==</span> <span class="dv">12</span>]</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(educ_years <span class="sc">&gt;</span> <span class="dv">12</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(industry, educ_cat, diff_from_hs, n)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>within_industry <span class="sc">|&gt;</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Industry"</span>, <span class="st">"Education"</span>, <span class="st">"Wage Diff vs HS ($)"</span>, <span class="st">"N in Cell"</span>),</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">0</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Industry</th>
<th style="text-align: left;">Education</th>
<th style="text-align: right;">Wage Diff vs HS ($)</th>
<th style="text-align: right;">N in Cell</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Some College</td>
<td style="text-align: right;">5076</td>
<td style="text-align: right;">349</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Bachelor’s+</td>
<td style="text-align: right;">11527</td>
<td style="text-align: right;">199</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Professional</td>
<td style="text-align: left;">Some College</td>
<td style="text-align: right;">5620</td>
<td style="text-align: right;">255</td>
</tr>
<tr class="even">
<td style="text-align: left;">Professional</td>
<td style="text-align: left;">Bachelor’s+</td>
<td style="text-align: right;">11110</td>
<td style="text-align: right;">368</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Notice that the within-industry differences are much closer to the true values ($6,000 for Some College, $12,000 for Bachelor’s+).</p>
</section>
<section id="step-2-compute-weights" class="level3" data-number="5.5.4">
<h3 data-number="5.5.4" class="anchored" data-anchor-id="step-2-compute-weights"><span class="header-section-number">5.5.4</span> Step 2: Compute Weights</h3>
<p>To combine these within-industry estimates into a single number, we take a <strong>weighted average</strong>. The weights are based on the number of observations in each industry:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Total workers in each industry</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>industry_totals <span class="ot">&lt;-</span> wage_data <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(industry) <span class="sc">|&gt;</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weight =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>industry_totals <span class="sc">|&gt;</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Industry"</span>, <span class="st">"N"</span>, <span class="st">"Weight"</span>),</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">3</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Industry</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Other</td>
<td style="text-align: right;">1196</td>
<td style="text-align: right;">0.598</td>
</tr>
<tr class="even">
<td style="text-align: left;">Professional</td>
<td style="text-align: right;">804</td>
<td style="text-align: right;">0.402</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="step-3-compute-weighted-average" class="level3" data-number="5.5.5">
<h3 data-number="5.5.5" class="anchored" data-anchor-id="step-3-compute-weighted-average"><span class="header-section-number">5.5.5</span> Step 3: Compute Weighted Average</h3>
<p>Now we combine the within-industry differences using these weights. Let’s do this for the Bachelor’s+ vs HS comparison:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the within-industry differences for Bachelor's+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>ba_diffs <span class="ot">&lt;-</span> within_industry <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(educ_cat <span class="sc">==</span> <span class="st">"Bachelor's+"</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(industry_totals, <span class="at">by =</span> <span class="st">"industry"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>ba_diffs <span class="sc">|&gt;</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(industry, diff_from_hs, weight) <span class="sc">|&gt;</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Industry"</span>, <span class="st">"Within-Industry Diff ($)"</span>, <span class="st">"Weight"</span>),</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Industry</th>
<th style="text-align: right;">Within-Industry Diff ($)</th>
<th style="text-align: right;">Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Other</td>
<td style="text-align: right;">11527</td>
<td style="text-align: right;">0.598</td>
</tr>
<tr class="even">
<td style="text-align: left;">Professional</td>
<td style="text-align: right;">11110</td>
<td style="text-align: right;">0.402</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Weighted average</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>weighted_avg <span class="ot">&lt;-</span> <span class="fu">sum</span>(ba_diffs<span class="sc">$</span>diff_from_hs <span class="sc">*</span> ba_diffs<span class="sc">$</span>weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The weighted average is:</p>
<p><span class="math display">\[
(1.1527\times 10^{4} \times 0.598) + (1.111\times 10^{4} \times 0.402) = 11,360
\]</span></p>
<p>This is much closer to the true effect of $12,000!</p>
</section>
<section id="the-regression-equivalent" class="level3" data-number="5.5.6">
<h3 data-number="5.5.6" class="anchored" data-anchor-id="the-regression-equivalent"><span class="header-section-number">5.5.6</span> The Regression Equivalent</h3>
<p>Now let’s see what regression gives us:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create numeric education variable (years beyond HS)</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>wage_data <span class="ot">&lt;-</span> wage_data <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">educ_beyond_hs =</span> educ_years <span class="sc">-</span> <span class="dv">12</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression controlling for industry</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>lm_controlled <span class="ot">&lt;-</span> <span class="fu">lm</span>(wage <span class="sc">~</span> educ_beyond_hs <span class="sc">+</span> ind_professional, <span class="at">data =</span> wage_data)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_controlled)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wage ~ educ_beyond_hs + ind_professional, data = wage_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-25629.6  -5261.0     24.9   5383.0  27407.8 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       25179.3      275.7   91.33   &lt;2e-16 ***
educ_beyond_hs     2797.6      117.3   23.84   &lt;2e-16 ***
ind_professional  15180.2      394.9   38.44   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8075 on 1997 degrees of freedom
Multiple R-squared:  0.6093,    Adjusted R-squared:  0.6089 
F-statistic:  1557 on 2 and 1997 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The coefficient on <code>educ_beyond_hs</code> is approximately $3,000 per year—almost exactly the true value we built into the simulation!</p>
<p>Compare this to the naive regression without the industry control:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>lm_naive <span class="ot">&lt;-</span> <span class="fu">lm</span>(wage <span class="sc">~</span> educ_beyond_hs, <span class="at">data =</span> wage_data)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lm_naive)[<span class="st">"educ_beyond_hs"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>educ_beyond_hs 
      4427.053 </code></pre>
</div>
</div>
<p>The naive estimate (4,427) is inflated because it conflates the education effect with the industry premium.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Multivariate OLS as Matching
</div>
</div>
<div class="callout-body-container callout-body">
<p>When you include control variables, OLS is effectively:</p>
<ol type="1">
<li><strong>Grouping</strong> observations by similar values of the control variables</li>
<li><strong>Computing</strong> the relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> within each group</li>
<li><strong>Taking a weighted average</strong> across groups, where weights reflect group sizes</li>
</ol>
<p>This is why multivariate regression is sometimes called a “matching” estimator—we’re matching people who work in the same industry and comparing their wages based on education.</p>
</div>
</div>
</section>
</section>
<section id="goodness-of-fit-adjusted-r-squared" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="goodness-of-fit-adjusted-r-squared"><span class="header-section-number">5.6</span> Goodness-of-Fit: Adjusted R-Squared</h2>
<p>In bivariate OLS, we used <span class="math inline">\(R^2\)</span> to measure how much variation in <span class="math inline">\(y\)</span> our model explains. The same concept applies to multivariate OLS, but with an important caveat.</p>
<section id="the-problem-with-r-squared" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="the-problem-with-r-squared"><span class="header-section-number">5.6.1</span> The Problem with R-Squared</h3>
<p>The <span class="math inline">\(R^2\)</span> can never decrease when you add more variables—it can only increase or stay the same. This is because adding variables can only improve (or maintain) the fit, even if those variables are irrelevant.</p>
<p>This creates a problem: <span class="math inline">\(R^2\)</span> mechanically increases as you add more variables, potentially making a bloated model look better than a parsimonious one.</p>
</section>
<section id="the-adjusted-r-squared" class="level3" data-number="5.6.2">
<h3 data-number="5.6.2" class="anchored" data-anchor-id="the-adjusted-r-squared"><span class="header-section-number">5.6.2</span> The Adjusted R-Squared</h3>
<p>The <strong>adjusted R-squared</strong> penalizes for the number of parameters:</p>
<p><span class="math display">\[
\bar{R}^2 = 1 - \frac{(1 - R^2)(n - 1)}{n - k - 1}
\]</span></p>
<p>where <span class="math inline">\(n\)</span> is the sample size and <span class="math inline">\(k\)</span> is the number of independent variables.</p>
<p>The adjusted <span class="math inline">\(R^2\)</span>:</p>
<ul>
<li>Is always smaller than the regular <span class="math inline">\(R^2\)</span></li>
<li>Can decrease when you add irrelevant variables</li>
<li>Provides a better comparison between models with different numbers of variables</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare R-squared and Adjusted R-squared</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Bivariate R-sq"</span> <span class="ot">=</span> <span class="fu">summary</span>(lm_bivariate)<span class="sc">$</span>r.squared,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Bivariate Adj R-sq"</span> <span class="ot">=</span> <span class="fu">summary</span>(lm_bivariate)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Multivariate R-sq"</span> <span class="ot">=</span> <span class="fu">summary</span>(lm_multivariate)<span class="sc">$</span>r.squared,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Multivariate Adj R-sq"</span> <span class="ot">=</span> <span class="fu">summary</span>(lm_multivariate)<span class="sc">$</span>adj.r.squared</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Bivariate R-sq    Bivariate Adj R-sq     Multivariate R-sq 
            0.6024373             0.5891853             0.8267855 
Multivariate Adj R-sq 
            0.8148396 </code></pre>
</div>
</div>
</section>
</section>
<section id="gauss-markov-assumptions-for-multivariate-ols" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="gauss-markov-assumptions-for-multivariate-ols"><span class="header-section-number">5.7</span> Gauss-Markov Assumptions for Multivariate OLS</h2>
<p>The Gauss-Markov assumptions extend naturally to the multivariate case, with one important addition.</p>
<section id="assumption-1-linear-in-parameters" class="level3" data-number="5.7.1">
<h3 data-number="5.7.1" class="anchored" data-anchor-id="assumption-1-linear-in-parameters"><span class="header-section-number">5.7.1</span> Assumption 1: Linear in Parameters</h3>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_k x_k + \mu
\]</span></p>
<p>As in the bivariate case, we can transform variables to model non-linear relationships while maintaining linearity in parameters.</p>
</section>
<section id="assumption-2-random-sampling" class="level3" data-number="5.7.2">
<h3 data-number="5.7.2" class="anchored" data-anchor-id="assumption-2-random-sampling"><span class="header-section-number">5.7.2</span> Assumption 2: Random Sampling</h3>
<p>We have a random sample <span class="math inline">\(\{(x_{1i}, x_{2i}, \ldots, x_{ki}, y_i) : i = 1, \ldots, n\}\)</span> from the population.</p>
</section>
<section id="assumption-3-no-perfect-multicollinearity" class="level3" data-number="5.7.3">
<h3 data-number="5.7.3" class="anchored" data-anchor-id="assumption-3-no-perfect-multicollinearity"><span class="header-section-number">5.7.3</span> Assumption 3: No Perfect Multicollinearity</h3>
<p>This assumption has two parts:</p>
<ol type="1">
<li><strong>No constant variables:</strong> Each independent variable must have some variation in the sample</li>
<li><strong>No exact linear relationships:</strong> No independent variable can be a perfect linear function of other independent variables</li>
</ol>
<p>The second part is new and important in multivariate regression.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Perfect Multicollinearity
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Perfect multicollinearity</strong> occurs when one independent variable is an exact linear combination of others. Examples:</p>
<ul>
<li>Including both <code>family_income</code> and <code>family_income_thousands</code> (one is just the other divided by 1000)</li>
<li>Including <code>parent1_income</code>, <code>parent2_income</code>, and <code>family_income</code> when <code>family_income = parent1_income + parent2_income</code></li>
<li>Including dummy variables for all categories of a categorical variable plus an intercept</li>
</ul>
<p>When perfect multicollinearity exists, the OLS formulas break down (the system of equations has no unique solution). R will typically drop one of the collinear variables automatically and issue a warning.</p>
</div>
</div>
</section>
<section id="assumption-4-zero-conditional-mean" class="level3" data-number="5.7.4">
<h3 data-number="5.7.4" class="anchored" data-anchor-id="assumption-4-zero-conditional-mean"><span class="header-section-number">5.7.4</span> Assumption 4: Zero Conditional Mean</h3>
<p><span class="math display">\[
E[\mu | x_1, x_2, \ldots, x_k] = 0
\]</span></p>
<p>The error term has mean zero for all combinations of the independent variables. This can still fail due to:</p>
<ul>
<li>Omitted variables correlated with included variables</li>
<li>Wrong functional form</li>
<li>Measurement error in independent variables</li>
<li>Simultaneous causality</li>
</ul>
</section>
<section id="assumption-5-homoskedasticity" class="level3" data-number="5.7.5">
<h3 data-number="5.7.5" class="anchored" data-anchor-id="assumption-5-homoskedasticity"><span class="header-section-number">5.7.5</span> Assumption 5: Homoskedasticity</h3>
<p><span class="math display">\[
Var(\mu | x_1, x_2, \ldots, x_k) = \sigma^2
\]</span></p>
<p>The variance of the error term is constant across all combinations of independent variable values.</p>
</section>
</section>
<section id="the-omitted-variable-bias-formula" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="the-omitted-variable-bias-formula"><span class="header-section-number">5.8</span> The Omitted Variable Bias Formula</h2>
<p>Even when we can’t include an omitted variable (perhaps because it’s unobservable), we can still reason about the <strong>direction</strong> of the bias.</p>
<section id="setup" class="level3" data-number="5.8.1">
<h3 data-number="5.8.1" class="anchored" data-anchor-id="setup"><span class="header-section-number">5.8.1</span> Setup</h3>
<p>Suppose the true model is:</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \mu
\]</span></p>
<p>But we can’t observe <span class="math inline">\(x_2\)</span>, so we estimate the misspecified model:</p>
<p><span class="math display">\[
\tilde{y} = \tilde{\beta}_0 + \tilde{\beta}_1 x_1
\]</span></p>
<p>where the tilde (<span class="math inline">\(\tilde{}\)</span>) indicates estimates from the misspecified model.</p>
</section>
<section id="the-ovb-formula" class="level3" data-number="5.8.2">
<h3 data-number="5.8.2" class="anchored" data-anchor-id="the-ovb-formula"><span class="header-section-number">5.8.2</span> The OVB Formula</h3>
<p>It can be shown that:</p>
<p><span id="eq-ovb-formula"><span class="math display">\[
\tilde{\beta}_1 = \hat{\beta}_1 + \hat{\beta}_2 \tilde{\delta}_1
\tag{5.2}\]</span></span></p>
<p>where <span class="math inline">\(\tilde{\delta}_1\)</span> is the coefficient from regressing <span class="math inline">\(x_2\)</span> on <span class="math inline">\(x_1\)</span>:</p>
<p><span class="math display">\[
x_2 = \tilde{\delta}_0 + \tilde{\delta}_1 x_1 + \text{error}
\]</span></p>
<p>Taking expectations:</p>
<p><span class="math display">\[
E[\tilde{\beta}_1] = \beta_1 + \beta_2 \tilde{\delta}_1
\]</span></p>
<p>Therefore, the <strong>bias</strong> is:</p>
<p><span id="eq-ovb-bias"><span class="math display">\[
\text{Bias}(\tilde{\beta}_1) = \beta_2 \cdot \tilde{\delta}_1
\tag{5.3}\]</span></span></p>
</section>
<section id="interpreting-the-bias-formula" class="level3" data-number="5.8.3">
<h3 data-number="5.8.3" class="anchored" data-anchor-id="interpreting-the-bias-formula"><span class="header-section-number">5.8.3</span> Interpreting the Bias Formula</h3>
<p>The bias depends on two factors:</p>
<ol type="1">
<li><strong><span class="math inline">\(\beta_2\)</span>:</strong> The effect of the omitted variable on <span class="math inline">\(y\)</span></li>
<li><strong><span class="math inline">\(\tilde{\delta}_1\)</span>:</strong> The correlation between the omitted variable (<span class="math inline">\(x_2\)</span>) and the included variable (<span class="math inline">\(x_1\)</span>)</li>
</ol>
<p>If either factor is zero, there is no bias. But if both are non-zero, bias exists, and its direction depends on the signs:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 44%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(Corr(x_1, x_2) &gt; 0\)</span></th>
<th><span class="math inline">\(Corr(x_1, x_2) &lt; 0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\beta_2 &gt; 0\)</span></td>
<td>Positive bias (overestimate)</td>
<td>Negative bias (underestimate)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta_2 &lt; 0\)</span></td>
<td>Negative bias (underestimate)</td>
<td>Positive bias (overestimate)</td>
</tr>
</tbody>
</table>
</section>
<section id="example-education-wages-and-ability" class="level3" data-number="5.8.4">
<h3 data-number="5.8.4" class="anchored" data-anchor-id="example-education-wages-and-ability"><span class="header-section-number">5.8.4</span> Example: Education, Wages, and Ability</h3>
<p>Consider estimating the return to education while omitting ability:</p>
<ul>
<li><strong><span class="math inline">\(\beta_2\)</span> (effect of ability on wages):</strong> Positive (more able people earn more)</li>
<li><strong><span class="math inline">\(\tilde{\delta}_1\)</span> (correlation of ability with education):</strong> Positive (more able people get more education)</li>
</ul>
<p>Therefore: <span class="math display">\[\text{Bias} = (+)(+) = \text{Positive}\]</span></p>
<p>Our estimate of the return to education is <strong>too large</strong>—it includes part of the return to ability.</p>
</section>
<section id="example-policing-crime-and-poverty" class="level3" data-number="5.8.5">
<h3 data-number="5.8.5" class="anchored" data-anchor-id="example-policing-crime-and-poverty"><span class="header-section-number">5.8.5</span> Example: Policing, Crime, and Poverty</h3>
<p>Consider estimating the effect of policing on crime while omitting local poverty:</p>
<ul>
<li><strong>Effect of poverty on crime (<span class="math inline">\(\beta_2\)</span>):</strong> Positive (higher poverty → more crime)</li>
<li><strong>Correlation of poverty with policing (<span class="math inline">\(\tilde{\delta}_1\)</span>):</strong> Positive (high-poverty areas get more policing)</li>
</ul>
<p>Therefore: <span class="math display">\[\text{Bias} = (+)(+) = \text{Positive}\]</span></p>
<p>Our estimate suggests policing <em>increases</em> crime more than it actually does (or reduces it less than it actually does). This is why naive correlations between police presence and crime can be misleading.</p>
</section>
</section>
<section id="variance-in-multivariate-ols" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="variance-in-multivariate-ols"><span class="header-section-number">5.9</span> Variance in Multivariate OLS</h2>
<p>Under the Gauss-Markov assumptions, the variance of <span class="math inline">\(\hat{\beta}_j\)</span> is:</p>
<p><span id="eq-multivar-variance"><span class="math display">\[
Var(\hat{\beta}_j) = \frac{\sigma^2}{SST_j (1 - R_j^2)}
\tag{5.4}\]</span></span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\sigma^2\)</span> is the error variance</li>
<li><span class="math inline">\(SST_j = \sum(x_{ji} - \bar{x}_j)^2\)</span> is the total variation in <span class="math inline">\(x_j\)</span></li>
<li><span class="math inline">\(R_j^2\)</span> is the R-squared from regressing <span class="math inline">\(x_j\)</span> on all other independent variables</li>
</ul>
<section id="what-increases-variance" class="level3" data-number="5.9.1">
<h3 data-number="5.9.1" class="anchored" data-anchor-id="what-increases-variance"><span class="header-section-number">5.9.1</span> What Increases Variance?</h3>
<p>From <a href="#eq-multivar-variance" class="quarto-xref">Equation&nbsp;<span>5.4</span></a>, the variance of <span class="math inline">\(\hat{\beta}_j\)</span> increases when:</p>
<ol type="1">
<li><strong>More noise (<span class="math inline">\(\sigma^2\)</span>):</strong> Higher error variance means less precise estimates</li>
<li><strong>Less variation in <span class="math inline">\(x_j\)</span> (<span class="math inline">\(SST_j\)</span>):</strong> Less information about how <span class="math inline">\(x_j\)</span> relates to <span class="math inline">\(y\)</span></li>
<li><strong>Higher <span class="math inline">\(R_j^2\)</span>:</strong> More correlation between <span class="math inline">\(x_j\)</span> and other independent variables</li>
</ol>
<p>The third point is crucial: when your variable of interest is highly correlated with control variables, your estimate becomes less precise. This is sometimes called <strong>imperfect multicollinearity</strong> or the <strong>multicollinearity problem</strong>.</p>
</section>
<section id="standard-errors" class="level3" data-number="5.9.2">
<h3 data-number="5.9.2" class="anchored" data-anchor-id="standard-errors"><span class="header-section-number">5.9.2</span> Standard Errors</h3>
<p>The standard error is estimated as:</p>
<p><span class="math display">\[
se(\hat{\beta}_j) = \frac{\hat{\sigma}}{\sqrt{SST_j(1 - R_j^2)}}
\]</span></p>
<p>where <span class="math inline">\(\hat{\sigma}^2 = \frac{SSR}{n - k - 1}\)</span> is the estimated error variance, and <span class="math inline">\(n - k - 1\)</span> represents the <strong>degrees of freedom</strong>.</p>
</section>
</section>
<section id="the-bias-variance-tradeoff" class="level2" data-number="5.10">
<h2 data-number="5.10" class="anchored" data-anchor-id="the-bias-variance-tradeoff"><span class="header-section-number">5.10</span> The Bias-Variance Tradeoff</h2>
<p>Should you include a variable in your regression? The answer depends on a tradeoff.</p>
<section id="the-costs-of-omitting-a-relevant-variable" class="level3" data-number="5.10.1">
<h3 data-number="5.10.1" class="anchored" data-anchor-id="the-costs-of-omitting-a-relevant-variable"><span class="header-section-number">5.10.1</span> The Costs of Omitting a Relevant Variable</h3>
<p>If a variable truly belongs in the model (<span class="math inline">\(\beta_2 \neq 0\)</span>) and is correlated with <span class="math inline">\(x_1\)</span>, omitting it causes <strong>bias</strong>. Your estimate systematically misses the true value.</p>
</section>
<section id="the-costs-of-including-an-irrelevant-variable" class="level3" data-number="5.10.2">
<h3 data-number="5.10.2" class="anchored" data-anchor-id="the-costs-of-including-an-irrelevant-variable"><span class="header-section-number">5.10.2</span> The Costs of Including an Irrelevant Variable</h3>
<p>What if you include a variable that doesn’t belong (<span class="math inline">\(\beta_2 = 0\)</span>)?</p>
<p>From the OVB formula: <span class="math display">\[E[\hat{\beta}_1] = \beta_1 + (0) \cdot \tilde{\delta}_1 = \beta_1\]</span></p>
<p>No bias! Including an irrelevant variable doesn’t bias your estimate.</p>
<p>But look at the variance formula. Including an extra variable increases <span class="math inline">\(R_1^2\)</span> (the correlation between <span class="math inline">\(x_1\)</span> and other variables), which increases the variance of <span class="math inline">\(\hat{\beta}_1\)</span>.</p>
<p><strong>Including irrelevant variables inflates variance without reducing bias.</strong></p>
</section>
<section id="the-tradeoff" class="level3" data-number="5.10.3">
<h3 data-number="5.10.3" class="anchored" data-anchor-id="the-tradeoff"><span class="header-section-number">5.10.3</span> The Tradeoff</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Action</th>
<th>Bias</th>
<th>Variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Omit relevant variable</td>
<td>Increases</td>
<td>Decreases</td>
</tr>
<tr class="even">
<td>Include irrelevant variable</td>
<td>No change</td>
<td>Increases</td>
</tr>
</tbody>
</table>
<p>This is the <strong>bias-variance tradeoff</strong>:</p>
<ul>
<li>If you’re too conservative (omit too many variables), you risk bias</li>
<li>If you’re too liberal (include everything), you inflate variance</li>
</ul>
</section>
<section id="practical-guidance" class="level3" data-number="5.10.4">
<h3 data-number="5.10.4" class="anchored" data-anchor-id="practical-guidance"><span class="header-section-number">5.10.4</span> Practical Guidance</h3>
<p>There’s no perfect solution, but some principles help:</p>
<ol type="1">
<li><p><strong>Include variables you have strong theoretical reasons to believe are confounders.</strong> Use economic theory and prior research to guide variable selection.</p></li>
<li><p><strong>Be cautious about highly correlated controls.</strong> If two controls are very highly correlated with each other, including both can dramatically inflate variance.</p></li>
<li><p><strong>Larger samples help.</strong> As <span class="math inline">\(n\)</span> increases, variance decreases, making the “include it just in case” strategy less costly.</p></li>
<li><p><strong>Check how estimates change.</strong> If adding a control substantially changes your coefficient of interest, that control is probably important.</p></li>
</ol>
</section>
</section>
<section id="simulation-bias-vs.-variance" class="level2" data-number="5.11">
<h2 data-number="5.11" class="anchored" data-anchor-id="simulation-bias-vs.-variance"><span class="header-section-number">5.11</span> Simulation: Bias vs.&nbsp;Variance</h2>
<p>Let’s see the bias-variance tradeoff in action with a simulation.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bias-variance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-bias-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: The bias-variance tradeoff. Left: When x₂ doesn’t affect y (β₂=0), including it adds variance without reducing bias. Right: When x₂ does affect y (β₂≠0), omitting it causes bias.
</figcaption>
<div aria-describedby="fig-bias-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="unit4_files/figure-html/fig-bias-variance-1.png" class="img-fluid figure-img" style="width:95.0%">
</div>
</figure>
</div>
</div>
</div>
<p>In <strong>Case 1</strong> (left panel), <span class="math inline">\(x_2\)</span> doesn’t actually affect <span class="math inline">\(y\)</span>. Including it (coral) doesn’t reduce bias (both distributions are centered on the true value), but it does increase variance (the coral distribution is wider).</p>
<p>In <strong>Case 2</strong> (right panel), <span class="math inline">\(x_2\)</span> does affect <span class="math inline">\(y\)</span>. Omitting it (blue) causes bias—the distribution is centered away from the true value. Including it (coral) eliminates the bias, even though variance is slightly higher.</p>
</section>
<section id="summary" class="level2" data-number="5.12">
<h2 data-number="5.12" class="anchored" data-anchor-id="summary"><span class="header-section-number">5.12</span> Summary</h2>
<p>This chapter extended OLS to the multivariate case, allowing us to control for confounding variables.</p>
<section id="key-takeaways" class="level3" data-number="5.12.1">
<h3 data-number="5.12.1" class="anchored" data-anchor-id="key-takeaways"><span class="header-section-number">5.12.1</span> Key Takeaways</h3>
<ul>
<li><p><strong>Multivariate OLS</strong> includes multiple independent variables: <span class="math display">\[y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_k x_k + \mu\]</span></p></li>
<li><p><strong>Coefficients have ceteris paribus interpretations:</strong> <span class="math inline">\(\beta_j\)</span> is the effect of <span class="math inline">\(x_j\)</span> holding all other variables constant</p></li>
<li><p><strong>The zero conditional mean assumption</strong> now requires <span class="math inline">\(E[\mu | x_1, \ldots, x_k] = 0\)</span>—more plausible with good controls</p></li>
<li><p><strong>Multivariate OLS is like matching:</strong> It compares observations within groups defined by control variables</p></li>
<li><p><strong>The OVB formula</strong> tells us the direction of bias from omitting a variable: <span class="math display">\[\text{Bias} = \beta_2 \cdot \tilde{\delta}_1\]</span></p></li>
<li><p><strong>There’s a bias-variance tradeoff:</strong> Omitting relevant variables causes bias; including irrelevant variables inflates variance</p></li>
<li><p><strong>Perfect multicollinearity</strong> occurs when one variable is an exact linear function of others; it must be avoided</p></li>
</ul>
</section>
</section>
<section id="check-your-understanding" class="level2" data-number="5.13">
<h2 data-number="5.13" class="anchored" data-anchor-id="check-your-understanding"><span class="header-section-number">5.13</span> Check Your Understanding</h2>
<div class="question">
<div class="answer-row">
    <label>i. In the model \(y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \mu\), what does \(\beta_1\) represent? </label>
    <select onchange="checkAnswer(this, 'c')">
        <option value="">-- Select Answer --</option>
        <option value="a">The total effect of \(x_1\) on \(y\)</option>
        <option value="b">The correlation between \(x_1\) and \(y\)</option>
        <option value="c">The effect of \(x_1\) on \(y\), holding \(x_2\) constant</option>
        <option value="d">The effect of \(x_1\) on \(y\), ignoring \(x_2\)</option>
    </select>
</div>

<div class="answer-row">
    <label>ii. The zero conditional mean assumption in multivariate OLS states: </label>
    <select onchange="checkAnswer(this, 'b')">
        <option value="">-- Select Answer --</option>
        <option value="a">\(E[\mu] = 0\)</option>
        <option value="b">\(E[\mu | x_1, x_2, \ldots, x_k] = 0\)</option>
        <option value="c">\(E[y | x_1, x_2, \ldots, x_k] = 0\)</option>
        <option value="d">\(Var(\mu | x_1, x_2, \ldots, x_k) = \sigma^2\)</option>
    </select>
</div>

<div class="answer-row">
    <label>iii. Perfect multicollinearity occurs when: </label>
    <select onchange="checkAnswer(this, 'd')">
        <option value="">-- Select Answer --</option>
        <option value="a">Two independent variables are correlated</option>
        <option value="b">The R-squared is very high</option>
        <option value="c">The error term is correlated with an independent variable</option>
        <option value="d">One independent variable is an exact linear function of others</option>
    </select>
</div>

<div class="answer-row">
    <label>iv. The adjusted R-squared differs from the regular R-squared because it: </label>
    <select onchange="checkAnswer(this, 'a')">
        <option value="">-- Select Answer --</option>
        <option value="a">Penalizes for the number of independent variables</option>
        <option value="b">Is always larger</option>
        <option value="c">Measures causality rather than correlation</option>
        <option value="d">Only applies to bivariate regression</option>
    </select>
</div>

<div class="answer-row">
    <label>v. According to the OVB formula, bias equals zero when: </label>
    <select onchange="checkAnswer(this, 'c')">
        <option value="">-- Select Answer --</option>
        <option value="a">The omitted variable is important</option>
        <option value="b">The sample size is large</option>
        <option value="c">Either \(\beta_2 = 0\) or the omitted variable is uncorrelated with \(x_1\)</option>
        <option value="d">The R-squared is high</option>
    </select>
</div>

<div class="answer-row">
    <label>vi. If you include an irrelevant variable (one with \(\beta = 0\)), your estimate of \(\beta_1\) will be: </label>
    <select onchange="checkAnswer(this, 'b')">
        <option value="">-- Select Answer --</option>
        <option value="a">Biased with lower variance</option>
        <option value="b">Unbiased with higher variance</option>
        <option value="c">Biased with higher variance</option>
        <option value="d">Unbiased with lower variance</option>
    </select>
</div>
</div>

<div class="context" style="margin-top: 30px; margin-bottom: 20px;">
<strong>OVB Direction Practice:</strong> For each scenario, determine the likely direction of bias.
</div>

<div class="question">
<div class="answer-row">
    <label>vii. Model: \(health = \beta_0 + \beta_1(exercise) + \mu\). Omitted variable: income. If higher income → more exercise AND higher income → better health, the bias on \(\hat{\beta}_1\) is: </label>
    <select onchange="checkAnswer(this, 'a')">
        <option value="">-- Select Answer --</option>
        <option value="a">Positive (overestimate)</option>
        <option value="b">Negative (underestimate)</option>
        <option value="c">Zero</option>
        <option value="d">Cannot determine</option>
    </select>
</div>

<div class="answer-row">
    <label>viii. Model: \(test\_score = \beta_0 + \beta_1(class\_size) + \mu\). Omitted variable: school funding. If more funding → smaller classes AND more funding → higher scores, the bias on \(\hat{\beta}_1\) is: </label>
    <select onchange="checkAnswer(this, 'b')">
        <option value="">-- Select Answer --</option>
        <option value="a">Positive (makes class size look beneficial)</option>
        <option value="b">Negative (makes class size look more harmful)</option>
        <option value="c">Zero</option>
        <option value="d">Cannot determine</option>
    </select>
</div>

<div class="answer-row">
    <label>ix. <strong>(Challenge)</strong> In a wage regression controlling for education and experience, you add a control for "IQ score." The coefficient on education drops substantially. This suggests: </label>
    <select onchange="checkAnswer(this, 'c')">
        <option value="">-- Select Answer --</option>
        <option value="a">IQ is irrelevant to wages</option>
        <option value="b">Education has no causal effect on wages</option>
        <option value="c">Part of the original "education effect" was actually capturing ability differences</option>
        <option value="d">The new regression is biased</option>
    </select>
</div>
</div>

<div class="context" style="margin-top: 30px; margin-bottom: 20px;">
<strong>Practice: Interpreting Multivariate Regression Output</strong>
</div>

<div class="context" style="margin-bottom: 20px;">
<strong>Regression 1:</strong> A researcher estimates the determinants of house prices:
<pre style="background-color: #f5f5f5; padding: 10px; margin-top: 10px; font-family: monospace;">Dependent variable: price (house price in $1000s)

             Estimate  Std. Error
(Intercept)    50.23      12.45
sqft            0.15       0.02
bedrooms       -8.72       3.21
bathrooms      24.56       4.89

n = 546, Adjusted R-squared = 0.68
</pre>
</div>

<div class="question">
<div class="answer-row">
    <label>x. According to this regression, an additional 100 square feet is associated with a price increase of: </label>
    <select onchange="checkAnswer(this, 'b')">
        <option value="">-- Select Answer --</option>
        <option value="a">$0.15</option>
        <option value="b">$15,000</option>
        <option value="c">$150</option>
        <option value="d">$1,500</option>
    </select>
</div>

<div class="answer-row">
    <label>xi. The negative coefficient on bedrooms (-8.72) means: </label>
    <select onchange="checkAnswer(this, 'c')">
        <option value="">-- Select Answer --</option>
        <option value="a">Houses with more bedrooms are always cheaper</option>
        <option value="b">Bedrooms reduce house prices by $8,720 on average</option>
        <option value="c">Holding sqft and bathrooms constant, an extra bedroom is associated with $8,720 lower price</option>
        <option value="d">The regression is incorrectly specified</option>
    </select>
</div>

<div class="answer-row">
    <label>xii. Why might the coefficient on bedrooms be negative even though houses with more bedrooms typically sell for more? </label>
    <select onchange="checkAnswer(this, 'd')">
        <option value="">-- Select Answer --</option>
        <option value="a">Measurement error in the data</option>
        <option value="b">The sample is not representative</option>
        <option value="c">Omitted variable bias</option>
        <option value="d">Holding square footage constant, more bedrooms means smaller rooms on average</option>
    </select>
</div>
</div>

<div class="context" style="margin-top: 30px; margin-bottom: 20px;">
<strong>Regression 2:</strong> An economist studies student test performance:
<pre style="background-color: #f5f5f5; padding: 10px; margin-top: 10px; font-family: monospace;">Dependent variable: test_score (standardized, mean=0, sd=1)

                  Estimate  Std. Error
(Intercept)        -0.892      0.156
hours_studied       0.045      0.008
parent_college      0.312      0.067
free_lunch         -0.287      0.071

n = 1,200, Adjusted R-squared = 0.23
</pre>
<em>Note: parent_college = 1 if at least one parent has college degree; free_lunch = 1 if eligible for free lunch program (proxy for low income)</em>
</div>

<div class="question">
<div class="answer-row">
    <label>xiii. A student who studies 10 more hours per week is predicted to score how much higher? </label>
    <select onchange="checkAnswer(this, 'a')">
        <option value="">-- Select Answer --</option>
        <option value="a">0.45 standard deviations higher</option>
        <option value="b">0.045 standard deviations higher</option>
        <option value="c">4.5 points higher</option>
        <option value="d">45 points higher</option>
    </select>
</div>

<div class="answer-row">
    <label>xiv. Comparing two students who study the same amount and have the same free lunch status, a student with a college-educated parent scores on average: </label>
    <select onchange="checkAnswer(this, 'b')">
        <option value="">-- Select Answer --</option>
        <option value="a">0.312 points higher</option>
        <option value="b">0.312 standard deviations higher</option>
        <option value="c">31.2% higher</option>
        <option value="d">Cannot determine from this output</option>
    </select>
</div>

<div class="answer-row">
    <label>xv. <strong>(Challenge)</strong> A naive regression of test_score on hours_studied alone yields a coefficient of 0.062. Why might this be larger than the 0.045 in the full model? </label>
    <select onchange="checkAnswer(this, 'c')">
        <option value="">-- Select Answer --</option>
        <option value="a">The full model has more noise</option>
        <option value="b">Hours studied has less variation in the full model</option>
        <option value="c">Students from advantaged backgrounds (college parents, higher income) study more AND score higher for other reasons</option>
        <option value="d">The adjusted R-squared is too low</option>
    </select>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Explanation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="i">
<li><p>In multivariate regression, <span class="math inline">\(\beta_1\)</span> is the partial effect of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span>, holding <span class="math inline">\(x_2\)</span> (and all other included variables) constant. This is the ceteris paribus interpretation.</p></li>
<li><p>The multivariate zero conditional mean assumption requires that the error term have mean zero for all combinations of the independent variables, not just unconditionally.</p></li>
<li><p>Perfect multicollinearity means one variable is a perfect linear combination of others (like including income in dollars and income in thousands, or including all categories of a dummy variable plus an intercept). Simple correlation between variables is not perfect multicollinearity.</p></li>
<li><p>The adjusted R-squared penalizes for adding more variables, preventing the mechanical increase that happens with regular R-squared when you add irrelevant variables.</p></li>
<li><p>From the OVB formula: <span class="math inline">\(\text{Bias} = \beta_2 \cdot \tilde{\delta}_1\)</span>. Bias equals zero if either <span class="math inline">\(\beta_2 = 0\)</span> (the omitted variable doesn’t affect <span class="math inline">\(y\)</span>) or <span class="math inline">\(\tilde{\delta}_1 = 0\)</span> (the omitted variable is uncorrelated with <span class="math inline">\(x_1\)</span>).</p></li>
<li><p>Including an irrelevant variable doesn’t cause bias (since <span class="math inline">\(\beta_2 = 0\)</span> in the OVB formula), but it does increase variance through the <span class="math inline">\((1 - R_j^2)\)</span> term in the variance formula.</p></li>
<li><p>Income is positively correlated with both exercise and health. $ = (+)(+) = $ Positive. We overestimate the effect of exercise because part of what we’re measuring is actually the effect of income.</p></li>
<li><p>More funding means smaller classes (negative correlation: <span class="math inline">\(\tilde{\delta}_1 &lt; 0\)</span>) and higher scores (<span class="math inline">\(\beta_2 &gt; 0\)</span>). $ = (+)(-) = $ Negative. The estimate of class size’s effect is too negative—we attribute to large classes what is actually due to low funding.</p></li>
<li><p>When adding a control causes the coefficient of interest to change substantially, it suggests the original estimate was confounded. Here, part of what looked like a “return to education” was actually capturing the fact that higher-ability people get more education and earn more.</p></li>
</ol>
<p><strong>Regression Interpretation Questions:</strong></p>
<ol start="24" type="a">
<li>The coefficient on sqft is 0.15, meaning each additional square foot is associated with $150 more (since price is in $1000s). For 100 square feet: <span class="math inline">\(100 \times 0.15 = 15\)</span>, which is $15,000.</li>
</ol>
<ol start="11" type="i">
<li><p>The coefficient on bedrooms has a ceteris paribus interpretation: holding square footage and bathrooms constant, an additional bedroom is associated with $8,720 lower price. This doesn’t mean bedrooms reduce prices overall—it’s the partial effect.</p></li>
<li><p>The key is “holding square footage constant.” If total space is fixed, adding a bedroom means dividing that space into more (smaller) rooms. Buyers may prefer fewer, larger rooms to more cramped ones. This illustrates why we must interpret multivariate coefficients carefully—they hold other variables constant.</p></li>
<li><p>The coefficient on hours_studied is 0.045, so 10 additional hours predicts: <span class="math inline">\(10 \times 0.045 = 0.45\)</span> standard deviations higher. Since the outcome is standardized, we interpret in standard deviation units.</p></li>
<li><p>The coefficient on parent_college (0.312) is the difference in predicted test scores between students with and without college-educated parents, holding study hours and free lunch status constant. Since test scores are standardized, this is 0.312 standard deviations.</p></li>
<li><p>The naive coefficient (0.062) is larger than the controlled coefficient (0.045) because of omitted variable bias. Students from advantaged backgrounds (college-educated parents, higher income) likely study more AND have other advantages (better schools, tutoring, resources) that boost scores. The naive estimate conflates the effect of studying with these background advantages.</p></li>
</ol>
</div>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-wooldridge_introductory_2019" class="csl-entry" role="listitem">
Wooldridge, Jeffrey M. 2019. <em>Introductory Econometrics: A Modern Approach</em>. 7th ed. Cengage Learning.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/unit3.html" class="pagination-link" aria-label="Bivariate Regression and Ordinary Least Squares">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bivariate Regression and Ordinary Least Squares</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/unit5.html" class="pagination-link" aria-label="Statistical Inference">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Statistical Inference</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><span class="faux-block"> © 2025 Raymond Caraher. All rights reserved. </span></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>