{
  "hash": "0f43df2e26432d4ff9737ee024843b2e",
  "result": {
    "engine": "knitr",
    "markdown": "# Statistical Inference {#sec-inference}\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n```{=html}\n\n<style>\n.problem {\n    background-color: #f8f9fa;\n    border: 1px solid #dee2e6;\n    border-radius: 8px;\n    padding: 20px;\n    margin: 20px 0;\n}\n.context {\n    background-color: #e8f4f8;\n    padding: 12px;\n    border-radius: 5px;\n    margin-bottom: 15px;\n    border-left: 4px solid #2874a6;\n}\n.question {\n    margin: 15px 0;\n    padding: 10px;\n    background-color: #fff3cd;\n    border-radius: 5px;\n}\n.answer-row {\n    display: flex;\n    align-items: center;\n    margin: 10px 0;\n    flex-wrap: wrap;\n    gap: 10px;\n}\n.answer-row label {\n    min-width: 320px;\n    font-weight: 500;\n}\nselect {\n    padding: 8px 12px;\n    font-size: 14px;\n    border: 2px solid #ccc;\n    border-radius: 5px;\n    min-width: 300px;\n    cursor: pointer;\n}\nselect:focus {\n    border-color: #2874a6;\n    outline: none;\n}\n.correct {\n    border-color: #28a745 !important;\n    background-color: #d4edda !important;\n}\n.incorrect {\n    border-color: #dc3545 !important;\n    background-color: #f8d7da !important;\n}\n.explanation {\n    margin-top: 10px;\n    padding: 15px;\n    background-color: #e7f3ff;\n    border-radius: 5px;\n    border-left: 4px solid #2874a6;\n}\n.note {\n    font-size: 0.85em;\n    color: #666;\n    font-style: italic;\n}\n</style>\n\n<script>\nfunction checkAnswer(selectElement, correctValue) {\n    if (selectElement.value === '') {\n        selectElement.classList.remove('correct', 'incorrect');\n    } else if (selectElement.value === correctValue) {\n        selectElement.classList.remove('incorrect');\n        selectElement.classList.add('correct');\n    } else {\n        selectElement.classList.remove('correct');\n        selectElement.classList.add('incorrect');\n    }\n}\n</script>\n\n```\n\n\n\n\n\n\n\n::: {.callout-tip collapse=\"true\"}\n## **Key Questions**\n- How do we know if our OLS estimate reflects a \"real\" effect or is just due to random chance?\n- What is the sampling distribution of our OLS estimator and why does it matter?\n- How do we conduct hypothesis tests using t-statistics and p-values?\n- What do confidence intervals tell us about our estimates?\n- How do we test multiple hypotheses simultaneously using F-tests?\n- How do we read and interpret regression tables in published research?\n:::\n\n::: {.callout-note collapse=\"true\"}\n## **Suggested Readings**\n- @wooldridge_introductory_2019, Ch. 4\n:::\n\n\n## From Point Estimates to Uncertainty\n\nIn the previous chapters, we learned how to estimate the parameters of a regression model using OLS.\nWe discussed how, under certain assumptions, our OLS estimator $\\hat{\\beta}_j$ is *unbiased*---meaning that on average, across many hypothetical samples, our estimate equals the true population parameter $\\beta_j$.\n\nBut here's the catch: we only ever observe *one* sample.\nOur single estimate might be too high or too low relative to the truth, simply due to the random variation inherent in sampling.\n**Statistical inference** is the set of tools that allows us to quantify this uncertainty and make statements about population parameters based on sample data.\n\nThe central question of statistical inference is: *Is our single OLS estimate \"real,\" or is it due to random chance?*\n\n\n## The Sampling Distribution: A Simulation\n\nTo understand why uncertainty matters, let's run a simulation.\nImagine we have a population where the true relationship between $x$ and $y$ is:\n\n$$y = 2.45 + 0 \\cdot x + \\mu$$\n\nNotice that the true effect of $x$ on $y$ is **exactly zero**.\nIn the population, $x$ has no effect on $y$ whatsoever.\n\nBut what happens when we draw samples from this population and estimate OLS regressions?\nLet's find out.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(124890)\n\n# Create our \"population\" data\npop_data <- tibble(\n  x = sample(1:100, size = 1000, replace = TRUE),\n  err = rnorm(1000),\n  y = 2.45 + 0 * x + err  # True beta_1 = 0\n)\n\n# Number of simulation repetitions\nn_sims <- 1000\n\n# Run the simulation\nsim_results <- map_dfr(1:n_sims, function(i) {\n  # Draw a random sample of 50 observations\n  sample_data <- pop_data |>\n    slice_sample(n = 50, replace = TRUE)\n  \n  # Estimate OLS regression\n  reg <- lm(y ~ x, data = sample_data)\n  \n  # Store the estimate\n  tibble(\n    iteration = i,\n    b1_hat = coef(reg)[\"x\"]\n  )\n})\n\n# Calculate the average estimate\navg_estimate <- mean(sim_results$b1_hat)\n\n# Create the visualization\nggplot(sim_results, aes(x = b1_hat)) +\n  geom_histogram(fill = \"lightgrey\", color = \"black\", bins = 40) +\n  geom_vline(xintercept = avg_estimate, color = \"darkgreen\", linewidth = 1.5) +\n  annotate(\"text\", x = avg_estimate + 0.003, y = 85,\n           label = paste0(\"Average estimate\\n= \", round(avg_estimate, 4)),\n           color = \"darkgreen\", size = 4, hjust = 0) +\n  labs(\n    x = expression(hat(beta)[1]),\n    y = \"Frequency\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text = element_text(size = 12),\n    axis.title = element_text(size = 14)\n  )\n```\n\n::: {.cell-output-display}\n![Sampling distribution of β̂₁ when the true β₁ = 0. Each bar represents the frequency of estimates across 1,000 different samples.](unit5_files/figure-pdf/fig-sampling-dist-sim-1.pdf){#fig-sampling-dist-sim fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nLook at what happened!\nEven though the true $\\beta_1 = 0$, we got a *distribution* of different estimates ranging from about -0.02 to +0.02.\nSome samples produced positive estimates, others produced negative estimates.\nThe average across all samples is very close to zero (as expected from unbiasedness), but any *individual* sample could give us an estimate that deviates from zero.\n\nThis distribution of estimates across all possible samples is called the **sampling distribution** of $\\hat{\\beta}_j$.\n\n\n## Where Does Our Estimate Fall?\n\nNow imagine you only have access to *one* sample---as is always the case in practice.\nYou run your regression and get an estimate of, say, $\\hat{\\beta}_1 = 0.001$.\n\nHow do you know if your estimate comes from here (close to the true value):\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![An estimate close to the average is likely consistent with the null hypothesis.](unit5_files/figure-pdf/fig-estimate-close-1.pdf){#fig-estimate-close}\n:::\n:::\n\n\n\n\n\n\nOr from here (far out in the tails):\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![An estimate in the tail is unlikely if the true effect is zero---suggesting the true effect might not be zero.](unit5_files/figure-pdf/fig-estimate-far-1.pdf){#fig-estimate-far}\n:::\n:::\n\n\n\n\n\n\nIf your estimate falls in the middle of the distribution where $\\beta_1 = 0$, it's consistent with the null hypothesis of no effect.\nBut if your estimate falls way out in the tails, it suggests that maybe the true $\\beta_1$ isn't zero after all---because getting such an extreme estimate would be very unlikely if $\\beta_1$ really were zero.\n\nThe tools of statistical inference formalize this intuition.\n\n\n## The Sampling Distribution of $\\hat{\\beta}_j$\n\nTo conduct statistical inference, we need to know the *shape* of the sampling distribution.\nWe've already established two key properties of our OLS estimator (under the Gauss-Markov assumptions):\n\n**Expected Value (Unbiasedness):**\n$$E[\\hat{\\beta}_j] = \\beta_j$$\n\n**Variance (under homoskedasticity):**\n$$Var(\\hat{\\beta}_j) = \\frac{\\sigma^2}{SST_j(1 - R^2_j)}$$\n\nwhere $SST_j$ is the total sum of squares of $x_j$ and $R^2_j$ is the R-squared from regressing $x_j$ on all other independent variables.\n\nBut knowing the mean and variance isn't enough---we need to know the *shape* of the distribution.\n\n\n### The Normality Assumption\n\nTo fully characterize the sampling distribution, we make an additional assumption:\n\n::: {.callout-important}\n## Normality Assumption\nThe population error $\\mu$ is independent of the explanatory variables $x_1, x_2, ..., x_k$ and is normally distributed with zero mean and variance $\\sigma^2$:\n\n$$\\mu \\sim Normal(0, \\sigma^2)$$\n\nEquivalently, we can write:\n\n$$y | \\mathbf{x} \\sim Normal(\\beta_0 + \\beta_1 x_1 + ... + \\beta_k x_k, \\sigma^2)$$\n:::\n\nThis says that conditional on the independent variables, the outcome $y$ follows a normal distribution centered on the regression line.\n\nLet's visualize what a normal distribution looks like:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(123)\nmu <- 100\nsigma <- 15\n\nnormal_data <- tibble(\n  values = rnorm(n = 1000, mean = mu, sd = sigma)\n)\n\nggplot(normal_data, aes(x = values)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 30,\n                 fill = \"skyblue\",\n                 color = \"white\",\n                 alpha = 0.8) +\n  stat_function(fun = dnorm,\n                args = list(mean = mu, sd = sigma),\n                color = \"darkred\",\n                linewidth = 1.2) +\n  labs(\n    title = \"Normal Distribution with Density Curve\",\n    subtitle = paste0(\"Generated from N(μ = \", mu, \", σ = \", sigma, \")\"),\n    x = \"Values (e.g., IQ Scores)\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Generated from N(μ = 100, σ = 15)' in 'mbcsToSbcs': dot\nsubstituted for <ce>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Generated from N(μ = 100, σ = 15)' in 'mbcsToSbcs': dot\nsubstituted for <bc>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Generated from N(μ = 100, σ = 15)' in 'mbcsToSbcs': dot\nsubstituted for <cf>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Generated from N(μ = 100, σ = 15)' in 'mbcsToSbcs': dot\nsubstituted for <83>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Generated from N(μ = 100, σ = 15)' in 'mbcsToSbcs': dot\nsubstituted for <ce>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Generated from N(μ = 100, σ = 15)' in 'mbcsToSbcs': dot\nsubstituted for <bc>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Generated from N(μ = 100, σ = 15)' in 'mbcsToSbcs': dot\nsubstituted for <cf>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Generated from N(μ = 100, σ = 15)' in 'mbcsToSbcs': dot\nsubstituted for <83>\n```\n\n\n:::\n\n::: {.cell-output-display}\n![The normal (Gaussian) distribution---the classic 'bell curve.' The example shows IQ scores, which are designed to follow N(100, 15).](unit5_files/figure-pdf/fig-normal-dist-1.pdf){#fig-normal-dist fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nAt first glance, the normality assumption seems quite strong.\nFor many economic variables---like wages, which are bounded below by zero and have a right skew---the distribution is clearly not normal.\nHowever, there's good news: as long as our sample size is large enough, the sampling distribution of $\\hat{\\beta}_j$ will be approximately normal *even if the errors aren't normally distributed*.\nThis result is called **asymptotic normality** and follows from the Central Limit Theorem.\n\n\n### The Normal Sampling Distribution\n\nUnder the normality assumption (or with large samples via asymptotic normality), our OLS estimator follows a normal distribution:\n\n$$\\hat{\\beta}_j \\sim Normal\\left[\\beta_j, Var(\\hat{\\beta}_j)\\right]$$\n\nLet's verify this with a simulation.\nWe'll draw many samples and show that the distribution of estimates indeed looks normal:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Overlay a normal density on our simulation results\nggplot(sim_results, aes(x = b1_hat)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 fill = \"lightgrey\", color = \"black\", bins = 40) +\n  stat_function(\n    fun = dnorm,\n    args = list(mean = mean(sim_results$b1_hat), \n                sd = sd(sim_results$b1_hat)),\n    color = \"darkred\",\n    linewidth = 1.2\n  ) +\n  geom_vline(xintercept = 0, color = \"darkgreen\", linewidth = 1.2, linetype = \"dashed\") +\n  annotate(\"text\", x = 0.012, y = 55,\n           label = \"True β₁ = 0\", color = \"darkgreen\", size = 4) +\n  labs(\n    x = expression(hat(beta)[1]),\n    y = \"Density\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'True β₁ = 0' in 'mbcsToSbcs': dot substituted for <ce>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'True β₁ = 0' in 'mbcsToSbcs': dot substituted for <b2>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'True β₁ = 0' in 'mbcsToSbcs': dot substituted for <e2>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'True β₁ = 0' in 'mbcsToSbcs': dot substituted for <82>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'True β₁ = 0' in 'mbcsToSbcs': dot substituted for <81>\n```\n\n\n:::\n\n::: {.cell-output-display}\n![The sampling distribution of β̂₁ follows a normal distribution (red curve) centered on the true value.](unit5_files/figure-pdf/fig-normal-sampling-1.pdf){#fig-normal-sampling fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nThe histogram of our 1,000 simulated estimates matches the theoretical normal curve almost perfectly!\n\n\n:::: {.content-visible when-format=\"html\"}\n\n::: {.problem}\n\n<div class=\"context\">\n**Quick Check: Understanding the Sampling Distribution**\n</div>\n\n<div class=\"question\">\n<div class=\"answer-row\">\n<label>If we draw many samples and estimate $\\hat{\\beta}_1$ from each, what will the average of all these estimates equal (assuming unbiasedness)?</label>\n<select onchange=\"checkAnswer(this, 'b')\">\n<option value=\"\">Select answer...</option>\n<option value=\"a\">Zero</option>\n<option value=\"b\">The true population parameter β₁</option>\n<option value=\"c\">The sample mean of y</option>\n<option value=\"d\">It depends on the sample size</option>\n</select>\n</div>\n</div>\n\n<div class=\"question\">\n<div class=\"answer-row\">\n<label>If the true $\\beta_1 = 0$ and we get an estimate of $\\hat{\\beta}_1 = 0.5$ with a standard error of 0.1, where does our estimate fall in the sampling distribution?</label>\n<select onchange=\"checkAnswer(this, 'c')\">\n<option value=\"\">Select answer...</option>\n<option value=\"a\">At the center of the distribution</option>\n<option value=\"b\">Slightly to the right of center</option>\n<option value=\"c\">Far in the right tail (5 standard errors away)</option>\n<option value=\"d\">Cannot be determined</option>\n</select>\n</div>\n</div>\n\n:::\n\n::::\n\n:::: {.content-hidden when-format=\"html\"}\n\n*Quick Check: This section contains interactive content only available in the HTML version.*\n\n::::\n\n\n## Hypothesis Testing\n\nNow that we understand the sampling distribution, we can use it to make inferences about population parameters.\nThe key idea is **hypothesis testing**: we hypothesize about the value of $\\beta_j$ in the population, then use our sample estimate to evaluate whether the hypothesis is plausible.\n\n\n### The Null and Alternative Hypotheses\n\nIn econometrics, we're usually interested in whether a variable has *any* effect on the outcome.\nWe formalize this as:\n\n**Null Hypothesis:** $H_0: \\beta_j = 0$\n\nThe null hypothesis states that the variable $x_j$ has no effect on $y$ in the population (after controlling for other variables).\n\n**Alternative Hypothesis:** We test the null against one of:\n\n- $H_1: \\beta_j \\neq 0$ (two-sided test, most common)\n- $H_1: \\beta_j > 0$ (one-sided, if we expect a positive effect)\n- $H_1: \\beta_j < 0$ (one-sided, if we expect a negative effect)\n\nFor example, consider the wage equation:\n\n$$wage = \\beta_0 + \\beta_1(educ) + \\beta_2(experience) + \\beta_3(tenure) + \\mu$$\n\nThe null hypothesis $H_0: \\beta_2 = 0$ states that, after controlling for education and tenure, experience has no effect on wages.\n\n\n### The t-Statistic\n\nTo test our hypothesis, we use the **t-statistic**.\nUnder the null hypothesis, the following quantity follows a t-distribution:\n\n$$\\frac{\\hat{\\beta}_j - \\beta_j}{se(\\hat{\\beta}_j)} \\sim t_{n-k-1}$$\n\nwhere $n - k - 1$ are the degrees of freedom (sample size minus the number of parameters).\n\nWhen testing $H_0: \\beta_j = 0$, the t-statistic simplifies to:\n\n$$t_{\\hat{\\beta}_j} = \\frac{\\hat{\\beta}_j}{se(\\hat{\\beta}_j)}$$\n\nThis is simply the ratio of our estimate to its standard error.\nThe t-stat tells us: *how many standard errors away from zero is our estimate?*\n\n\n### Properties of the t-Statistic\n\nThe t-statistic has several useful properties:\n\n1. **Same sign as the estimate:** Since $se(\\hat{\\beta}_j) > 0$, the t-stat has the same sign as $\\hat{\\beta}_j$\n\n2. **Magnitude matters:** As $\\hat{\\beta}_j$ grows in magnitude, so does $t_{\\hat{\\beta}_j}$\n\n3. **Signal-to-noise ratio:** The t-stat measures how large our estimate is *relative to the noise* (uncertainty) in our data\n\n\n### Visualizing the Hypothesis Test\n\nLet's visualize what the t-test is doing.\nUnder the null hypothesis $H_0: \\beta_j = 0$, we assume that the distribution of possible estimates is centered on zero:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(42)\ndf_value <- 100  # degrees of freedom\n\nt_sample <- tibble(\n  t_value = rt(10000, df = df_value)\n)\n\nggplot(t_sample, aes(x = t_value)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 50,\n                 fill = \"lightblue\",\n                 color = \"black\") +\n  stat_function(fun = dt,\n                args = list(df = df_value),\n                color = \"darkred\",\n                linewidth = 1.2) +\n  geom_vline(xintercept = 0, color = \"darkgreen\", linewidth = 1.2) +\n  annotate(\"text\", x = 1.5, y = 0.35,\n           label = \"Distribution under H₀\",\n           color = \"darkgreen\", size = 5) +\n  labs(x = \"t-values\", y = \"Density\") +\n  coord_cartesian(xlim = c(-4, 4)) +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution under H₀' in 'mbcsToSbcs': dot substituted\nfor <e2>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution under H₀' in 'mbcsToSbcs': dot substituted\nfor <82>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Distribution under H₀' in 'mbcsToSbcs': dot substituted\nfor <80>\n```\n\n\n:::\n\n::: {.cell-output-display}\n![The t-distribution under the null hypothesis H₀: βⱼ = 0. Most estimates will fall near zero.](unit5_files/figure-pdf/fig-t-dist-null-1.pdf){#fig-t-dist-null fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nNow suppose we get a t-statistic from our sample.\nIs it close to zero (consistent with $H_0$) or far from zero (evidence against $H_0$)?\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\np_close <- ggplot(t_sample, aes(x = t_value)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 50, fill = \"lightblue\", color = \"black\") +\n  stat_function(fun = dt, args = list(df = df_value),\n                color = \"darkred\", linewidth = 1.2) +\n  geom_vline(xintercept = 0.85, color = \"blue\", linewidth = 1.5) +\n  annotate(\"text\", x = 0.85, y = 0.42, label = \"t = 0.85\",\n           color = \"blue\", size = 4, hjust = -0.1) +\n  labs(x = \"t-values\", y = \"Density\", \n       title = \"t-stat close to zero\") +\n  coord_cartesian(xlim = c(-4, 4)) +\n  theme_minimal()\n\np_far <- ggplot(t_sample, aes(x = t_value)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 50, fill = \"lightblue\", color = \"black\") +\n  stat_function(fun = dt, args = list(df = df_value),\n                color = \"darkred\", linewidth = 1.2) +\n  geom_vline(xintercept = 2.8, color = \"red\", linewidth = 1.5) +\n  annotate(\"text\", x = 2.8, y = 0.15, label = \"t = 2.8\",\n           color = \"red\", size = 4, hjust = -0.1) +\n  labs(x = \"t-values\", y = \"Density\",\n       title = \"t-stat in the tail\") +\n  coord_cartesian(xlim = c(-4, 4)) +\n  theme_minimal()\n\np_close + p_far\n```\n\n::: {.cell-output-display}\n![Two possible t-statistics: one at 0.85 (consistent with H₀) and one at 2.8 (in the tail, suggesting we reject H₀).](unit5_files/figure-pdf/fig-t-test-comparison-1.pdf){#fig-t-test-comparison fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nA t-statistic of 0.85 falls well within the \"body\" of the distribution---values like this occur frequently when $H_0$ is true.\nBut a t-statistic of 2.8 is out in the tail---such extreme values are rare when $H_0$ is true.\n\n\n### Critical Values and Rejection Regions\n\nTo formalize our decision rule, we need to define:\n\n1. **Significance level ($\\alpha$):** The probability of rejecting $H_0$ when it's actually true (Type I error). Common choices: 10%, 5%, or 1%.\n\n2. **Critical value ($c$):** The threshold value of the t-statistic beyond which we reject $H_0$.\n\nFor a two-sided test at the 5% level, we reject $H_0$ if $|t_{\\hat{\\beta}_j}| > c$, where $c$ is the critical value that leaves 2.5% of the distribution in each tail.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Calculate critical value for 5% significance, two-sided\nalpha <- 0.05\nc_val <- qt(alpha/2, df = df_value, lower.tail = FALSE)\n\n# Create shading data for rejection regions\nt_grid <- seq(-4, 4, length.out = 500)\nt_dens <- dt(t_grid, df = df_value)\n\nshade_data <- tibble(t_value = t_grid, density = t_dens) |>\n  mutate(\n    rejection = t_value < -c_val | t_value > c_val\n  )\n\nggplot() +\n  # Full distribution\n  geom_area(data = shade_data |> filter(!rejection),\n            aes(x = t_value, y = density),\n            fill = \"lightblue\", alpha = 0.7) +\n  # Rejection regions\n  geom_area(data = shade_data |> filter(rejection),\n            aes(x = t_value, y = density),\n            fill = \"red\", alpha = 0.5) +\n  # Distribution curve\n  stat_function(fun = dt, args = list(df = df_value),\n                color = \"darkblue\", linewidth = 1.2) +\n  # Critical value lines\n  geom_vline(xintercept = c(-c_val, c_val), \n             color = \"darkgoldenrod\", linewidth = 1.2, linetype = \"dashed\") +\n  # Annotations\n  annotate(\"text\", x = -c_val, y = 0.42, \n           label = paste0(\"-\", round(c_val, 2)),\n           color = \"darkgoldenrod\", size = 4, hjust = 1.1) +\n  annotate(\"text\", x = c_val, y = 0.42, \n           label = paste0(\"+\", round(c_val, 2)),\n           color = \"darkgoldenrod\", size = 4, hjust = -0.1) +\n  annotate(\"text\", x = 0, y = 0.2,\n           label = \"Fail to reject H₀\\n(95%)\",\n           color = \"darkblue\", size = 4) +\n  annotate(\"text\", x = 3.2, y = 0.05,\n           label = \"Reject H₀\\n(2.5%)\",\n           color = \"red\", size = 3) +\n  annotate(\"text\", x = -3.2, y = 0.05,\n           label = \"Reject H₀\\n(2.5%)\",\n           color = \"red\", size = 3) +\n  labs(x = \"t-values\", y = \"Density\") +\n  coord_cartesian(xlim = c(-4, 4)) +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Fail to reject H₀' in 'mbcsToSbcs': dot substituted for\n<e2>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Fail to reject H₀' in 'mbcsToSbcs': dot substituted for\n<82>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Fail to reject H₀' in 'mbcsToSbcs': dot substituted for\n<80>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Reject H₀' in 'mbcsToSbcs': dot substituted for <e2>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Reject H₀' in 'mbcsToSbcs': dot substituted for <82>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Reject H₀' in 'mbcsToSbcs': dot substituted for <80>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Reject H₀' in 'mbcsToSbcs': dot substituted for <e2>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Reject H₀' in 'mbcsToSbcs': dot substituted for <82>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'Reject H₀' in 'mbcsToSbcs': dot substituted for <80>\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Critical values for a two-sided test at the 5% significance level. We reject H₀ if |t| > 1.96.](unit5_files/figure-pdf/fig-critical-values-1.pdf){#fig-critical-values fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\n### Hypothesis Testing Example\n\nLet's work through a complete example.\nWe'll create some simulated housing data and test whether lot area affects sale price:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create simulated housing data\nset.seed(2025)\nn <- 500\n\nhousing_data <- tibble(\n  lot_area = runif(n, 5000, 20000),\n  pool_area = rbinom(n, 1, 0.15) * runif(n, 200, 600),\n  garage_area = runif(n, 200, 800),\n  year_built = sample(1960:2020, n, replace = TRUE),\n  year_remod = pmax(year_built, sample(1980:2023, n, replace = TRUE)),\n  # True relationship: lot_area has effect of $1.50 per sq ft\n  sale_price = -2500000 + 1.50 * lot_area + 80 * pool_area + \n               150 * garage_area + 500 * year_built + \n               900 * year_remod + rnorm(n, 0, 50000)\n)\n\n# Estimate the regression\nreg_housing <- lm(sale_price ~ lot_area + pool_area + garage_area + \n                    year_built + year_remod, \n                  data = housing_data)\n\nsummary(reg_housing)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sale_price ~ lot_area + pool_area + garage_area + \n    year_built + year_remod, data = housing_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-134582  -32117     138   32584  167861 \n\nCoefficients:\n                 Estimate    Std. Error t value             Pr(>|t|)    \n(Intercept) -2369345.4532   407348.8976  -5.817         0.0000000108 ***\nlot_area           1.5528        0.5207   2.982             0.003002 ** \npool_area         81.5522       14.6980   5.549         0.0000000470 ***\ngarage_area      167.0837       13.4931  12.383 < 0.0000000000000002 ***\nyear_built       554.2853      143.8278   3.854             0.000132 ***\nyear_remod       775.7472      223.5861   3.470             0.000567 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 51130 on 494 degrees of freedom\nMultiple R-squared:  0.3396,\tAdjusted R-squared:  0.3329 \nF-statistic: 50.81 on 5 and 494 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\n\n\n\n\nTo test $H_0: \\beta_1 = 0$ (lot area has no effect):\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract the coefficient and standard error for lot_area\nb1_hat <- coef(reg_housing)[\"lot_area\"]\nse_b1 <- summary(reg_housing)$coefficients[\"lot_area\", \"Std. Error\"]\n\n# Calculate the t-statistic\nt_stat <- b1_hat / se_b1\n\n# Find the critical value at 5% significance\nsig_level <- 0.05\nn_obs <- nobs(reg_housing)\nk <- 5  # number of independent variables\ndf <- n_obs - k - 1\n\nt_crit <- qt(sig_level / 2, df = df, lower.tail = FALSE)\n\n# Display results\ncat(\"Estimate:\", round(b1_hat, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimate: 1.5528 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Standard Error:\", round(se_b1, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandard Error: 0.5207 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"t-statistic:\", round(t_stat, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt-statistic: 2.98 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Critical value (5%):\", round(t_crit, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCritical value (5%): 1.96 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Reject H₀?\", abs(t_stat) > t_crit, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReject H₀? TRUE \n```\n\n\n:::\n:::\n\n\n\n\n\n\nSince $|t_{\\hat{\\beta}_1}|$ exceeds the critical value of approximately 1.96, we **reject the null hypothesis** that lot area has no effect on sale price.\nThe estimate is **statistically significant at the 5% level**.\n\n\n### Rule of Thumb\n\nWith modern datasets that have hundreds or thousands of observations, the critical value for a two-sided 5% test is essentially always **1.96 ≈ 2**.\n\nThis gives us a handy rule of thumb:\n\n::: {.callout-tip}\n## The \"Rule of 2\"\nAn estimate is statistically significant at the 5% level if:\n\n$$|\\hat{\\beta}_j| > 2 \\times se(\\hat{\\beta}_j)$$\n\nIn other words, if your estimate is more than twice as large as its standard error, you can reject the null hypothesis of no effect at the 5% level.\n:::\n\n\n## P-Values\n\nWhile the t-test with a fixed significance level is useful, it has limitations.\nSaying an estimate is \"significant at 5%\" doesn't tell us *how strongly* we reject the null.\nWas it a narrow rejection or a \"knock out\"?\n\nThe **p-value** answers this question:\n\n::: {.callout-important}\n## Definition: P-Value\nThe p-value is the smallest significance level at which we would reject the null hypothesis.\n\nEquivalently: the p-value is the probability of observing a t-statistic as extreme (or more extreme) as the one we calculated, *if the null hypothesis were true*.\n:::\n\n### Visualizing P-Values\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Parameters\ndf_viz <- 250\nobserved_t <- 2.3\n\n# Calculate p-value\np_val <- 2 * pt(abs(observed_t), df = df_viz, lower.tail = FALSE)\n\n# Create the visualization\nt_grid <- seq(-4, 4, length.out = 500)\nt_dens <- dt(t_grid, df = df_viz)\n\nshade_data <- tibble(t_value = t_grid, density = t_dens) |>\n  mutate(\n    in_tail = abs(t_value) >= abs(observed_t)\n  )\n\nggplot() +\n  # Main curve\n  geom_line(data = shade_data, aes(x = t_value, y = density),\n            color = \"darkblue\", linewidth = 1.2) +\n  # Shaded tails (p-value area)\n  geom_area(data = shade_data |> filter(in_tail & t_value > 0),\n            aes(x = t_value, y = density),\n            fill = \"red\", alpha = 0.6) +\n  geom_area(data = shade_data |> filter(in_tail & t_value < 0),\n            aes(x = t_value, y = density),\n            fill = \"red\", alpha = 0.6) +\n  # Observed t-statistic lines\n  geom_vline(xintercept = c(-observed_t, observed_t),\n             color = \"darkgreen\", linewidth = 1, linetype = \"dashed\") +\n  # Annotations\n  annotate(\"text\", x = observed_t + 0.3, y = 0.05,\n           label = paste0(\"Observed t = \", observed_t),\n           color = \"darkgreen\", size = 4, hjust = 0) +\n  annotate(\"text\", x = 0, y = 0.2,\n           label = paste0(\"P-value = \", round(p_val, 4)),\n           color = \"red\", size = 5) +\n  labs(\n    title = \"P-Value Visualization\",\n    subtitle = paste0(\"df = \", df_viz, \", Observed t = \", observed_t),\n    x = \"t-statistic\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![The p-value is the total shaded area in both tails beyond the observed t-statistic.](unit5_files/figure-pdf/fig-pvalue-viz-1.pdf){#fig-pvalue-viz fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n### Interpreting P-Values\n\nThe p-value tells us the probability of getting our estimate (or something more extreme) if the null were true:\n\n- **p = 0.035:** There's a 3.5% chance of getting our estimate if $\\beta_j = 0$. That's quite unlikely---evidence against $H_0$.\n\n- **p = 0.35:** There's a 35% chance of getting our estimate if $\\beta_j = 0$. That's not unusual at all---no evidence against $H_0$.\n\nCommon decision rules:\n\n- p < 0.10: Reject $H_0$ at 10% level (weak evidence against $H_0$)\n- p < 0.05: Reject $H_0$ at 5% level (moderate evidence against $H_0$)\n- p < 0.01: Reject $H_0$ at 1% level (strong evidence against $H_0$)\n\n\n### A Note on Language\n\nWhen we *cannot* reject the null hypothesis, we say:\n\n> \"We **fail to reject** the null at the x% level.\"\n\nWe do **not** say we \"accept\" the null.\nWhy? Because there are many possible values of $\\beta_j$ that we would also fail to reject.\nFailing to reject $\\beta_j = 0$ doesn't mean $\\beta_j$ actually equals zero---it just means our data aren't precise enough to distinguish $\\beta_j$ from zero.\n\n\n### Statistical vs. Practical Significance\n\n::: {.callout-warning}\n## Important Distinction\n**Statistical significance** and **practical (economic) significance** are not the same thing!\n\nA coefficient can be statistically significant but practically unimportant.\nThis is especially common in very large samples, where even tiny effects can be detected.\n:::\n\nFor example, suppose we find that an additional year of education increases wages by $0.50 per year, and this is statistically significant with p < 0.001.\nStatistically, we're very confident the effect isn't zero.\nBut practically, a 50-cent annual raise is economically trivial.\n\nAlways interpret the *magnitude* of coefficients, not just their statistical significance.\n\n\n:::: {.content-visible when-format=\"html\"}\n\n::: {.problem}\n\n<div class=\"context\">\n**Quick Check: Hypothesis Testing**\n</div>\n\n<div class=\"question\">\n<div class=\"answer-row\">\n<label>If you get a t-statistic of 1.5 (with many degrees of freedom), can you reject H₀ at the 5% level?</label>\n<select onchange=\"checkAnswer(this, 'b')\">\n<option value=\"\">Select answer...</option>\n<option value=\"a\">Yes, because 1.5 > 0</option>\n<option value=\"b\">No, because 1.5 < 1.96</option>\n<option value=\"c\">Yes, because 1.5 > 1</option>\n<option value=\"d\">Cannot determine without the p-value</option>\n</select>\n</div>\n</div>\n\n<div class=\"question\">\n<div class=\"answer-row\">\n<label>A p-value of 0.03 means:</label>\n<select onchange=\"checkAnswer(this, 'b')\">\n<option value=\"\">Select answer...</option>\n<option value=\"a\">There's a 3% chance the null hypothesis is true</option>\n<option value=\"b\">There's a 3% chance of seeing data this extreme if H₀ were true</option>\n<option value=\"c\">The coefficient is 3% of the standard error</option>\n<option value=\"d\">We reject H₀ at the 1% level</option>\n</select>\n</div>\n</div>\n\n<div class=\"question\">\n<div class=\"answer-row\">\n<label>An estimate of β̂ = 0.001 with SE = 0.0001 and p < 0.001 means:</label>\n<select onchange=\"checkAnswer(this, 'c')\">\n<option value=\"\">Select answer...</option>\n<option value=\"a\">The effect is both statistically and practically significant</option>\n<option value=\"b\">The effect is neither statistically nor practically significant</option>\n<option value=\"c\">The effect is statistically significant but may not be practically significant</option>\n<option value=\"d\">The effect is practically significant but not statistically significant</option>\n</select>\n</div>\n</div>\n\n:::\n\n::::\n\n:::: {.content-hidden when-format=\"html\"}\n\n*Quick Check: This section contains interactive content only available in the HTML version.*\n\n::::\n\n\n## Confidence Intervals\n\nAnother way to quantify uncertainty is through **confidence intervals**.\nWhile hypothesis tests ask \"is $\\beta_j$ different from zero?\", confidence intervals ask \"what range of values is $\\beta_j$ likely to fall within?\"\n\n### Computing a Confidence Interval\n\nA confidence interval at the $(1 - \\alpha)$ level is:\n\n$$\\hat{\\beta}_j \\pm c_{\\alpha} \\times se(\\hat{\\beta}_j)$$\n\nwhere $c_{\\alpha}$ is the critical value at significance level $\\alpha$.\n\nFor a 95% confidence interval with large samples:\n\n$$\\hat{\\beta}_j \\pm 1.96 \\times se(\\hat{\\beta}_j)$$\n\n\n### Example\n\nUsing our housing regression:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 95% confidence interval for lot_area coefficient\nlower <- b1_hat - 1.96 * se_b1\nupper <- b1_hat + 1.96 * se_b1\n\ncat(\"Point estimate:\", round(b1_hat, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoint estimate: 1.5528 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI: [\", round(lower, 4), \",\", round(upper, 4), \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: [ 0.5323 , 2.5733 ]\n```\n\n\n:::\n\n```{.r .cell-code}\n# Or use confint() function\nconfint(reg_housing, \"lot_area\", level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             2.5 %  97.5 %\nlot_area 0.5298262 2.57581\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n### Interpreting Confidence Intervals\n\n> \"We are 95% confident that the true effect of lot area on sale price is between $0.53 and $2.57 per square foot.\"\n\nMore precisely: if we drew 100 different samples and computed 100 different confidence intervals, about 95 of them would contain the true $\\beta_j$.\n\n**Key insight:** If the confidence interval includes zero, the estimate is *not* statistically significant at that level.\n\n\n### Simulation: Understanding Confidence Intervals\n\nLet's run a simulation to see what \"95% confidence\" really means:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(456)\n\n# True parameter value\ntrue_beta1 <- 1.50\n\n# Generate 20 samples and compute CIs\nn_samples <- 20\n\nci_data <- map_dfr(1:n_samples, function(i) {\n  # Generate new sample\n  sample_data <- tibble(\n    lot_area = runif(500, 5000, 20000),\n    pool_area = rbinom(500, 1, 0.15) * runif(500, 200, 600),\n    garage_area = runif(500, 200, 800),\n    year_built = sample(1960:2020, 500, replace = TRUE),\n    year_remod = pmax(year_built, sample(1980:2023, 500, replace = TRUE)),\n    sale_price = -2500000 + true_beta1 * lot_area + 80 * pool_area + \n                 150 * garage_area + 500 * year_built + \n                 900 * year_remod + rnorm(500, 0, 50000)\n  )\n  \n  # Fit model\n  reg <- lm(sale_price ~ lot_area + pool_area + garage_area + \n              year_built + year_remod, data = sample_data)\n  \n  # Get CI\n  ci <- confint(reg, \"lot_area\", level = 0.95)\n  \n  tibble(\n    sample = i,\n    estimate = coef(reg)[\"lot_area\"],\n    lower = ci[1],\n    upper = ci[2],\n    covers_true = lower <= true_beta1 & upper >= true_beta1\n  )\n})\n\nggplot(ci_data, aes(y = sample)) +\n  geom_vline(xintercept = true_beta1, linetype = \"dashed\", \n             color = \"darkgreen\", linewidth = 1) +\n  geom_errorbarh(aes(xmin = lower, xmax = upper, \n                     color = covers_true),\n                 height = 0.3, linewidth = 0.8) +\n  geom_point(aes(x = estimate, color = covers_true), size = 2) +\n  scale_color_manual(values = c(\"TRUE\" = \"steelblue\", \"FALSE\" = \"red\"),\n                     labels = c(\"TRUE\" = \"Contains true value\",\n                                \"FALSE\" = \"Misses true value\")) +\n  annotate(\"text\", x = true_beta1 + 0.05, y = 21,\n           label = paste0(\"True β₁ = \", true_beta1),\n           color = \"darkgreen\", size = 4, hjust = 0) +\n  labs(\n    x = expression(hat(beta)[1]),\n    y = \"Sample\",\n    color = NULL\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'True β₁ = 1.5' in 'mbcsToSbcs': dot substituted for <ce>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'True β₁ = 1.5' in 'mbcsToSbcs': dot substituted for <b2>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'True β₁ = 1.5' in 'mbcsToSbcs': dot substituted for <e2>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'True β₁ = 1.5' in 'mbcsToSbcs': dot substituted for <82>\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nconversion failure on 'True β₁ = 1.5' in 'mbcsToSbcs': dot substituted for <81>\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Twenty 95% confidence intervals from different samples. The true β₁ = 1.50 (dashed line). About 95% of intervals capture the true value.](unit5_files/figure-pdf/fig-ci-simulation-1.pdf){#fig-ci-simulation fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\n## T-Tests, P-Values, and CIs: A Comparison\n\nThese three approaches are closely related but answer slightly different questions:\n\n| Method | Question Answered |\n|--------|-------------------|\n| T-statistic | Is my estimate large relative to the noise in the data? |\n| P-value | What's the probability of seeing my estimate if $H_0$ were true? |\n| Confidence Interval | What range of values is plausible for $\\beta_j$? |\n\nAll three are mathematically connected:\n\n- If $|t| > 1.96$, then p < 0.05, and the 95% CI excludes zero\n- If p < 0.05, then $|t| > 1.96$, and the 95% CI excludes zero\n- If the 95% CI excludes zero, then p < 0.05 and $|t| > 1.96$\n\n\n## Reading Regression Tables\n\nNow that we understand statistical inference, we can properly interpret the regression tables you'll encounter in academic papers.\n\n### From R Output to Publication Format\n\nWhen you run `summary()` on a regression in R, you get detailed but messy output.\nAcademic papers present this information in a standardized, clean format using tables.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Standard R output\nsummary(reg_housing)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sale_price ~ lot_area + pool_area + garage_area + \n    year_built + year_remod, data = housing_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-134582  -32117     138   32584  167861 \n\nCoefficients:\n                 Estimate    Std. Error t value             Pr(>|t|)    \n(Intercept) -2369345.4532   407348.8976  -5.817         0.0000000108 ***\nlot_area           1.5528        0.5207   2.982             0.003002 ** \npool_area         81.5522       14.6980   5.549         0.0000000470 ***\ngarage_area      167.0837       13.4931  12.383 < 0.0000000000000002 ***\nyear_built       554.2853      143.8278   3.854             0.000132 ***\nyear_remod       775.7472      223.5861   3.470             0.000567 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 51130 on 494 degrees of freedom\nMultiple R-squared:  0.3396,\tAdjusted R-squared:  0.3329 \nF-statistic: 50.81 on 5 and 494 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\n\n\n\n\nIn a publication, this same information would appear as:\n\n\n\n\n\n\n::: {#tbl-housing-reg .cell tbl-cap='The Effect of Lot Area on Home Sale Price'}\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{talltblr}[         %% tabularray outer open\nentry=none,label=none,\nnote{}={* p \\num{< 0.1}, ** p \\num{< 0.05}, *** p \\num{< 0.01}},\nnote{ }={Standard errors in parentheses. * p < 0.1, ** p < 0.05, *** p < 0.01},\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]},\ncolumn{2}={}{halign=c,},\ncolumn{1}={}{halign=l,},\nhline{14}={1,2}{solid, black, 0.05em},\n}                     %% tabularray inner close\n\\toprule\n& Sale Price \\\\ \\midrule %% TinyTableHeader\n(Intercept) & \\num{-2369345.453}*** \\\\\n& (\\num{407348.898}) \\\\\nLot Area (sq ft) & \\num{1.553}*** \\\\\n& (\\num{0.521}) \\\\\nPool Area & \\num{81.552}*** \\\\\n& (\\num{14.698}) \\\\\nGarage Area & \\num{167.084}*** \\\\\n& (\\num{13.493}) \\\\\nYear Built & \\num{554.285}*** \\\\\n& (\\num{143.828}) \\\\\nYear Remodeled & \\num{775.747}*** \\\\\n& (\\num{223.586}) \\\\\nNum.Obs. & \\num{500} \\\\\nR2 & \\num{0.340} \\\\\nR2 Adj. & \\num{0.333} \\\\\n\\bottomrule\n\\end{talltblr}\n\\end{table}\n:::\n:::\n\n\n\n\n\n\n### Decoding the Table Structure\n\n**Rows are variables:** The top indicates the dependent variable.\nRows below show independent variables and the constant (intercept).\n\n**The main numbers are coefficients:** Each cell contains $\\hat{\\beta}_j$.\n\n**Numbers in parentheses are standard errors:** These are $se(\\hat{\\beta}_j)$.\n\n**Stars indicate significance levels:**\n\n- \\* = significant at 10% level (p < 0.10)\n- \\*\\* = significant at 5% level (p < 0.05)\n- \\*\\*\\* = significant at 1% level (p < 0.01)\n\n**Bottom statistics:** Sample size (N), R-squared, and sometimes other diagnostics.\n\n\n### Multiple Columns Show Robustness\n\nMost regression tables have multiple columns, each representing a different specification.\nThis lets readers see how estimates change as controls are added:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Three specifications with increasing controls\nreg1 <- lm(sale_price ~ lot_area, data = housing_data)\nreg2 <- lm(sale_price ~ lot_area + pool_area + garage_area, data = housing_data)\nreg3 <- lm(sale_price ~ lot_area + pool_area + garage_area + \n             year_built + year_remod, data = housing_data)\n```\n:::\n\n::: {#tbl-housing-multi .cell tbl-cap='The Effect of Lot Area on Home Sale Price: Multiple Specifications'}\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{talltblr}[         %% tabularray outer open\nentry=none,label=none,\nnote{}={* p \\num{< 0.1}, ** p \\num{< 0.05}, *** p \\num{< 0.01}},\nnote{ }={Standard errors in parentheses. * p < 0.1, ** p < 0.05, *** p < 0.01},\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]Q[]},\ncolumn{2,3,4}={}{halign=c,},\ncolumn{1}={}{halign=l,},\nhline{14}={1,2,3,4}{solid, black, 0.05em},\n}                     %% tabularray inner close\n\\toprule\n& (1) & (2) & (3) \\\\ \\midrule %% TinyTableHeader\n(Intercept) & \\num{385464.906}*** & \\num{288761.744}*** & \\num{-2369345.453}*** \\\\\n& (\\num{8462.611}) & (\\num{10454.349}) & (\\num{407348.898}) \\\\\nLot Area (sq ft) & \\num{1.038} & \\num{1.472}*** & \\num{1.553}*** \\\\\n& (\\num{0.635}) & (\\num{0.545}) & (\\num{0.521}) \\\\\nPool Area &  & \\num{86.081}*** & \\num{81.552}*** \\\\\n&  & (\\num{15.352}) & (\\num{14.698}) \\\\\nGarage Area &  & \\num{170.687}*** & \\num{167.084}*** \\\\\n&  & (\\num{14.112}) & (\\num{13.493}) \\\\\nYear Built &  &  & \\num{554.285}*** \\\\\n&  &  & (\\num{143.828}) \\\\\nYear Remodeled &  &  & \\num{775.747}*** \\\\\n&  &  & (\\num{223.586}) \\\\\nNum.Obs. & \\num{500} & \\num{500} & \\num{500} \\\\\nR2 & \\num{0.005} & \\num{0.274} & \\num{0.340} \\\\\nR2 Adj. & \\num{0.003} & \\num{0.269} & \\num{0.333} \\\\\n\\bottomrule\n\\end{talltblr}\n\\end{table}\n:::\n:::\n\n\n\n\n\n\nNotice how the coefficient on Lot Area changes across specifications.\nIn column (1), without controls, the estimate is different from column (3).\nThis pattern often reveals omitted variable bias in simpler specifications.\n\n\n### What to Look for in Regression Tables\n\n1. **What is the coefficient on the variable of interest?** How do we interpret it?\n\n2. **Is it statistically significant?** At what level?\n\n3. **How does the coefficient change across specifications?** Does it remain stable or shift dramatically?\n\n4. **Are the sample size and R-squared reasonable?** Very small N or very low R² might raise concerns.\n\n\n::: {.problem}\n\n<div class=\"context\">\n**Practice: Reading a Regression Table**\n\nConsider this table examining the effect of stock performance on CEO salary:\n</div>\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{talltblr}[         %% tabularray outer open\ncaption={Effect of Stock Performance on CEO Salary},\nnote{}={* p \\num{< 0.1}, ** p \\num{< 0.05}, *** p \\num{< 0.01}},\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]},\ncolumn{2,3}={}{halign=c,},\ncolumn{1}={}{halign=l,},\nhline{8}={1,2,3}{solid, black, 0.05em},\n}                     %% tabularray inner close\n\\toprule\n& (1) & (2) \\\\ \\midrule %% TinyTableHeader\n(Intercept) & \\num{6.806}*** & \\num{4.788}*** \\\\\n& (\\num{0.041}) & (\\num{0.234}) \\\\\nReturn on Stock (\\%) & \\num{0.001} & \\num{0.001} \\\\\n& (\\num{0.001}) & (\\num{0.001}) \\\\\nLog(Sales) &  & \\num{0.287}*** \\\\\n&  & (\\num{0.033}) \\\\\nNum.Obs. & \\num{209} & \\num{209} \\\\\nR2 Adj. & \\num{-0.004} & \\num{0.264} \\\\\n\\bottomrule\n\\end{talltblr}\n\\end{table}\n:::\n:::\n\n\n\n\n\n\n<div class=\"question\">\n<div class=\"answer-row\">\n<label>Is the effect of Return on Stock statistically significant at the 5% level in Column (1)?</label>\n<select onchange=\"checkAnswer(this, 'b')\">\n<option value=\"\">Select answer...</option>\n<option value=\"a\">Yes</option>\n<option value=\"b\">No</option>\n</select>\n</div>\n</div>\n\n<div class=\"question\">\n<div class=\"answer-row\">\n<label>What happens to the Adjusted R² when we add log(Sales) as a control?</label>\n<select onchange=\"checkAnswer(this, 'a')\">\n<option value=\"\">Select answer...</option>\n<option value=\"a\">It increases substantially</option>\n<option value=\"b\">It decreases</option>\n<option value=\"c\">It stays about the same</option>\n</select>\n</div>\n</div>\n\n<div class=\"question\">\n<div class=\"answer-row\">\n<label>Based on this table, which variable appears to be a more important determinant of CEO salary?</label>\n<select onchange=\"checkAnswer(this, 'b')\">\n<option value=\"\">Select answer...</option>\n<option value=\"a\">Return on Stock</option>\n<option value=\"b\">Company Sales</option>\n<option value=\"c\">Both are equally important</option>\n</select>\n</div>\n</div>\n\n:::\n\n\n## F-Tests: Testing Multiple Hypotheses\n\nSometimes we want to test hypotheses about *multiple* coefficients simultaneously.\nFor example: \"Do experience AND tenure jointly affect wages?\"\n\nThe **F-test** allows us to test such joint hypotheses.\n\n\n### Why Not Just Use Multiple t-Tests?\n\nYou might think: \"Why not just run separate t-tests on each coefficient?\"\n\nThere are two problems:\n\n1. **No restrictions on other parameters:** A t-test on $\\beta_2$ puts no restrictions on $\\beta_3$. If the variables are correlated, this can be misleading.\n\n2. **Multiple comparisons problem:** If you run many tests at the 5% level, you'll reject *some* true null hypotheses just by chance. With 20 tests, you'd expect about 1 false rejection even if all nulls are true!\n\nThe F-test controls for these issues.\n\n\n### Setting Up the F-Test\n\nConsider the wage model:\n\n$$\\log(wage) = \\beta_0 + \\beta_1(education) + \\beta_2(experience) + \\beta_3(tenure) + \\beta_4(age) + \\mu$$\n\nSuppose we want to test whether on-the-job training variables (experience and tenure) matter at all:\n\n$$H_0: \\beta_2 = \\beta_3 = 0$$\n$$H_1: H_0 \\text{ is not true}$$\n\nThe alternative is satisfied if *either* $\\beta_2 \\neq 0$ or $\\beta_3 \\neq 0$ (or both).\n\n\n### Computing the F-Statistic\n\nThe F-test compares two models:\n\n**Unrestricted Model:** The full model with all variables\n$$UR: \\widehat{\\log(wage)} = \\hat{\\beta}_0 + \\hat{\\beta}_1(educ) + \\hat{\\beta}_2(exper) + \\hat{\\beta}_3(tenure) + \\hat{\\beta}_4(age)$$\n\n**Restricted Model:** The model assuming the null is true (dropping the restricted variables)\n$$R: \\widehat{\\log(wage)} = \\hat{\\beta}_0 + \\hat{\\beta}_1(educ) + \\hat{\\beta}_4(age)$$\n\nThe F-statistic is:\n\n$$F = \\frac{(SSR_R - SSR_{UR})/q}{SSR_{UR}/df_{UR}}$$\n\nwhere:\n\n- $SSR_R$ = Sum of squared residuals from restricted model\n- $SSR_{UR}$ = Sum of squared residuals from unrestricted model\n- $q$ = Number of restrictions (variables dropped)\n- $df_{UR}$ = Degrees of freedom in unrestricted model ($n - k - 1$)\n\n\n### F-Test Example\n\nLet's test whether year built and year remodeled jointly affect home prices:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Unrestricted model (full model)\nreg_unrestricted <- lm(sale_price ~ lot_area + pool_area + garage_area + \n                         year_built + year_remod, \n                       data = housing_data)\n\n# Restricted model (dropping year variables)\nreg_restricted <- lm(sale_price ~ lot_area + pool_area + garage_area,\n                     data = housing_data)\n\n# Compute F-statistic manually\nssr_r <- sum(resid(reg_restricted)^2)\nssr_ur <- sum(resid(reg_unrestricted)^2)\ndf_ur <- df.residual(reg_unrestricted)\nq <- 2  # number of restrictions\n\nf_numerator <- (ssr_r - ssr_ur) / q\nf_denominator <- ssr_ur / df_ur\nf_stat <- f_numerator / f_denominator\n\n# Critical value at 5% significance\nf_crit <- qf(0.05, df1 = q, df2 = df_ur, lower.tail = FALSE)\n\ncat(\"F-statistic:\", round(f_stat, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nF-statistic: 24.69 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Critical value (5%):\", round(f_crit, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCritical value (5%): 3.01 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Reject H₀?\", f_stat > f_crit, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReject H₀? TRUE \n```\n\n\n:::\n:::\n\n\n\n\n\n\nSince the F-statistic exceeds the critical value, we **reject the null hypothesis**.\nYear built and year remodeled are **jointly statistically significant**---they collectively improve the model's fit.\n\n\n### Using R's anova() Function\n\nIn practice, you'll use R's `anova()` function to perform F-tests:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(reg_restricted, reg_unrestricted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: sale_price ~ lot_area + pool_area + garage_area\nModel 2: sale_price ~ lot_area + pool_area + garage_area + year_built + \n    year_remod\n  Res.Df           RSS Df    Sum of Sq      F           Pr(>F)    \n1    496 1420348267818                                            \n2    494 1291292854097  2 129055413721 24.686 0.00000000006048 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe output shows the F-statistic, degrees of freedom, and p-value directly.\n\n\n### The F-Statistic in Terms of R²\n\nThe F-statistic can also be written in terms of R-squared values:\n\n$$F = \\frac{(R^2_{UR} - R^2_R)/q}{(1 - R^2_{UR})/df_{UR}}$$\n\nThis shows that the F-test is essentially asking: *Does the unrestricted model fit the data significantly better than the restricted model?*\n\nIf $R^2_{UR}$ is much larger than $R^2_R$, the F-statistic will be large, and we'll reject the null.\n\n\n::: {.callout-note}\n## Properties of the F-Test\n\n- The F-statistic is always non-negative, so F-tests are always **one-sided**\n- If the null is rejected, we say the variables are **jointly statistically significant**\n- We cannot determine *which* individual variable is significant---only that at least one is\n- If variables are jointly insignificant, it provides justification for dropping them from the model\n:::\n\n\n## Chapter Summary\n\n::: {.callout-tip}\n## Key Takeaways\n\n1. **Statistical inference** allows us to move from sample estimates to statements about population parameters, accounting for sampling variability.\n\n2. The **sampling distribution** of $\\hat{\\beta}_j$ describes how our estimates would vary across repeated samples. Under the normality assumption (or with large samples), it follows a normal distribution.\n\n3. **Hypothesis testing** uses the t-statistic to determine whether our estimate is \"far enough\" from zero to reject the null hypothesis: $t = \\hat{\\beta}_j / se(\\hat{\\beta}_j)$\n\n4. **P-values** tell us the probability of seeing our data if the null were true. Smaller p-values provide stronger evidence against $H_0$.\n\n5. **Confidence intervals** provide a range of plausible values for the population parameter. A 95% CI excludes zero if and only if the estimate is significant at the 5% level.\n\n6. **Statistical significance ≠ practical significance.** Always consider the magnitude of effects, not just their p-values.\n\n7. **F-tests** allow us to test multiple hypotheses simultaneously, avoiding the multiple comparisons problem.\n\n8. **Regression tables** in academic papers present coefficients, standard errors (in parentheses), and significance stars. Multiple columns show robustness across specifications.\n:::\n\n\n## Practice Exercises\n\n:::: {.content-visible when-format=\"html\"}\n\n\n\n\n\n\n```{=html}\n<div class=\"problem\">\n\n<div class=\"context\" style=\"margin-bottom: 20px;\">\n<strong>Practice: Interpreting t-Statistics and Hypothesis Testing</strong>\n</div>\n\n<div class=\"context\" style=\"margin-bottom: 20px;\">\n<strong>Scenario:</strong> Consider a regression where \\(\\hat{\\beta}_1 = 2.5\\) and \\(se(\\hat{\\beta}_1) = 0.8\\). Assume a large sample size (df > 100).\n</div>\n\n<div class=\"question\">\n<div class=\"answer-row\">\n    <label>i. The t-statistic for testing \\(H_0: \\beta_1 = 0\\) is: </label>\n    <select onchange=\"checkAnswer(this, 'c')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">2.0</option>\n        <option value=\"b\">2.5</option>\n        <option value=\"c\">3.125</option>\n        <option value=\"d\">0.32</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>ii. Is this estimate statistically significant at the 5% level? </label>\n    <select onchange=\"checkAnswer(this, 'a')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Yes, because |t| > 1.96</option>\n        <option value=\"b\">No, because |t| < 1.96</option>\n        <option value=\"c\">Yes, because the estimate is positive</option>\n        <option value=\"d\">Cannot determine without the p-value</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>iii. Is this estimate statistically significant at the 1% level (critical value ≈ 2.58)? </label>\n    <select onchange=\"checkAnswer(this, 'a')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Yes, because |t| > 2.58</option>\n        <option value=\"b\">No, because |t| < 2.58</option>\n        <option value=\"c\">Yes, because it was significant at 5%</option>\n        <option value=\"d\">Cannot determine</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>iv. The 95% confidence interval for \\(\\beta_1\\) is approximately: </label>\n    <select onchange=\"checkAnswer(this, 'b')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">[1.70, 3.30]</option>\n        <option value=\"b\">[0.93, 4.07]</option>\n        <option value=\"c\">[2.50, 4.50]</option>\n        <option value=\"d\">[0.00, 5.00]</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>v. If someone claimed that \\(\\beta_1 = 4\\), does the 95% CI support or contradict this claim? </label>\n    <select onchange=\"checkAnswer(this, 'a')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">The CI includes 4, so we cannot reject β₁ = 4</option>\n        <option value=\"b\">The CI excludes 4, so we can reject β₁ = 4</option>\n        <option value=\"c\">CIs cannot be used to evaluate claims about specific values</option>\n        <option value=\"d\">We need the p-value to answer this</option>\n    </select>\n</div>\n</div>\n\n<div class=\"context\" style=\"margin-top: 30px; margin-bottom: 20px;\">\n<strong>Practice: Understanding P-Values</strong>\n</div>\n\n<div class=\"question\">\n<div class=\"answer-row\">\n    <label>vi. A p-value of 0.001 means: </label>\n    <select onchange=\"checkAnswer(this, 'b')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">There is a 0.1% chance the null hypothesis is true</option>\n        <option value=\"b\">If H₀ were true, there's a 0.1% chance of seeing data this extreme</option>\n        <option value=\"c\">The coefficient equals 0.001</option>\n        <option value=\"d\">We should accept the null hypothesis</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>vii. With p = 0.001, we can reject H₀ at which significance levels? </label>\n    <select onchange=\"checkAnswer(this, 'd')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Only the 10% level</option>\n        <option value=\"b\">The 10% and 5% levels</option>\n        <option value=\"c\">Only the 1% level</option>\n        <option value=\"d\">The 10%, 5%, and 1% levels</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>viii. With p = 0.047, we can reject H₀ at which significance levels? </label>\n    <select onchange=\"checkAnswer(this, 'b')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Only the 10% level</option>\n        <option value=\"b\">The 10% and 5% levels, but not the 1% level</option>\n        <option value=\"c\">The 10%, 5%, and 1% levels</option>\n        <option value=\"d\">None of these levels</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>ix. With p = 0.082, we can reject H₀ at which significance levels? </label>\n    <select onchange=\"checkAnswer(this, 'a')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Only the 10% level</option>\n        <option value=\"b\">The 10% and 5% levels</option>\n        <option value=\"c\">The 10%, 5%, and 1% levels</option>\n        <option value=\"d\">None of these levels</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>x. With p = 0.523, we can reject H₀ at which significance levels? </label>\n    <select onchange=\"checkAnswer(this, 'd')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Only the 10% level</option>\n        <option value=\"b\">The 10% and 5% levels</option>\n        <option value=\"c\">The 10%, 5%, and 1% levels</option>\n        <option value=\"d\">None of these levels</option>\n    </select>\n</div>\n</div>\n\n<div class=\"context\" style=\"margin-top: 30px; margin-bottom: 20px;\">\n<strong>Practice: Statistical vs. Practical Significance</strong>\n</div>\n\n<div class=\"question\">\n<div class=\"answer-row\">\n    <label>xi. A study finds that an additional year of education increases annual wages by $50, with p < 0.001 (n = 500,000). This effect is: </label>\n    <select onchange=\"checkAnswer(this, 'c')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Both statistically and practically significant</option>\n        <option value=\"b\">Neither statistically nor practically significant</option>\n        <option value=\"c\">Statistically significant but practically insignificant</option>\n        <option value=\"d\">Practically significant but not statistically significant</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>xii. Why can very large samples detect tiny, unimportant effects? </label>\n    <select onchange=\"checkAnswer(this, 'b')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Large samples have more bias</option>\n        <option value=\"b\">Standard errors shrink as n increases, making small effects detectable</option>\n        <option value=\"c\">P-values are calculated differently for large samples</option>\n        <option value=\"d\">The critical value increases with sample size</option>\n    </select>\n</div>\n</div>\n\n<div class=\"context\" style=\"margin-top: 30px; margin-bottom: 20px;\">\n<strong>Practice: F-Tests for Joint Hypotheses</strong>\n</div>\n\n<div class=\"context\" style=\"margin-bottom: 20px;\">\n<strong>Scenario:</strong> You estimate a model of house prices with: lot area, garage size, bedrooms, bathrooms, year built, and 20 neighborhood dummy variables. You want to test whether neighborhood matters for house prices.\n</div>\n\n<div class=\"question\">\n<div class=\"answer-row\">\n    <label>xiii. The null hypothesis for testing whether \"neighborhood matters\" is: </label>\n    <select onchange=\"checkAnswer(this, 'b')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">H₀: At least one neighborhood coefficient equals zero</option>\n        <option value=\"b\">H₀: All 20 neighborhood coefficients equal zero</option>\n        <option value=\"c\">H₀: The neighborhood coefficients are all equal to each other</option>\n        <option value=\"d\">H₀: The F-statistic equals zero</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>xiv. How many restrictions (q) are you testing? </label>\n    <select onchange=\"checkAnswer(this, 'c')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">1</option>\n        <option value=\"b\">5</option>\n        <option value=\"c\">20</option>\n        <option value=\"d\">21</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>xv. If the F-statistic is 3.45 and the critical value is 1.57, what do you conclude? </label>\n    <select onchange=\"checkAnswer(this, 'a')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Reject H₀; neighborhoods are jointly significant</option>\n        <option value=\"b\">Fail to reject H₀; neighborhoods are not significant</option>\n        <option value=\"c\">Cannot determine without the p-value</option>\n        <option value=\"d\">The test is invalid because F > 1</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>xvi. If the F-test rejects the null, can we conclude that every individual neighborhood dummy is statistically significant? </label>\n    <select onchange=\"checkAnswer(this, 'b')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Yes, rejecting the joint null means all are significant</option>\n        <option value=\"b\">No, we only know at least one is different from zero</option>\n        <option value=\"c\">Yes, if F > critical value then each t > critical value</option>\n        <option value=\"d\">Cannot determine</option>\n    </select>\n</div>\n</div>\n\n<div class=\"context\" style=\"margin-top: 30px; margin-bottom: 20px;\">\n<strong>Practice: Reading Regression Tables</strong>\n</div>\n\n<div class=\"context\" style=\"margin-bottom: 20px;\">\n<strong>Regression Output:</strong> A researcher studies the determinants of college GPA:\n<pre style=\"background-color: #f5f5f5; padding: 10px; margin-top: 10px; font-family: monospace;\">\nDependent variable: college_gpa (scale: 0-4)\n\n                 Estimate  Std. Error   p-value\n(Intercept)        1.250      0.180     < 0.001\nhigh_school_gpa    0.520      0.045     < 0.001\nsat_score          0.001      0.0003    < 0.001\nathlete           -0.085      0.062      0.171\nlegacy             0.142      0.058      0.015\n\nn = 2,450, Adjusted R-squared = 0.31\n</pre>\n<em>Note: athlete = 1 if varsity athlete; legacy = 1 if parent attended the college</em>\n</div>\n\n<div class=\"question\">\n<div class=\"answer-row\">\n    <label>xvii. A 100-point increase in SAT score is associated with what change in college GPA? </label>\n    <select onchange=\"checkAnswer(this, 'b')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">0.001 points</option>\n        <option value=\"b\">0.1 points (one-tenth of a GPA point)</option>\n        <option value=\"c\">1.0 points</option>\n        <option value=\"d\">0.01 points</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>xviii. The coefficient on \"athlete\" is: </label>\n    <select onchange=\"checkAnswer(this, 'b')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Statistically significant at the 5% level</option>\n        <option value=\"b\">Not statistically significant at the 5% level</option>\n        <option value=\"c\">Statistically significant at the 1% level</option>\n        <option value=\"d\">Cannot determine from this output</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>xix. Comparing two students with identical high school GPAs and SAT scores, where one is a legacy and one is not, the legacy student has a predicted college GPA that is: </label>\n    <select onchange=\"checkAnswer(this, 'c')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">0.142 points lower</option>\n        <option value=\"b\">14.2% higher</option>\n        <option value=\"c\">0.142 points higher</option>\n        <option value=\"d\">Cannot determine without knowing athlete status</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>xx. <strong>(Challenge)</strong> Based on the standard error for \"athlete\" (0.062), the 95% CI for the athlete effect is approximately: </label>\n    <select onchange=\"checkAnswer(this, 'a')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">[-0.207, 0.037]</option>\n        <option value=\"b\">[-0.147, -0.023]</option>\n        <option value=\"c\">[0.023, 0.147]</option>\n        <option value=\"d\">[-0.085, 0.085]</option>\n    </select>\n</div>\n\n<div class=\"answer-row\">\n    <label>xxi. <strong>(Challenge)</strong> The fact that the athlete CI includes zero is consistent with: </label>\n    <select onchange=\"checkAnswer(this, 'c')\">\n        <option value=\"\">-- Select Answer --</option>\n        <option value=\"a\">Athletes definitely have the same GPA as non-athletes</option>\n        <option value=\"b\">The coefficient is biased</option>\n        <option value=\"c\">The p-value being greater than 0.05</option>\n        <option value=\"d\">A statistically significant result</option>\n    </select>\n</div>\n</div>\n\n</div>\n```\n\n\n\n\n\n\n::: {.callout-tip collapse=\"true\"}\n## Show Explanation\n\n**t-Statistics and Hypothesis Testing (i-v):**\n\ni. The t-statistic is calculated as $t = \\hat{\\beta}_1 / se(\\hat{\\beta}_1) = 2.5 / 0.8 = 3.125$.\n\nii. Since $|t| = 3.125 > 1.96$, we reject $H_0$ at the 5% level. The estimate is statistically significant.\n\niii. Since $|t| = 3.125 > 2.58$, we also reject $H_0$ at the 1% level. The estimate is highly significant.\n\niv. The 95% CI is $\\hat{\\beta}_1 \\pm 1.96 \\times se(\\hat{\\beta}_1) = 2.5 \\pm 1.96 \\times 0.8 = 2.5 \\pm 1.568 = [0.93, 4.07]$.\n\nv. Since 4 falls within the confidence interval [0.93, 4.07], we cannot reject the hypothesis that $\\beta_1 = 4$ at the 5% level. The CI supports (or at least doesn't contradict) this claim.\n\n**Understanding P-Values (vi-x):**\n\nvi. The p-value is the probability of observing data as extreme as ours *if the null hypothesis were true*. It is NOT the probability that the null is true.\n\nvii. With p = 0.001, we can reject at all three levels (10%, 5%, and 1%) because 0.001 < 0.01 < 0.05 < 0.10.\n\nviii. With p = 0.047, we can reject at 10% (0.047 < 0.10) and 5% (0.047 < 0.05), but not at 1% (0.047 > 0.01).\n\nix. With p = 0.082, we can only reject at 10% (0.082 < 0.10), but not at 5% (0.082 > 0.05) or 1%.\n\nx. With p = 0.523, we cannot reject at any conventional level. There is a 52.3% chance of seeing data this extreme if $H_0$ were true---not unusual at all.\n\n**Statistical vs. Practical Significance (xi-xii):**\n\nxi. A $50/year effect is statistically significant (p < 0.001) but practically trivial. This is less than 25 cents per hour---hardly worth an extra year of schooling! Large samples can detect tiny effects.\n\nxii. The standard error shrinks as $n$ increases (specifically, $se \\propto 1/\\sqrt{n}$). With huge samples, even tiny deviations from zero become \"detectable\" statistically, even if they're meaningless practically.\n\n**F-Tests (xiii-xvi):**\n\nxiii. The null hypothesis is that ALL 20 neighborhood coefficients equal zero jointly: $H_0: \\beta_{n1} = \\beta_{n2} = ... = \\beta_{n20} = 0$. If any neighborhood differs from the baseline, $H_0$ is false.\n\nxiv. You are testing 20 restrictions---one for each neighborhood dummy variable set to zero.\n\nxv. Since F = 3.45 > 1.57 = critical value, we reject $H_0$. Neighborhoods are jointly statistically significant---they collectively help explain house prices.\n\nxvi. Rejecting the joint null only tells us that at least one neighborhood coefficient differs from zero. Some individual neighborhoods might not be significantly different from the baseline---we'd need individual t-tests to determine which ones.\n\n**Reading Regression Tables (xvii-xxi):**\n\nxvii. The coefficient on SAT is 0.001, meaning each 1-point increase in SAT is associated with a 0.001 increase in GPA. For 100 points: $100 \\times 0.001 = 0.1$ GPA points.\n\nxviii. The p-value for athlete is 0.171, which is greater than 0.05. Therefore, the coefficient is NOT statistically significant at the 5% level.\n\nxix. The coefficient on legacy (0.142) is the difference in predicted GPA between legacy and non-legacy students, holding other variables constant. Legacy students are predicted to have GPAs 0.142 points higher.\n\nxx. The 95% CI is $-0.085 \\pm 1.96 \\times 0.062 = -0.085 \\pm 0.122 = [-0.207, 0.037]$. This interval includes zero.\n\nxxi. When a 95% CI includes zero, it means we cannot reject $H_0: \\beta = 0$ at the 5% level---which is consistent with the p-value being 0.171 > 0.05. The CI and hypothesis test always agree.\n\n:::\n\n::::\n\n:::: {.content-hidden when-format=\"html\"}\n\n*Note: This section contains interactive content only available in the HTML version.*\n\n::::\n",
    "supporting": [
      "unit5_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\UseTblrLibrary{booktabs}\",\"\\\\UseTblrLibrary{rotating}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\UseTblrLibrary{booktabs}\",\"\\\\UseTblrLibrary{rotating}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\UseTblrLibrary{booktabs}\",\"\\\\UseTblrLibrary{rotating}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}