project:
  type: book
  output-dir: ../docs
  resources:
   - robots.txt

book:
  title: "EC325 Workbook"
  subtitle: "EC325: Econometrics | Colby College"
  author: "Prof. Caraher"
  date: today
  date-format: long
  publisher-place: "Waterville, ME"
  downloads: [pdf, epub]
  page-footer: <span class="faux-block"> &copy; 2025 Raymond Caraher. All rights reserved. </span>
  back-to-top-navigation: true
  sidebar:
    style: "floating"
    search: true
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/data_practices.qmd
    - chapters/rcts.qmd
    - chapters/bivariate_ols.qmd
    - chapters/multivariate_ols.qmd
    - chapters/statistical_inference.qmd
    - chapters/dummies_nonlins.qmd
    - chapters/heteroskedasticity.qmd
    - chapters/binary_outcomes.qmd
    - chapters/panel_fe.qmd
    - chapters/did.qmd
    - chapters/advanced_did.qmd
    - chapters/instrumental_variables.qmd
    - chapters/references.qmd
  appendices:
    - chapters/installingR.qmd
    - chapters/git_github.qmd
    - chapters/statsreview.qmd
    - chapters/r_reference.qmd

bibliography: references.bib
fig-cap-location: top
format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
  epub:
    toc: true



