project:
  type: book

book:
  title: "Econometrics Lecture Notes"
  subtitle: "EC 325 | Colby College"
  author: "Prof. Caraher"
  date: "10/17/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



