# Introduction {#sec-introduction}

This is a book created from markdown and executable code.

::: {.callout-tip collapse="true"}
## **Key Concepts**
- Learn the difference between correlation and causation.
:::

## What is this Class About?

This class is obviously dedicated to the study of econometrics (endearingly shortened `metrics).
But what exactly does econometrics entail?
What differentiates it from broader terms such as "statistical analysis" or "data analysis"?

From @wooldridge_introductory_2019, we get a classic definition of econometrics:

> "...statistical methods for estimating economic relationships, testing economic theories, and evaluating and implementing government and business policy."

However, my view of econometrics is at the same time, broader and more narrow:

::: {.callout-note}
## **Econometrics**
The practice of using statistical, quantitative methods to study social phenomena and provide insights into public policy.
More specifically,
modern econometrics has focused on identifying the **causal effects** of social phenomena/policy as opposed to **correlations**.
:::

In other words, I view the practice of econometrics as the use of quantitative methods to understand the social world around us,
with a special (though not exclusive) lens focusing on separating correlation from causation.

## Does Having Health Insurance *Cause* You to be Healthier?

Let's think about a critical question in public policy: *does having health insurance make someone healthier*?
This is especially an important question in the context of the United States,
which does not have a public health insurance system.
Instead, it is a predominantly private system entangled with a complex net of social safety nets meant to provide a patchwork of coverage to the most marginalized.

However, as of XXX, YYY do not have any health insurance coverage.
Would the US as a whole be better off guarantee health insurance coverage for everyone?
If health insurance makes people healthier,
then there may be a strong case to do so.
If not, the benefits of such a system would become, at the very least, more opaque.


